# Copy of contrib/libs/grpc/src/compiler/grpc_python_plugin
# Generated by devtools/yamaker.

IF (HOST_OS_DARWIN AND HOST_ARCH_X86_64 OR
    HOST_OS_LINUX AND HOST_ARCH_X86_64 OR
    HOST_OS_WINDOWS AND HOST_ARCH_X86_64)
    ENABLE(VALID_HOST_PLATFORM_FOR_PREBUILT_GRPC_PYTHON)
ENDIF()

IF (NOT USE_PREBUILT_TOOLS OR NOT VALID_HOST_PLATFORM_FOR_PREBUILT_GRPC_PYTHON)
    PROGRAM()

    

    LICENSE(Apache-2.0)

    PEERDIR(
        contrib/libs/grpc/src/compiler/grpc_plugin_support
    )

    ADDINCL(
        contrib/libs/grpc
        contrib/libs/grpc/include
    )

    NO_COMPILER_WARNINGS()

    CFLAGS(
        -DGRPC_USE_ABSL=0
    )

    SRCDIR(contrib/libs/grpc/src/compiler)

    IF (OS_LINUX AND NOT MUSL)
        CFLAGS(
            -DGPR_BACKWARDS_COMPATIBILITY_MODE=1
        )
    ENDIF()

    SRCS(
        python_plugin.cc
    )

    END()
ELSE()
    PREBUILT_PROGRAM()

    PEERDIR(build/external_resources/arcadia_grpc_python)

    PRIMARY_OUTPUT(${ARCADIA_GRPC_PYTHON_RESOURCE_GLOBAL}/grpc_python${MODULE_SUFFIX})

    END()
ENDIF()
