
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-12T16:59:13+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2cb96529396d93b46abab7bbc73a208e708c642e",
 "version": "1.2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
