# Generated by devtools/yamaker from nixpkgs 22.05.

LIBRARY()

LICENSE(
    Apache-2.0 AND
    Apache-2.0 WITH LLVM-exception AND
    BSD-2-Clause AND
    BSD-2-Clause-Views AND
    BSD-3-Clause AND
    BSL-1.0 AND
    Bsd-Unmodified AND
    CC0-1.0 AND
    LicenseRef-scancode-unknown-license-reference AND
    MIT AND
    NCSA AND
    Sunpro
)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)



VERSION(1.17.2)

ORIGINAL_SOURCE(https://github.com/NVIDIA/thrust/archive/1.17.2.tar.gz)

ADDINCL(
    GLOBAL contrib/libs/nvidia/thrust
)

NO_COMPILER_WARNINGS()

NO_RUNTIME()

END()
