# Generated by devtools/yamaker (pypi).

PY23_LIBRARY()



VERSION(2.4.7)

LICENSE(MIT)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    pyparsing.py
)

RESOURCE_FILES(
    PREFIX contrib/python/pyparsing/
    .dist-info/METADATA
    .dist-info/top_level.txt
)

END()
