

PY23_LIBRARY()

VERSION(2018.9)

LICENSE(MIT)

PY_SRCS(
    TOP_LEVEL
    pytz/__init__.py
    pytz/exceptions.py
    pytz/lazy.py
    pytz/reference.py
    pytz/tzfile.py
    pytz/tzinfo.py
)

RESOURCE(
    .dist-info/METADATA /fs/contrib/python/pytz/.dist-info/METADATA
    pytz/zoneinfo/Africa/Abidjan /pytz_data/zoneinfo/Africa/Abidjan
    pytz/zoneinfo/Africa/Accra /pytz_data/zoneinfo/Africa/Accra
    pytz/zoneinfo/Africa/Addis_Ababa /pytz_data/zoneinfo/Africa/Addis_Ababa
    pytz/zoneinfo/Africa/Algiers /pytz_data/zoneinfo/Africa/Algiers
    pytz/zoneinfo/Africa/Asmara /pytz_data/zoneinfo/Africa/Asmara
    pytz/zoneinfo/Africa/Asmera /pytz_data/zoneinfo/Africa/Asmera
    pytz/zoneinfo/Africa/Bamako /pytz_data/zoneinfo/Africa/Bamako
    pytz/zoneinfo/Africa/Bangui /pytz_data/zoneinfo/Africa/Bangui
    pytz/zoneinfo/Africa/Banjul /pytz_data/zoneinfo/Africa/Banjul
    pytz/zoneinfo/Africa/Bissau /pytz_data/zoneinfo/Africa/Bissau
    pytz/zoneinfo/Africa/Blantyre /pytz_data/zoneinfo/Africa/Blantyre
    pytz/zoneinfo/Africa/Brazzaville /pytz_data/zoneinfo/Africa/Brazzaville
    pytz/zoneinfo/Africa/Bujumbura /pytz_data/zoneinfo/Africa/Bujumbura
    pytz/zoneinfo/Africa/Cairo /pytz_data/zoneinfo/Africa/Cairo
    pytz/zoneinfo/Africa/Casablanca /pytz_data/zoneinfo/Africa/Casablanca
    pytz/zoneinfo/Africa/Ceuta /pytz_data/zoneinfo/Africa/Ceuta
    pytz/zoneinfo/Africa/Conakry /pytz_data/zoneinfo/Africa/Conakry
    pytz/zoneinfo/Africa/Dakar /pytz_data/zoneinfo/Africa/Dakar
    pytz/zoneinfo/Africa/Dar_es_Salaam /pytz_data/zoneinfo/Africa/Dar_es_Salaam
    pytz/zoneinfo/Africa/Djibouti /pytz_data/zoneinfo/Africa/Djibouti
    pytz/zoneinfo/Africa/Douala /pytz_data/zoneinfo/Africa/Douala
    pytz/zoneinfo/Africa/El_Aaiun /pytz_data/zoneinfo/Africa/El_Aaiun
    pytz/zoneinfo/Africa/Freetown /pytz_data/zoneinfo/Africa/Freetown
    pytz/zoneinfo/Africa/Gaborone /pytz_data/zoneinfo/Africa/Gaborone
    pytz/zoneinfo/Africa/Harare /pytz_data/zoneinfo/Africa/Harare
    pytz/zoneinfo/Africa/Johannesburg /pytz_data/zoneinfo/Africa/Johannesburg
    pytz/zoneinfo/Africa/Juba /pytz_data/zoneinfo/Africa/Juba
    pytz/zoneinfo/Africa/Kampala /pytz_data/zoneinfo/Africa/Kampala
    pytz/zoneinfo/Africa/Khartoum /pytz_data/zoneinfo/Africa/Khartoum
    pytz/zoneinfo/Africa/Kigali /pytz_data/zoneinfo/Africa/Kigali
    pytz/zoneinfo/Africa/Kinshasa /pytz_data/zoneinfo/Africa/Kinshasa
    pytz/zoneinfo/Africa/Lagos /pytz_data/zoneinfo/Africa/Lagos
    pytz/zoneinfo/Africa/Libreville /pytz_data/zoneinfo/Africa/Libreville
    pytz/zoneinfo/Africa/Lome /pytz_data/zoneinfo/Africa/Lome
    pytz/zoneinfo/Africa/Luanda /pytz_data/zoneinfo/Africa/Luanda
    pytz/zoneinfo/Africa/Lubumbashi /pytz_data/zoneinfo/Africa/Lubumbashi
    pytz/zoneinfo/Africa/Lusaka /pytz_data/zoneinfo/Africa/Lusaka
    pytz/zoneinfo/Africa/Malabo /pytz_data/zoneinfo/Africa/Malabo
    pytz/zoneinfo/Africa/Maputo /pytz_data/zoneinfo/Africa/Maputo
    pytz/zoneinfo/Africa/Maseru /pytz_data/zoneinfo/Africa/Maseru
    pytz/zoneinfo/Africa/Mbabane /pytz_data/zoneinfo/Africa/Mbabane
    pytz/zoneinfo/Africa/Mogadishu /pytz_data/zoneinfo/Africa/Mogadishu
    pytz/zoneinfo/Africa/Monrovia /pytz_data/zoneinfo/Africa/Monrovia
    pytz/zoneinfo/Africa/Nairobi /pytz_data/zoneinfo/Africa/Nairobi
    pytz/zoneinfo/Africa/Ndjamena /pytz_data/zoneinfo/Africa/Ndjamena
    pytz/zoneinfo/Africa/Niamey /pytz_data/zoneinfo/Africa/Niamey
    pytz/zoneinfo/Africa/Nouakchott /pytz_data/zoneinfo/Africa/Nouakchott
    pytz/zoneinfo/Africa/Ouagadougou /pytz_data/zoneinfo/Africa/Ouagadougou
    pytz/zoneinfo/Africa/Porto-Novo /pytz_data/zoneinfo/Africa/Porto-Novo
    pytz/zoneinfo/Africa/Sao_Tome /pytz_data/zoneinfo/Africa/Sao_Tome
    pytz/zoneinfo/Africa/Timbuktu /pytz_data/zoneinfo/Africa/Timbuktu
    pytz/zoneinfo/Africa/Tripoli /pytz_data/zoneinfo/Africa/Tripoli
    pytz/zoneinfo/Africa/Tunis /pytz_data/zoneinfo/Africa/Tunis
    pytz/zoneinfo/Africa/Windhoek /pytz_data/zoneinfo/Africa/Windhoek
    pytz/zoneinfo/America/Adak /pytz_data/zoneinfo/America/Adak
    pytz/zoneinfo/America/Anchorage /pytz_data/zoneinfo/America/Anchorage
    pytz/zoneinfo/America/Anguilla /pytz_data/zoneinfo/America/Anguilla
    pytz/zoneinfo/America/Antigua /pytz_data/zoneinfo/America/Antigua
    pytz/zoneinfo/America/Araguaina /pytz_data/zoneinfo/America/Araguaina
    pytz/zoneinfo/America/Argentina/Buenos_Aires /pytz_data/zoneinfo/America/Argentina/Buenos_Aires
    pytz/zoneinfo/America/Argentina/Catamarca /pytz_data/zoneinfo/America/Argentina/Catamarca
    pytz/zoneinfo/America/Argentina/ComodRivadavia /pytz_data/zoneinfo/America/Argentina/ComodRivadavia
    pytz/zoneinfo/America/Argentina/Cordoba /pytz_data/zoneinfo/America/Argentina/Cordoba
    pytz/zoneinfo/America/Argentina/Jujuy /pytz_data/zoneinfo/America/Argentina/Jujuy
    pytz/zoneinfo/America/Argentina/La_Rioja /pytz_data/zoneinfo/America/Argentina/La_Rioja
    pytz/zoneinfo/America/Argentina/Mendoza /pytz_data/zoneinfo/America/Argentina/Mendoza
    pytz/zoneinfo/America/Argentina/Rio_Gallegos /pytz_data/zoneinfo/America/Argentina/Rio_Gallegos
    pytz/zoneinfo/America/Argentina/Salta /pytz_data/zoneinfo/America/Argentina/Salta
    pytz/zoneinfo/America/Argentina/San_Juan /pytz_data/zoneinfo/America/Argentina/San_Juan
    pytz/zoneinfo/America/Argentina/San_Luis /pytz_data/zoneinfo/America/Argentina/San_Luis
    pytz/zoneinfo/America/Argentina/Tucuman /pytz_data/zoneinfo/America/Argentina/Tucuman
    pytz/zoneinfo/America/Argentina/Ushuaia /pytz_data/zoneinfo/America/Argentina/Ushuaia
    pytz/zoneinfo/America/Aruba /pytz_data/zoneinfo/America/Aruba
    pytz/zoneinfo/America/Asuncion /pytz_data/zoneinfo/America/Asuncion
    pytz/zoneinfo/America/Atikokan /pytz_data/zoneinfo/America/Atikokan
    pytz/zoneinfo/America/Atka /pytz_data/zoneinfo/America/Atka
    pytz/zoneinfo/America/Bahia /pytz_data/zoneinfo/America/Bahia
    pytz/zoneinfo/America/Bahia_Banderas /pytz_data/zoneinfo/America/Bahia_Banderas
    pytz/zoneinfo/America/Barbados /pytz_data/zoneinfo/America/Barbados
    pytz/zoneinfo/America/Belem /pytz_data/zoneinfo/America/Belem
    pytz/zoneinfo/America/Belize /pytz_data/zoneinfo/America/Belize
    pytz/zoneinfo/America/Blanc-Sablon /pytz_data/zoneinfo/America/Blanc-Sablon
    pytz/zoneinfo/America/Boa_Vista /pytz_data/zoneinfo/America/Boa_Vista
    pytz/zoneinfo/America/Bogota /pytz_data/zoneinfo/America/Bogota
    pytz/zoneinfo/America/Boise /pytz_data/zoneinfo/America/Boise
    pytz/zoneinfo/America/Buenos_Aires /pytz_data/zoneinfo/America/Buenos_Aires
    pytz/zoneinfo/America/Cambridge_Bay /pytz_data/zoneinfo/America/Cambridge_Bay
    pytz/zoneinfo/America/Campo_Grande /pytz_data/zoneinfo/America/Campo_Grande
    pytz/zoneinfo/America/Cancun /pytz_data/zoneinfo/America/Cancun
    pytz/zoneinfo/America/Caracas /pytz_data/zoneinfo/America/Caracas
    pytz/zoneinfo/America/Catamarca /pytz_data/zoneinfo/America/Catamarca
    pytz/zoneinfo/America/Cayenne /pytz_data/zoneinfo/America/Cayenne
    pytz/zoneinfo/America/Cayman /pytz_data/zoneinfo/America/Cayman
    pytz/zoneinfo/America/Chicago /pytz_data/zoneinfo/America/Chicago
    pytz/zoneinfo/America/Chihuahua /pytz_data/zoneinfo/America/Chihuahua
    pytz/zoneinfo/America/Coral_Harbour /pytz_data/zoneinfo/America/Coral_Harbour
    pytz/zoneinfo/America/Cordoba /pytz_data/zoneinfo/America/Cordoba
    pytz/zoneinfo/America/Costa_Rica /pytz_data/zoneinfo/America/Costa_Rica
    pytz/zoneinfo/America/Creston /pytz_data/zoneinfo/America/Creston
    pytz/zoneinfo/America/Cuiaba /pytz_data/zoneinfo/America/Cuiaba
    pytz/zoneinfo/America/Curacao /pytz_data/zoneinfo/America/Curacao
    pytz/zoneinfo/America/Danmarkshavn /pytz_data/zoneinfo/America/Danmarkshavn
    pytz/zoneinfo/America/Dawson /pytz_data/zoneinfo/America/Dawson
    pytz/zoneinfo/America/Dawson_Creek /pytz_data/zoneinfo/America/Dawson_Creek
    pytz/zoneinfo/America/Denver /pytz_data/zoneinfo/America/Denver
    pytz/zoneinfo/America/Detroit /pytz_data/zoneinfo/America/Detroit
    pytz/zoneinfo/America/Dominica /pytz_data/zoneinfo/America/Dominica
    pytz/zoneinfo/America/Edmonton /pytz_data/zoneinfo/America/Edmonton
    pytz/zoneinfo/America/Eirunepe /pytz_data/zoneinfo/America/Eirunepe
    pytz/zoneinfo/America/El_Salvador /pytz_data/zoneinfo/America/El_Salvador
    pytz/zoneinfo/America/Ensenada /pytz_data/zoneinfo/America/Ensenada
    pytz/zoneinfo/America/Fort_Nelson /pytz_data/zoneinfo/America/Fort_Nelson
    pytz/zoneinfo/America/Fort_Wayne /pytz_data/zoneinfo/America/Fort_Wayne
    pytz/zoneinfo/America/Fortaleza /pytz_data/zoneinfo/America/Fortaleza
    pytz/zoneinfo/America/Glace_Bay /pytz_data/zoneinfo/America/Glace_Bay
    pytz/zoneinfo/America/Godthab /pytz_data/zoneinfo/America/Godthab
    pytz/zoneinfo/America/Goose_Bay /pytz_data/zoneinfo/America/Goose_Bay
    pytz/zoneinfo/America/Grand_Turk /pytz_data/zoneinfo/America/Grand_Turk
    pytz/zoneinfo/America/Grenada /pytz_data/zoneinfo/America/Grenada
    pytz/zoneinfo/America/Guadeloupe /pytz_data/zoneinfo/America/Guadeloupe
    pytz/zoneinfo/America/Guatemala /pytz_data/zoneinfo/America/Guatemala
    pytz/zoneinfo/America/Guayaquil /pytz_data/zoneinfo/America/Guayaquil
    pytz/zoneinfo/America/Guyana /pytz_data/zoneinfo/America/Guyana
    pytz/zoneinfo/America/Halifax /pytz_data/zoneinfo/America/Halifax
    pytz/zoneinfo/America/Havana /pytz_data/zoneinfo/America/Havana
    pytz/zoneinfo/America/Hermosillo /pytz_data/zoneinfo/America/Hermosillo
    pytz/zoneinfo/America/Indiana/Indianapolis /pytz_data/zoneinfo/America/Indiana/Indianapolis
    pytz/zoneinfo/America/Indiana/Knox /pytz_data/zoneinfo/America/Indiana/Knox
    pytz/zoneinfo/America/Indiana/Marengo /pytz_data/zoneinfo/America/Indiana/Marengo
    pytz/zoneinfo/America/Indiana/Petersburg /pytz_data/zoneinfo/America/Indiana/Petersburg
    pytz/zoneinfo/America/Indiana/Tell_City /pytz_data/zoneinfo/America/Indiana/Tell_City
    pytz/zoneinfo/America/Indiana/Vevay /pytz_data/zoneinfo/America/Indiana/Vevay
    pytz/zoneinfo/America/Indiana/Vincennes /pytz_data/zoneinfo/America/Indiana/Vincennes
    pytz/zoneinfo/America/Indiana/Winamac /pytz_data/zoneinfo/America/Indiana/Winamac
    pytz/zoneinfo/America/Indianapolis /pytz_data/zoneinfo/America/Indianapolis
    pytz/zoneinfo/America/Inuvik /pytz_data/zoneinfo/America/Inuvik
    pytz/zoneinfo/America/Iqaluit /pytz_data/zoneinfo/America/Iqaluit
    pytz/zoneinfo/America/Jamaica /pytz_data/zoneinfo/America/Jamaica
    pytz/zoneinfo/America/Jujuy /pytz_data/zoneinfo/America/Jujuy
    pytz/zoneinfo/America/Juneau /pytz_data/zoneinfo/America/Juneau
    pytz/zoneinfo/America/Kentucky/Louisville /pytz_data/zoneinfo/America/Kentucky/Louisville
    pytz/zoneinfo/America/Kentucky/Monticello /pytz_data/zoneinfo/America/Kentucky/Monticello
    pytz/zoneinfo/America/Knox_IN /pytz_data/zoneinfo/America/Knox_IN
    pytz/zoneinfo/America/Kralendijk /pytz_data/zoneinfo/America/Kralendijk
    pytz/zoneinfo/America/La_Paz /pytz_data/zoneinfo/America/La_Paz
    pytz/zoneinfo/America/Lima /pytz_data/zoneinfo/America/Lima
    pytz/zoneinfo/America/Los_Angeles /pytz_data/zoneinfo/America/Los_Angeles
    pytz/zoneinfo/America/Louisville /pytz_data/zoneinfo/America/Louisville
    pytz/zoneinfo/America/Lower_Princes /pytz_data/zoneinfo/America/Lower_Princes
    pytz/zoneinfo/America/Maceio /pytz_data/zoneinfo/America/Maceio
    pytz/zoneinfo/America/Managua /pytz_data/zoneinfo/America/Managua
    pytz/zoneinfo/America/Manaus /pytz_data/zoneinfo/America/Manaus
    pytz/zoneinfo/America/Marigot /pytz_data/zoneinfo/America/Marigot
    pytz/zoneinfo/America/Martinique /pytz_data/zoneinfo/America/Martinique
    pytz/zoneinfo/America/Matamoros /pytz_data/zoneinfo/America/Matamoros
    pytz/zoneinfo/America/Mazatlan /pytz_data/zoneinfo/America/Mazatlan
    pytz/zoneinfo/America/Mendoza /pytz_data/zoneinfo/America/Mendoza
    pytz/zoneinfo/America/Menominee /pytz_data/zoneinfo/America/Menominee
    pytz/zoneinfo/America/Merida /pytz_data/zoneinfo/America/Merida
    pytz/zoneinfo/America/Metlakatla /pytz_data/zoneinfo/America/Metlakatla
    pytz/zoneinfo/America/Mexico_City /pytz_data/zoneinfo/America/Mexico_City
    pytz/zoneinfo/America/Miquelon /pytz_data/zoneinfo/America/Miquelon
    pytz/zoneinfo/America/Moncton /pytz_data/zoneinfo/America/Moncton
    pytz/zoneinfo/America/Monterrey /pytz_data/zoneinfo/America/Monterrey
    pytz/zoneinfo/America/Montevideo /pytz_data/zoneinfo/America/Montevideo
    pytz/zoneinfo/America/Montreal /pytz_data/zoneinfo/America/Montreal
    pytz/zoneinfo/America/Montserrat /pytz_data/zoneinfo/America/Montserrat
    pytz/zoneinfo/America/Nassau /pytz_data/zoneinfo/America/Nassau
    pytz/zoneinfo/America/New_York /pytz_data/zoneinfo/America/New_York
    pytz/zoneinfo/America/Nipigon /pytz_data/zoneinfo/America/Nipigon
    pytz/zoneinfo/America/Nome /pytz_data/zoneinfo/America/Nome
    pytz/zoneinfo/America/Noronha /pytz_data/zoneinfo/America/Noronha
    pytz/zoneinfo/America/North_Dakota/Beulah /pytz_data/zoneinfo/America/North_Dakota/Beulah
    pytz/zoneinfo/America/North_Dakota/Center /pytz_data/zoneinfo/America/North_Dakota/Center
    pytz/zoneinfo/America/North_Dakota/New_Salem /pytz_data/zoneinfo/America/North_Dakota/New_Salem
    pytz/zoneinfo/America/Ojinaga /pytz_data/zoneinfo/America/Ojinaga
    pytz/zoneinfo/America/Panama /pytz_data/zoneinfo/America/Panama
    pytz/zoneinfo/America/Pangnirtung /pytz_data/zoneinfo/America/Pangnirtung
    pytz/zoneinfo/America/Paramaribo /pytz_data/zoneinfo/America/Paramaribo
    pytz/zoneinfo/America/Phoenix /pytz_data/zoneinfo/America/Phoenix
    pytz/zoneinfo/America/Port-au-Prince /pytz_data/zoneinfo/America/Port-au-Prince
    pytz/zoneinfo/America/Port_of_Spain /pytz_data/zoneinfo/America/Port_of_Spain
    pytz/zoneinfo/America/Porto_Acre /pytz_data/zoneinfo/America/Porto_Acre
    pytz/zoneinfo/America/Porto_Velho /pytz_data/zoneinfo/America/Porto_Velho
    pytz/zoneinfo/America/Puerto_Rico /pytz_data/zoneinfo/America/Puerto_Rico
    pytz/zoneinfo/America/Punta_Arenas /pytz_data/zoneinfo/America/Punta_Arenas
    pytz/zoneinfo/America/Rainy_River /pytz_data/zoneinfo/America/Rainy_River
    pytz/zoneinfo/America/Rankin_Inlet /pytz_data/zoneinfo/America/Rankin_Inlet
    pytz/zoneinfo/America/Recife /pytz_data/zoneinfo/America/Recife
    pytz/zoneinfo/America/Regina /pytz_data/zoneinfo/America/Regina
    pytz/zoneinfo/America/Resolute /pytz_data/zoneinfo/America/Resolute
    pytz/zoneinfo/America/Rio_Branco /pytz_data/zoneinfo/America/Rio_Branco
    pytz/zoneinfo/America/Rosario /pytz_data/zoneinfo/America/Rosario
    pytz/zoneinfo/America/Santa_Isabel /pytz_data/zoneinfo/America/Santa_Isabel
    pytz/zoneinfo/America/Santarem /pytz_data/zoneinfo/America/Santarem
    pytz/zoneinfo/America/Santiago /pytz_data/zoneinfo/America/Santiago
    pytz/zoneinfo/America/Santo_Domingo /pytz_data/zoneinfo/America/Santo_Domingo
    pytz/zoneinfo/America/Sao_Paulo /pytz_data/zoneinfo/America/Sao_Paulo
    pytz/zoneinfo/America/Scoresbysund /pytz_data/zoneinfo/America/Scoresbysund
    pytz/zoneinfo/America/Shiprock /pytz_data/zoneinfo/America/Shiprock
    pytz/zoneinfo/America/Sitka /pytz_data/zoneinfo/America/Sitka
    pytz/zoneinfo/America/St_Barthelemy /pytz_data/zoneinfo/America/St_Barthelemy
    pytz/zoneinfo/America/St_Johns /pytz_data/zoneinfo/America/St_Johns
    pytz/zoneinfo/America/St_Kitts /pytz_data/zoneinfo/America/St_Kitts
    pytz/zoneinfo/America/St_Lucia /pytz_data/zoneinfo/America/St_Lucia
    pytz/zoneinfo/America/St_Thomas /pytz_data/zoneinfo/America/St_Thomas
    pytz/zoneinfo/America/St_Vincent /pytz_data/zoneinfo/America/St_Vincent
    pytz/zoneinfo/America/Swift_Current /pytz_data/zoneinfo/America/Swift_Current
    pytz/zoneinfo/America/Tegucigalpa /pytz_data/zoneinfo/America/Tegucigalpa
    pytz/zoneinfo/America/Thule /pytz_data/zoneinfo/America/Thule
    pytz/zoneinfo/America/Thunder_Bay /pytz_data/zoneinfo/America/Thunder_Bay
    pytz/zoneinfo/America/Tijuana /pytz_data/zoneinfo/America/Tijuana
    pytz/zoneinfo/America/Toronto /pytz_data/zoneinfo/America/Toronto
    pytz/zoneinfo/America/Tortola /pytz_data/zoneinfo/America/Tortola
    pytz/zoneinfo/America/Vancouver /pytz_data/zoneinfo/America/Vancouver
    pytz/zoneinfo/America/Virgin /pytz_data/zoneinfo/America/Virgin
    pytz/zoneinfo/America/Whitehorse /pytz_data/zoneinfo/America/Whitehorse
    pytz/zoneinfo/America/Winnipeg /pytz_data/zoneinfo/America/Winnipeg
    pytz/zoneinfo/America/Yakutat /pytz_data/zoneinfo/America/Yakutat
    pytz/zoneinfo/America/Yellowknife /pytz_data/zoneinfo/America/Yellowknife
    pytz/zoneinfo/Antarctica/Casey /pytz_data/zoneinfo/Antarctica/Casey
    pytz/zoneinfo/Antarctica/Davis /pytz_data/zoneinfo/Antarctica/Davis
    pytz/zoneinfo/Antarctica/DumontDUrville /pytz_data/zoneinfo/Antarctica/DumontDUrville
    pytz/zoneinfo/Antarctica/Macquarie /pytz_data/zoneinfo/Antarctica/Macquarie
    pytz/zoneinfo/Antarctica/Mawson /pytz_data/zoneinfo/Antarctica/Mawson
    pytz/zoneinfo/Antarctica/McMurdo /pytz_data/zoneinfo/Antarctica/McMurdo
    pytz/zoneinfo/Antarctica/Palmer /pytz_data/zoneinfo/Antarctica/Palmer
    pytz/zoneinfo/Antarctica/Rothera /pytz_data/zoneinfo/Antarctica/Rothera
    pytz/zoneinfo/Antarctica/South_Pole /pytz_data/zoneinfo/Antarctica/South_Pole
    pytz/zoneinfo/Antarctica/Syowa /pytz_data/zoneinfo/Antarctica/Syowa
    pytz/zoneinfo/Antarctica/Troll /pytz_data/zoneinfo/Antarctica/Troll
    pytz/zoneinfo/Antarctica/Vostok /pytz_data/zoneinfo/Antarctica/Vostok
    pytz/zoneinfo/Arctic/Longyearbyen /pytz_data/zoneinfo/Arctic/Longyearbyen
    pytz/zoneinfo/Asia/Aden /pytz_data/zoneinfo/Asia/Aden
    pytz/zoneinfo/Asia/Almaty /pytz_data/zoneinfo/Asia/Almaty
    pytz/zoneinfo/Asia/Amman /pytz_data/zoneinfo/Asia/Amman
    pytz/zoneinfo/Asia/Anadyr /pytz_data/zoneinfo/Asia/Anadyr
    pytz/zoneinfo/Asia/Aqtau /pytz_data/zoneinfo/Asia/Aqtau
    pytz/zoneinfo/Asia/Aqtobe /pytz_data/zoneinfo/Asia/Aqtobe
    pytz/zoneinfo/Asia/Ashgabat /pytz_data/zoneinfo/Asia/Ashgabat
    pytz/zoneinfo/Asia/Ashkhabad /pytz_data/zoneinfo/Asia/Ashkhabad
    pytz/zoneinfo/Asia/Atyrau /pytz_data/zoneinfo/Asia/Atyrau
    pytz/zoneinfo/Asia/Baghdad /pytz_data/zoneinfo/Asia/Baghdad
    pytz/zoneinfo/Asia/Bahrain /pytz_data/zoneinfo/Asia/Bahrain
    pytz/zoneinfo/Asia/Baku /pytz_data/zoneinfo/Asia/Baku
    pytz/zoneinfo/Asia/Bangkok /pytz_data/zoneinfo/Asia/Bangkok
    pytz/zoneinfo/Asia/Barnaul /pytz_data/zoneinfo/Asia/Barnaul
    pytz/zoneinfo/Asia/Beirut /pytz_data/zoneinfo/Asia/Beirut
    pytz/zoneinfo/Asia/Bishkek /pytz_data/zoneinfo/Asia/Bishkek
    pytz/zoneinfo/Asia/Brunei /pytz_data/zoneinfo/Asia/Brunei
    pytz/zoneinfo/Asia/Calcutta /pytz_data/zoneinfo/Asia/Calcutta
    pytz/zoneinfo/Asia/Chita /pytz_data/zoneinfo/Asia/Chita
    pytz/zoneinfo/Asia/Choibalsan /pytz_data/zoneinfo/Asia/Choibalsan
    pytz/zoneinfo/Asia/Chongqing /pytz_data/zoneinfo/Asia/Chongqing
    pytz/zoneinfo/Asia/Chungking /pytz_data/zoneinfo/Asia/Chungking
    pytz/zoneinfo/Asia/Colombo /pytz_data/zoneinfo/Asia/Colombo
    pytz/zoneinfo/Asia/Dacca /pytz_data/zoneinfo/Asia/Dacca
    pytz/zoneinfo/Asia/Damascus /pytz_data/zoneinfo/Asia/Damascus
    pytz/zoneinfo/Asia/Dhaka /pytz_data/zoneinfo/Asia/Dhaka
    pytz/zoneinfo/Asia/Dili /pytz_data/zoneinfo/Asia/Dili
    pytz/zoneinfo/Asia/Dubai /pytz_data/zoneinfo/Asia/Dubai
    pytz/zoneinfo/Asia/Dushanbe /pytz_data/zoneinfo/Asia/Dushanbe
    pytz/zoneinfo/Asia/Famagusta /pytz_data/zoneinfo/Asia/Famagusta
    pytz/zoneinfo/Asia/Gaza /pytz_data/zoneinfo/Asia/Gaza
    pytz/zoneinfo/Asia/Harbin /pytz_data/zoneinfo/Asia/Harbin
    pytz/zoneinfo/Asia/Hebron /pytz_data/zoneinfo/Asia/Hebron
    pytz/zoneinfo/Asia/Ho_Chi_Minh /pytz_data/zoneinfo/Asia/Ho_Chi_Minh
    pytz/zoneinfo/Asia/Hong_Kong /pytz_data/zoneinfo/Asia/Hong_Kong
    pytz/zoneinfo/Asia/Hovd /pytz_data/zoneinfo/Asia/Hovd
    pytz/zoneinfo/Asia/Irkutsk /pytz_data/zoneinfo/Asia/Irkutsk
    pytz/zoneinfo/Asia/Istanbul /pytz_data/zoneinfo/Asia/Istanbul
    pytz/zoneinfo/Asia/Jakarta /pytz_data/zoneinfo/Asia/Jakarta
    pytz/zoneinfo/Asia/Jayapura /pytz_data/zoneinfo/Asia/Jayapura
    pytz/zoneinfo/Asia/Jerusalem /pytz_data/zoneinfo/Asia/Jerusalem
    pytz/zoneinfo/Asia/Kabul /pytz_data/zoneinfo/Asia/Kabul
    pytz/zoneinfo/Asia/Kamchatka /pytz_data/zoneinfo/Asia/Kamchatka
    pytz/zoneinfo/Asia/Karachi /pytz_data/zoneinfo/Asia/Karachi
    pytz/zoneinfo/Asia/Kashgar /pytz_data/zoneinfo/Asia/Kashgar
    pytz/zoneinfo/Asia/Kathmandu /pytz_data/zoneinfo/Asia/Kathmandu
    pytz/zoneinfo/Asia/Katmandu /pytz_data/zoneinfo/Asia/Katmandu
    pytz/zoneinfo/Asia/Khandyga /pytz_data/zoneinfo/Asia/Khandyga
    pytz/zoneinfo/Asia/Kolkata /pytz_data/zoneinfo/Asia/Kolkata
    pytz/zoneinfo/Asia/Krasnoyarsk /pytz_data/zoneinfo/Asia/Krasnoyarsk
    pytz/zoneinfo/Asia/Kuala_Lumpur /pytz_data/zoneinfo/Asia/Kuala_Lumpur
    pytz/zoneinfo/Asia/Kuching /pytz_data/zoneinfo/Asia/Kuching
    pytz/zoneinfo/Asia/Kuwait /pytz_data/zoneinfo/Asia/Kuwait
    pytz/zoneinfo/Asia/Macao /pytz_data/zoneinfo/Asia/Macao
    pytz/zoneinfo/Asia/Macau /pytz_data/zoneinfo/Asia/Macau
    pytz/zoneinfo/Asia/Magadan /pytz_data/zoneinfo/Asia/Magadan
    pytz/zoneinfo/Asia/Makassar /pytz_data/zoneinfo/Asia/Makassar
    pytz/zoneinfo/Asia/Manila /pytz_data/zoneinfo/Asia/Manila
    pytz/zoneinfo/Asia/Muscat /pytz_data/zoneinfo/Asia/Muscat
    pytz/zoneinfo/Asia/Nicosia /pytz_data/zoneinfo/Asia/Nicosia
    pytz/zoneinfo/Asia/Novokuznetsk /pytz_data/zoneinfo/Asia/Novokuznetsk
    pytz/zoneinfo/Asia/Novosibirsk /pytz_data/zoneinfo/Asia/Novosibirsk
    pytz/zoneinfo/Asia/Omsk /pytz_data/zoneinfo/Asia/Omsk
    pytz/zoneinfo/Asia/Oral /pytz_data/zoneinfo/Asia/Oral
    pytz/zoneinfo/Asia/Phnom_Penh /pytz_data/zoneinfo/Asia/Phnom_Penh
    pytz/zoneinfo/Asia/Pontianak /pytz_data/zoneinfo/Asia/Pontianak
    pytz/zoneinfo/Asia/Pyongyang /pytz_data/zoneinfo/Asia/Pyongyang
    pytz/zoneinfo/Asia/Qatar /pytz_data/zoneinfo/Asia/Qatar
    pytz/zoneinfo/Asia/Qostanay /pytz_data/zoneinfo/Asia/Qostanay
    pytz/zoneinfo/Asia/Qyzylorda /pytz_data/zoneinfo/Asia/Qyzylorda
    pytz/zoneinfo/Asia/Rangoon /pytz_data/zoneinfo/Asia/Rangoon
    pytz/zoneinfo/Asia/Riyadh /pytz_data/zoneinfo/Asia/Riyadh
    pytz/zoneinfo/Asia/Saigon /pytz_data/zoneinfo/Asia/Saigon
    pytz/zoneinfo/Asia/Sakhalin /pytz_data/zoneinfo/Asia/Sakhalin
    pytz/zoneinfo/Asia/Samarkand /pytz_data/zoneinfo/Asia/Samarkand
    pytz/zoneinfo/Asia/Seoul /pytz_data/zoneinfo/Asia/Seoul
    pytz/zoneinfo/Asia/Shanghai /pytz_data/zoneinfo/Asia/Shanghai
    pytz/zoneinfo/Asia/Singapore /pytz_data/zoneinfo/Asia/Singapore
    pytz/zoneinfo/Asia/Srednekolymsk /pytz_data/zoneinfo/Asia/Srednekolymsk
    pytz/zoneinfo/Asia/Taipei /pytz_data/zoneinfo/Asia/Taipei
    pytz/zoneinfo/Asia/Tashkent /pytz_data/zoneinfo/Asia/Tashkent
    pytz/zoneinfo/Asia/Tbilisi /pytz_data/zoneinfo/Asia/Tbilisi
    pytz/zoneinfo/Asia/Tehran /pytz_data/zoneinfo/Asia/Tehran
    pytz/zoneinfo/Asia/Tel_Aviv /pytz_data/zoneinfo/Asia/Tel_Aviv
    pytz/zoneinfo/Asia/Thimbu /pytz_data/zoneinfo/Asia/Thimbu
    pytz/zoneinfo/Asia/Thimphu /pytz_data/zoneinfo/Asia/Thimphu
    pytz/zoneinfo/Asia/Tokyo /pytz_data/zoneinfo/Asia/Tokyo
    pytz/zoneinfo/Asia/Tomsk /pytz_data/zoneinfo/Asia/Tomsk
    pytz/zoneinfo/Asia/Ujung_Pandang /pytz_data/zoneinfo/Asia/Ujung_Pandang
    pytz/zoneinfo/Asia/Ulaanbaatar /pytz_data/zoneinfo/Asia/Ulaanbaatar
    pytz/zoneinfo/Asia/Ulan_Bator /pytz_data/zoneinfo/Asia/Ulan_Bator
    pytz/zoneinfo/Asia/Urumqi /pytz_data/zoneinfo/Asia/Urumqi
    pytz/zoneinfo/Asia/Ust-Nera /pytz_data/zoneinfo/Asia/Ust-Nera
    pytz/zoneinfo/Asia/Vientiane /pytz_data/zoneinfo/Asia/Vientiane
    pytz/zoneinfo/Asia/Vladivostok /pytz_data/zoneinfo/Asia/Vladivostok
    pytz/zoneinfo/Asia/Yakutsk /pytz_data/zoneinfo/Asia/Yakutsk
    pytz/zoneinfo/Asia/Yangon /pytz_data/zoneinfo/Asia/Yangon
    pytz/zoneinfo/Asia/Yekaterinburg /pytz_data/zoneinfo/Asia/Yekaterinburg
    pytz/zoneinfo/Asia/Yerevan /pytz_data/zoneinfo/Asia/Yerevan
    pytz/zoneinfo/Atlantic/Azores /pytz_data/zoneinfo/Atlantic/Azores
    pytz/zoneinfo/Atlantic/Bermuda /pytz_data/zoneinfo/Atlantic/Bermuda
    pytz/zoneinfo/Atlantic/Canary /pytz_data/zoneinfo/Atlantic/Canary
    pytz/zoneinfo/Atlantic/Cape_Verde /pytz_data/zoneinfo/Atlantic/Cape_Verde
    pytz/zoneinfo/Atlantic/Faeroe /pytz_data/zoneinfo/Atlantic/Faeroe
    pytz/zoneinfo/Atlantic/Faroe /pytz_data/zoneinfo/Atlantic/Faroe
    pytz/zoneinfo/Atlantic/Jan_Mayen /pytz_data/zoneinfo/Atlantic/Jan_Mayen
    pytz/zoneinfo/Atlantic/Madeira /pytz_data/zoneinfo/Atlantic/Madeira
    pytz/zoneinfo/Atlantic/Reykjavik /pytz_data/zoneinfo/Atlantic/Reykjavik
    pytz/zoneinfo/Atlantic/South_Georgia /pytz_data/zoneinfo/Atlantic/South_Georgia
    pytz/zoneinfo/Atlantic/St_Helena /pytz_data/zoneinfo/Atlantic/St_Helena
    pytz/zoneinfo/Atlantic/Stanley /pytz_data/zoneinfo/Atlantic/Stanley
    pytz/zoneinfo/Australia/ACT /pytz_data/zoneinfo/Australia/ACT
    pytz/zoneinfo/Australia/Adelaide /pytz_data/zoneinfo/Australia/Adelaide
    pytz/zoneinfo/Australia/Brisbane /pytz_data/zoneinfo/Australia/Brisbane
    pytz/zoneinfo/Australia/Broken_Hill /pytz_data/zoneinfo/Australia/Broken_Hill
    pytz/zoneinfo/Australia/Canberra /pytz_data/zoneinfo/Australia/Canberra
    pytz/zoneinfo/Australia/Currie /pytz_data/zoneinfo/Australia/Currie
    pytz/zoneinfo/Australia/Darwin /pytz_data/zoneinfo/Australia/Darwin
    pytz/zoneinfo/Australia/Eucla /pytz_data/zoneinfo/Australia/Eucla
    pytz/zoneinfo/Australia/Hobart /pytz_data/zoneinfo/Australia/Hobart
    pytz/zoneinfo/Australia/LHI /pytz_data/zoneinfo/Australia/LHI
    pytz/zoneinfo/Australia/Lindeman /pytz_data/zoneinfo/Australia/Lindeman
    pytz/zoneinfo/Australia/Lord_Howe /pytz_data/zoneinfo/Australia/Lord_Howe
    pytz/zoneinfo/Australia/Melbourne /pytz_data/zoneinfo/Australia/Melbourne
    pytz/zoneinfo/Australia/NSW /pytz_data/zoneinfo/Australia/NSW
    pytz/zoneinfo/Australia/North /pytz_data/zoneinfo/Australia/North
    pytz/zoneinfo/Australia/Perth /pytz_data/zoneinfo/Australia/Perth
    pytz/zoneinfo/Australia/Queensland /pytz_data/zoneinfo/Australia/Queensland
    pytz/zoneinfo/Australia/South /pytz_data/zoneinfo/Australia/South
    pytz/zoneinfo/Australia/Sydney /pytz_data/zoneinfo/Australia/Sydney
    pytz/zoneinfo/Australia/Tasmania /pytz_data/zoneinfo/Australia/Tasmania
    pytz/zoneinfo/Australia/Victoria /pytz_data/zoneinfo/Australia/Victoria
    pytz/zoneinfo/Australia/West /pytz_data/zoneinfo/Australia/West
    pytz/zoneinfo/Australia/Yancowinna /pytz_data/zoneinfo/Australia/Yancowinna
    pytz/zoneinfo/Brazil/Acre /pytz_data/zoneinfo/Brazil/Acre
    pytz/zoneinfo/Brazil/DeNoronha /pytz_data/zoneinfo/Brazil/DeNoronha
    pytz/zoneinfo/Brazil/East /pytz_data/zoneinfo/Brazil/East
    pytz/zoneinfo/Brazil/West /pytz_data/zoneinfo/Brazil/West
    pytz/zoneinfo/CET /pytz_data/zoneinfo/CET
    pytz/zoneinfo/CST6CDT /pytz_data/zoneinfo/CST6CDT
    pytz/zoneinfo/Canada/Atlantic /pytz_data/zoneinfo/Canada/Atlantic
    pytz/zoneinfo/Canada/Central /pytz_data/zoneinfo/Canada/Central
    pytz/zoneinfo/Canada/East-Saskatchewan /pytz_data/zoneinfo/Canada/East-Saskatchewan
    pytz/zoneinfo/Canada/Eastern /pytz_data/zoneinfo/Canada/Eastern
    pytz/zoneinfo/Canada/Mountain /pytz_data/zoneinfo/Canada/Mountain
    pytz/zoneinfo/Canada/Newfoundland /pytz_data/zoneinfo/Canada/Newfoundland
    pytz/zoneinfo/Canada/Pacific /pytz_data/zoneinfo/Canada/Pacific
    pytz/zoneinfo/Canada/Saskatchewan /pytz_data/zoneinfo/Canada/Saskatchewan
    pytz/zoneinfo/Canada/Yukon /pytz_data/zoneinfo/Canada/Yukon
    pytz/zoneinfo/Chile/Continental /pytz_data/zoneinfo/Chile/Continental
    pytz/zoneinfo/Chile/EasterIsland /pytz_data/zoneinfo/Chile/EasterIsland
    pytz/zoneinfo/Cuba /pytz_data/zoneinfo/Cuba
    pytz/zoneinfo/EET /pytz_data/zoneinfo/EET
    pytz/zoneinfo/EST /pytz_data/zoneinfo/EST
    pytz/zoneinfo/EST5EDT /pytz_data/zoneinfo/EST5EDT
    pytz/zoneinfo/Egypt /pytz_data/zoneinfo/Egypt
    pytz/zoneinfo/Eire /pytz_data/zoneinfo/Eire
    pytz/zoneinfo/Etc/GMT /pytz_data/zoneinfo/Etc/GMT
    pytz/zoneinfo/Etc/GMT+0 /pytz_data/zoneinfo/Etc/GMT+0
    pytz/zoneinfo/Etc/GMT+1 /pytz_data/zoneinfo/Etc/GMT+1
    pytz/zoneinfo/Etc/GMT+10 /pytz_data/zoneinfo/Etc/GMT+10
    pytz/zoneinfo/Etc/GMT+11 /pytz_data/zoneinfo/Etc/GMT+11
    pytz/zoneinfo/Etc/GMT+12 /pytz_data/zoneinfo/Etc/GMT+12
    pytz/zoneinfo/Etc/GMT+2 /pytz_data/zoneinfo/Etc/GMT+2
    pytz/zoneinfo/Etc/GMT+3 /pytz_data/zoneinfo/Etc/GMT+3
    pytz/zoneinfo/Etc/GMT+4 /pytz_data/zoneinfo/Etc/GMT+4
    pytz/zoneinfo/Etc/GMT+5 /pytz_data/zoneinfo/Etc/GMT+5
    pytz/zoneinfo/Etc/GMT+6 /pytz_data/zoneinfo/Etc/GMT+6
    pytz/zoneinfo/Etc/GMT+7 /pytz_data/zoneinfo/Etc/GMT+7
    pytz/zoneinfo/Etc/GMT+8 /pytz_data/zoneinfo/Etc/GMT+8
    pytz/zoneinfo/Etc/GMT+9 /pytz_data/zoneinfo/Etc/GMT+9
    pytz/zoneinfo/Etc/GMT-0 /pytz_data/zoneinfo/Etc/GMT-0
    pytz/zoneinfo/Etc/GMT-1 /pytz_data/zoneinfo/Etc/GMT-1
    pytz/zoneinfo/Etc/GMT-10 /pytz_data/zoneinfo/Etc/GMT-10
    pytz/zoneinfo/Etc/GMT-11 /pytz_data/zoneinfo/Etc/GMT-11
    pytz/zoneinfo/Etc/GMT-12 /pytz_data/zoneinfo/Etc/GMT-12
    pytz/zoneinfo/Etc/GMT-13 /pytz_data/zoneinfo/Etc/GMT-13
    pytz/zoneinfo/Etc/GMT-14 /pytz_data/zoneinfo/Etc/GMT-14
    pytz/zoneinfo/Etc/GMT-2 /pytz_data/zoneinfo/Etc/GMT-2
    pytz/zoneinfo/Etc/GMT-3 /pytz_data/zoneinfo/Etc/GMT-3
    pytz/zoneinfo/Etc/GMT-4 /pytz_data/zoneinfo/Etc/GMT-4
    pytz/zoneinfo/Etc/GMT-5 /pytz_data/zoneinfo/Etc/GMT-5
    pytz/zoneinfo/Etc/GMT-6 /pytz_data/zoneinfo/Etc/GMT-6
    pytz/zoneinfo/Etc/GMT-7 /pytz_data/zoneinfo/Etc/GMT-7
    pytz/zoneinfo/Etc/GMT-8 /pytz_data/zoneinfo/Etc/GMT-8
    pytz/zoneinfo/Etc/GMT-9 /pytz_data/zoneinfo/Etc/GMT-9
    pytz/zoneinfo/Etc/GMT0 /pytz_data/zoneinfo/Etc/GMT0
    pytz/zoneinfo/Etc/Greenwich /pytz_data/zoneinfo/Etc/Greenwich
    pytz/zoneinfo/Etc/UCT /pytz_data/zoneinfo/Etc/UCT
    pytz/zoneinfo/Etc/UTC /pytz_data/zoneinfo/Etc/UTC
    pytz/zoneinfo/Etc/Universal /pytz_data/zoneinfo/Etc/Universal
    pytz/zoneinfo/Etc/Zulu /pytz_data/zoneinfo/Etc/Zulu
    pytz/zoneinfo/Europe/Amsterdam /pytz_data/zoneinfo/Europe/Amsterdam
    pytz/zoneinfo/Europe/Andorra /pytz_data/zoneinfo/Europe/Andorra
    pytz/zoneinfo/Europe/Astrakhan /pytz_data/zoneinfo/Europe/Astrakhan
    pytz/zoneinfo/Europe/Athens /pytz_data/zoneinfo/Europe/Athens
    pytz/zoneinfo/Europe/Belfast /pytz_data/zoneinfo/Europe/Belfast
    pytz/zoneinfo/Europe/Belgrade /pytz_data/zoneinfo/Europe/Belgrade
    pytz/zoneinfo/Europe/Berlin /pytz_data/zoneinfo/Europe/Berlin
    pytz/zoneinfo/Europe/Bratislava /pytz_data/zoneinfo/Europe/Bratislava
    pytz/zoneinfo/Europe/Brussels /pytz_data/zoneinfo/Europe/Brussels
    pytz/zoneinfo/Europe/Bucharest /pytz_data/zoneinfo/Europe/Bucharest
    pytz/zoneinfo/Europe/Budapest /pytz_data/zoneinfo/Europe/Budapest
    pytz/zoneinfo/Europe/Busingen /pytz_data/zoneinfo/Europe/Busingen
    pytz/zoneinfo/Europe/Chisinau /pytz_data/zoneinfo/Europe/Chisinau
    pytz/zoneinfo/Europe/Copenhagen /pytz_data/zoneinfo/Europe/Copenhagen
    pytz/zoneinfo/Europe/Dublin /pytz_data/zoneinfo/Europe/Dublin
    pytz/zoneinfo/Europe/Gibraltar /pytz_data/zoneinfo/Europe/Gibraltar
    pytz/zoneinfo/Europe/Guernsey /pytz_data/zoneinfo/Europe/Guernsey
    pytz/zoneinfo/Europe/Helsinki /pytz_data/zoneinfo/Europe/Helsinki
    pytz/zoneinfo/Europe/Isle_of_Man /pytz_data/zoneinfo/Europe/Isle_of_Man
    pytz/zoneinfo/Europe/Istanbul /pytz_data/zoneinfo/Europe/Istanbul
    pytz/zoneinfo/Europe/Jersey /pytz_data/zoneinfo/Europe/Jersey
    pytz/zoneinfo/Europe/Kaliningrad /pytz_data/zoneinfo/Europe/Kaliningrad
    pytz/zoneinfo/Europe/Kiev /pytz_data/zoneinfo/Europe/Kiev
    pytz/zoneinfo/Europe/Kirov /pytz_data/zoneinfo/Europe/Kirov
    pytz/zoneinfo/Europe/Lisbon /pytz_data/zoneinfo/Europe/Lisbon
    pytz/zoneinfo/Europe/Ljubljana /pytz_data/zoneinfo/Europe/Ljubljana
    pytz/zoneinfo/Europe/London /pytz_data/zoneinfo/Europe/London
    pytz/zoneinfo/Europe/Luxembourg /pytz_data/zoneinfo/Europe/Luxembourg
    pytz/zoneinfo/Europe/Madrid /pytz_data/zoneinfo/Europe/Madrid
    pytz/zoneinfo/Europe/Malta /pytz_data/zoneinfo/Europe/Malta
    pytz/zoneinfo/Europe/Mariehamn /pytz_data/zoneinfo/Europe/Mariehamn
    pytz/zoneinfo/Europe/Minsk /pytz_data/zoneinfo/Europe/Minsk
    pytz/zoneinfo/Europe/Monaco /pytz_data/zoneinfo/Europe/Monaco
    pytz/zoneinfo/Europe/Moscow /pytz_data/zoneinfo/Europe/Moscow
    pytz/zoneinfo/Europe/Nicosia /pytz_data/zoneinfo/Europe/Nicosia
    pytz/zoneinfo/Europe/Oslo /pytz_data/zoneinfo/Europe/Oslo
    pytz/zoneinfo/Europe/Paris /pytz_data/zoneinfo/Europe/Paris
    pytz/zoneinfo/Europe/Podgorica /pytz_data/zoneinfo/Europe/Podgorica
    pytz/zoneinfo/Europe/Prague /pytz_data/zoneinfo/Europe/Prague
    pytz/zoneinfo/Europe/Riga /pytz_data/zoneinfo/Europe/Riga
    pytz/zoneinfo/Europe/Rome /pytz_data/zoneinfo/Europe/Rome
    pytz/zoneinfo/Europe/Samara /pytz_data/zoneinfo/Europe/Samara
    pytz/zoneinfo/Europe/San_Marino /pytz_data/zoneinfo/Europe/San_Marino
    pytz/zoneinfo/Europe/Sarajevo /pytz_data/zoneinfo/Europe/Sarajevo
    pytz/zoneinfo/Europe/Saratov /pytz_data/zoneinfo/Europe/Saratov
    pytz/zoneinfo/Europe/Simferopol /pytz_data/zoneinfo/Europe/Simferopol
    pytz/zoneinfo/Europe/Skopje /pytz_data/zoneinfo/Europe/Skopje
    pytz/zoneinfo/Europe/Sofia /pytz_data/zoneinfo/Europe/Sofia
    pytz/zoneinfo/Europe/Stockholm /pytz_data/zoneinfo/Europe/Stockholm
    pytz/zoneinfo/Europe/Tallinn /pytz_data/zoneinfo/Europe/Tallinn
    pytz/zoneinfo/Europe/Tirane /pytz_data/zoneinfo/Europe/Tirane
    pytz/zoneinfo/Europe/Tiraspol /pytz_data/zoneinfo/Europe/Tiraspol
    pytz/zoneinfo/Europe/Ulyanovsk /pytz_data/zoneinfo/Europe/Ulyanovsk
    pytz/zoneinfo/Europe/Uzhgorod /pytz_data/zoneinfo/Europe/Uzhgorod
    pytz/zoneinfo/Europe/Vaduz /pytz_data/zoneinfo/Europe/Vaduz
    pytz/zoneinfo/Europe/Vatican /pytz_data/zoneinfo/Europe/Vatican
    pytz/zoneinfo/Europe/Vienna /pytz_data/zoneinfo/Europe/Vienna
    pytz/zoneinfo/Europe/Vilnius /pytz_data/zoneinfo/Europe/Vilnius
    pytz/zoneinfo/Europe/Volgograd /pytz_data/zoneinfo/Europe/Volgograd
    pytz/zoneinfo/Europe/Warsaw /pytz_data/zoneinfo/Europe/Warsaw
    pytz/zoneinfo/Europe/Zagreb /pytz_data/zoneinfo/Europe/Zagreb
    pytz/zoneinfo/Europe/Zaporozhye /pytz_data/zoneinfo/Europe/Zaporozhye
    pytz/zoneinfo/Europe/Zurich /pytz_data/zoneinfo/Europe/Zurich
    pytz/zoneinfo/Factory /pytz_data/zoneinfo/Factory
    pytz/zoneinfo/GB /pytz_data/zoneinfo/GB
    pytz/zoneinfo/GB-Eire /pytz_data/zoneinfo/GB-Eire
    pytz/zoneinfo/GMT /pytz_data/zoneinfo/GMT
    pytz/zoneinfo/GMT+0 /pytz_data/zoneinfo/GMT+0
    pytz/zoneinfo/GMT-0 /pytz_data/zoneinfo/GMT-0
    pytz/zoneinfo/GMT0 /pytz_data/zoneinfo/GMT0
    pytz/zoneinfo/Greenwich /pytz_data/zoneinfo/Greenwich
    pytz/zoneinfo/HST /pytz_data/zoneinfo/HST
    pytz/zoneinfo/Hongkong /pytz_data/zoneinfo/Hongkong
    pytz/zoneinfo/Iceland /pytz_data/zoneinfo/Iceland
    pytz/zoneinfo/Indian/Antananarivo /pytz_data/zoneinfo/Indian/Antananarivo
    pytz/zoneinfo/Indian/Chagos /pytz_data/zoneinfo/Indian/Chagos
    pytz/zoneinfo/Indian/Christmas /pytz_data/zoneinfo/Indian/Christmas
    pytz/zoneinfo/Indian/Cocos /pytz_data/zoneinfo/Indian/Cocos
    pytz/zoneinfo/Indian/Comoro /pytz_data/zoneinfo/Indian/Comoro
    pytz/zoneinfo/Indian/Kerguelen /pytz_data/zoneinfo/Indian/Kerguelen
    pytz/zoneinfo/Indian/Mahe /pytz_data/zoneinfo/Indian/Mahe
    pytz/zoneinfo/Indian/Maldives /pytz_data/zoneinfo/Indian/Maldives
    pytz/zoneinfo/Indian/Mauritius /pytz_data/zoneinfo/Indian/Mauritius
    pytz/zoneinfo/Indian/Mayotte /pytz_data/zoneinfo/Indian/Mayotte
    pytz/zoneinfo/Indian/Reunion /pytz_data/zoneinfo/Indian/Reunion
    pytz/zoneinfo/Iran /pytz_data/zoneinfo/Iran
    pytz/zoneinfo/Israel /pytz_data/zoneinfo/Israel
    pytz/zoneinfo/Jamaica /pytz_data/zoneinfo/Jamaica
    pytz/zoneinfo/Japan /pytz_data/zoneinfo/Japan
    pytz/zoneinfo/Kwajalein /pytz_data/zoneinfo/Kwajalein
    pytz/zoneinfo/Libya /pytz_data/zoneinfo/Libya
    pytz/zoneinfo/MET /pytz_data/zoneinfo/MET
    pytz/zoneinfo/MST /pytz_data/zoneinfo/MST
    pytz/zoneinfo/MST7MDT /pytz_data/zoneinfo/MST7MDT
    pytz/zoneinfo/Mexico/BajaNorte /pytz_data/zoneinfo/Mexico/BajaNorte
    pytz/zoneinfo/Mexico/BajaSur /pytz_data/zoneinfo/Mexico/BajaSur
    pytz/zoneinfo/Mexico/General /pytz_data/zoneinfo/Mexico/General
    pytz/zoneinfo/NZ /pytz_data/zoneinfo/NZ
    pytz/zoneinfo/NZ-CHAT /pytz_data/zoneinfo/NZ-CHAT
    pytz/zoneinfo/Navajo /pytz_data/zoneinfo/Navajo
    pytz/zoneinfo/PRC /pytz_data/zoneinfo/PRC
    pytz/zoneinfo/PST8PDT /pytz_data/zoneinfo/PST8PDT
    pytz/zoneinfo/Pacific/Apia /pytz_data/zoneinfo/Pacific/Apia
    pytz/zoneinfo/Pacific/Auckland /pytz_data/zoneinfo/Pacific/Auckland
    pytz/zoneinfo/Pacific/Bougainville /pytz_data/zoneinfo/Pacific/Bougainville
    pytz/zoneinfo/Pacific/Chatham /pytz_data/zoneinfo/Pacific/Chatham
    pytz/zoneinfo/Pacific/Chuuk /pytz_data/zoneinfo/Pacific/Chuuk
    pytz/zoneinfo/Pacific/Easter /pytz_data/zoneinfo/Pacific/Easter
    pytz/zoneinfo/Pacific/Efate /pytz_data/zoneinfo/Pacific/Efate
    pytz/zoneinfo/Pacific/Enderbury /pytz_data/zoneinfo/Pacific/Enderbury
    pytz/zoneinfo/Pacific/Fakaofo /pytz_data/zoneinfo/Pacific/Fakaofo
    pytz/zoneinfo/Pacific/Fiji /pytz_data/zoneinfo/Pacific/Fiji
    pytz/zoneinfo/Pacific/Funafuti /pytz_data/zoneinfo/Pacific/Funafuti
    pytz/zoneinfo/Pacific/Galapagos /pytz_data/zoneinfo/Pacific/Galapagos
    pytz/zoneinfo/Pacific/Gambier /pytz_data/zoneinfo/Pacific/Gambier
    pytz/zoneinfo/Pacific/Guadalcanal /pytz_data/zoneinfo/Pacific/Guadalcanal
    pytz/zoneinfo/Pacific/Guam /pytz_data/zoneinfo/Pacific/Guam
    pytz/zoneinfo/Pacific/Honolulu /pytz_data/zoneinfo/Pacific/Honolulu
    pytz/zoneinfo/Pacific/Johnston /pytz_data/zoneinfo/Pacific/Johnston
    pytz/zoneinfo/Pacific/Kiritimati /pytz_data/zoneinfo/Pacific/Kiritimati
    pytz/zoneinfo/Pacific/Kosrae /pytz_data/zoneinfo/Pacific/Kosrae
    pytz/zoneinfo/Pacific/Kwajalein /pytz_data/zoneinfo/Pacific/Kwajalein
    pytz/zoneinfo/Pacific/Majuro /pytz_data/zoneinfo/Pacific/Majuro
    pytz/zoneinfo/Pacific/Marquesas /pytz_data/zoneinfo/Pacific/Marquesas
    pytz/zoneinfo/Pacific/Midway /pytz_data/zoneinfo/Pacific/Midway
    pytz/zoneinfo/Pacific/Nauru /pytz_data/zoneinfo/Pacific/Nauru
    pytz/zoneinfo/Pacific/Niue /pytz_data/zoneinfo/Pacific/Niue
    pytz/zoneinfo/Pacific/Norfolk /pytz_data/zoneinfo/Pacific/Norfolk
    pytz/zoneinfo/Pacific/Noumea /pytz_data/zoneinfo/Pacific/Noumea
    pytz/zoneinfo/Pacific/Pago_Pago /pytz_data/zoneinfo/Pacific/Pago_Pago
    pytz/zoneinfo/Pacific/Palau /pytz_data/zoneinfo/Pacific/Palau
    pytz/zoneinfo/Pacific/Pitcairn /pytz_data/zoneinfo/Pacific/Pitcairn
    pytz/zoneinfo/Pacific/Pohnpei /pytz_data/zoneinfo/Pacific/Pohnpei
    pytz/zoneinfo/Pacific/Ponape /pytz_data/zoneinfo/Pacific/Ponape
    pytz/zoneinfo/Pacific/Port_Moresby /pytz_data/zoneinfo/Pacific/Port_Moresby
    pytz/zoneinfo/Pacific/Rarotonga /pytz_data/zoneinfo/Pacific/Rarotonga
    pytz/zoneinfo/Pacific/Saipan /pytz_data/zoneinfo/Pacific/Saipan
    pytz/zoneinfo/Pacific/Samoa /pytz_data/zoneinfo/Pacific/Samoa
    pytz/zoneinfo/Pacific/Tahiti /pytz_data/zoneinfo/Pacific/Tahiti
    pytz/zoneinfo/Pacific/Tarawa /pytz_data/zoneinfo/Pacific/Tarawa
    pytz/zoneinfo/Pacific/Tongatapu /pytz_data/zoneinfo/Pacific/Tongatapu
    pytz/zoneinfo/Pacific/Truk /pytz_data/zoneinfo/Pacific/Truk
    pytz/zoneinfo/Pacific/Wake /pytz_data/zoneinfo/Pacific/Wake
    pytz/zoneinfo/Pacific/Wallis /pytz_data/zoneinfo/Pacific/Wallis
    pytz/zoneinfo/Pacific/Yap /pytz_data/zoneinfo/Pacific/Yap
    pytz/zoneinfo/Poland /pytz_data/zoneinfo/Poland
    pytz/zoneinfo/Portugal /pytz_data/zoneinfo/Portugal
    pytz/zoneinfo/ROC /pytz_data/zoneinfo/ROC
    pytz/zoneinfo/ROK /pytz_data/zoneinfo/ROK
    pytz/zoneinfo/Singapore /pytz_data/zoneinfo/Singapore
    pytz/zoneinfo/Turkey /pytz_data/zoneinfo/Turkey
    pytz/zoneinfo/UCT /pytz_data/zoneinfo/UCT
    pytz/zoneinfo/US/Alaska /pytz_data/zoneinfo/US/Alaska
    pytz/zoneinfo/US/Aleutian /pytz_data/zoneinfo/US/Aleutian
    pytz/zoneinfo/US/Arizona /pytz_data/zoneinfo/US/Arizona
    pytz/zoneinfo/US/Central /pytz_data/zoneinfo/US/Central
    pytz/zoneinfo/US/East-Indiana /pytz_data/zoneinfo/US/East-Indiana
    pytz/zoneinfo/US/Eastern /pytz_data/zoneinfo/US/Eastern
    pytz/zoneinfo/US/Hawaii /pytz_data/zoneinfo/US/Hawaii
    pytz/zoneinfo/US/Indiana-Starke /pytz_data/zoneinfo/US/Indiana-Starke
    pytz/zoneinfo/US/Michigan /pytz_data/zoneinfo/US/Michigan
    pytz/zoneinfo/US/Mountain /pytz_data/zoneinfo/US/Mountain
    pytz/zoneinfo/US/Pacific /pytz_data/zoneinfo/US/Pacific
    pytz/zoneinfo/US/Pacific-New /pytz_data/zoneinfo/US/Pacific-New
    pytz/zoneinfo/US/Samoa /pytz_data/zoneinfo/US/Samoa
    pytz/zoneinfo/UTC /pytz_data/zoneinfo/UTC
    pytz/zoneinfo/Universal /pytz_data/zoneinfo/Universal
    pytz/zoneinfo/W-SU /pytz_data/zoneinfo/W-SU
    pytz/zoneinfo/WET /pytz_data/zoneinfo/WET
    pytz/zoneinfo/Zulu /pytz_data/zoneinfo/Zulu
    pytz/zoneinfo/iso3166.tab /pytz_data/zoneinfo/iso3166.tab
    pytz/zoneinfo/leapseconds /pytz_data/zoneinfo/leapseconds
    pytz/zoneinfo/localtime /pytz_data/zoneinfo/localtime
    pytz/zoneinfo/posixrules /pytz_data/zoneinfo/posixrules
    pytz/zoneinfo/tzdata.zi /pytz_data/zoneinfo/tzdata.zi
    pytz/zoneinfo/zone.tab /pytz_data/zoneinfo/zone.tab
    pytz/zoneinfo/zone1970.tab /pytz_data/zoneinfo/zone1970.tab
)

NO_LINT()

END()

RECURSE_FOR_TESTS(
    tests
)
