build:
  stage: build
  script:
    - cd catboost/python-package/catboost 
    - ../../../ya make -r -DDEBUGINFO -DOS_SDK=local -DUSE_ARCADIA_PYTHON=no -DUSE_SYSTEM_PYTHON=2.7 -DHAVE_CUDA=no
    - cd ../
    - python mk_wheel.py -r -DDEBUGINFO -DOS_SDK=local -DUSE_ARCADIA_PYTHON=no -DUSE_SYSTEM_PYTHON=2.7 -DHAVE_CUDA=no
  artifacts:
    paths:
      - catboost/python-package/catboost-*.whl

performance_test:
  stage: test
  tags:
    - performance
  before_script:
    - pip2 install catboost/python-package/catboost-*.whl --user
    - pip2 install xgboost matplotlib tqdm scipy lightgbm pandas numpy scikit_learn --user
    - pip2 install tbb --user
    
  script:
    - cd catboost/benchmarks/training_speed
    - python -m tbb benchmark.py --iterations 10
  artifacts:
    paths:
      - catboost/benchmarks/training_speed/common-table.txt
  dependencies:
    - build
