build:
  stage: build
#  before_script:
#    - apt update && apt -y install make autoconf
  script:
    - cd catboost/python-package/catboost 
    - ../../../ya make -r -DDEBUGINFO -DOS_SDK=local -DUSE_ARCADIA_PYTHON=no -DUSE_SYSTEM_PYTHON=2.7 -DHAVE_CUDA=no
    - cd ../
    - python mk_wheel.py -DDEBUGINFO -DOS_SDK=local -DUSE_ARCADIA_PYTHON=no -DUSE_SYSTEM_PYTHON=2.7 -DHAVE_CUDA=no
#  artifacts:
#    paths:
#      - mybinary
      # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
      # cache:
      #   paths:
      #     - "*.o"

# run tests using the binary built before
#test:
#  stage: test
#  script:
#    - ./runmytests.sh
