build:
  stage: build
  tags:
    - build
  script:
    - cd catboost/python-package/catboost 
#    - nice -19 ../../../ya make -r -DDEBUGINFO -DOS_SDK=local -DUSE_ARCADIA_PYTHON=no -DUSE_SYSTEM_PYTHON=2.7 -DHAVE_CUDA=no
    - cd ../
    - nice -19 python mk_wheel.py -r -DDEBUGINFO -DOS_SDK=local -DUSE_ARCADIA_PYTHON=no -DUSE_SYSTEM_PYTHON=2.7 -DHAVE_CUDA=no
  artifacts:
    paths:
      - catboost/python-package/catboost-*.whl

correctness_test:
  stage: test
  tags:
    - test
  script:
    - cd catboost/pytest
    - nice -19 ../../ya make -t -A 
  dependencies:
    - build

performance_test:
  stage: test
  tags:
    - performance
  before_script:
    - pip2 install -U catboost/python-package/catboost-*.whl --user
    - pip2 install -U xgboost matplotlib tqdm scipy lightgbm pandas numpy scikit_learn --user
    - pip2 install -U icc-rt tbb tbb4py --user
    
  script:
    - cd catboost/benchmarks/training_speed
    - python -m tbb --ipc -a --allocator-huge-pages -v benchmark.py --iterations 10
  artifacts:
    paths:
      - catboost/benchmarks/training_speed/common-table.txt
  dependencies:
    - build