# Generated by devtools/yamaker.

PROGRAM()



PEERDIR(
    contrib/restricted/libffi
)

NO_COMPILER_WARNINGS()

NO_RUNTIME()

SRCDIR(contrib/restricted/libffi/testsuite/libffi.closures)

SRCS(
    cls_align_longdouble.c
)

END()
