#pragma once

#include "config-linux.h"

#undef HAVE_DECL___FPENDING
#undef HAVE_STDIO_EXT_H

#undef HAVE___FSETERR

#undef HAVE_FEATURES_H

#undef HAVE_DECL_PROGRAM_INVOCATION_NAME
#undef HAVE_DECL_PROGRAM_INVOCATION_SHORT_NAME
#define HAVE_VAR___PROGNAME 1

#undef HAVE_OBSTACK
#undef HAVE_OBSTACK_PRINTF

// fread_unlocked should be controlled by USE_UNLOCKED_IO, yet it is not
#undef USE_UNLOCKED_IO
#undef HAVE_DECL_FEOF_UNLOCKED
#undef HAVE_DECL_FERROR_UNLOCKED
#undef HAVE_DECL_FFLUSH_UNLOCKED
#undef HAVE_DECL_FGETS_UNLOCKED
#undef HAVE_DECL_FPUTC_UNLOCKED
#undef HAVE_DECL_FPUTS_UNLOCKED
#undef HAVE_DECL_FREAD_UNLOCKED
#undef HAVE_DECL_FWRITE_UNLOCKED
#undef HAVE_DECL_GETCHAR_UNLOCKED
#undef HAVE_DECL_GETC_UNLOCKED
#undef HAVE_DECL_PUTCHAR_UNLOCKED
#undef HAVE_DECL_PUTC_UNLOCKED

#define _GL_ARG_NONNULL(...)

#undef HAVE_STRUCT_STAT_ST_ATIM_TV_NSEC
#undef TYPEOF_STRUCT_STAT_ST_ATIM_IS_STRUCT_TIMESPEC
