/* DO NOT EDIT! GENERATED AUTOMATICALLY! */
#if HAVE_WINSOCK2_H
# include <winsock2.h> /* avoid mingw pollution on DATADIR */
#endif
#define PREFIX "/var/empty/bison-3.7.6"
#define EXEC_PREFIX "/var/empty/bison-3.7.6"
#define BINDIR "/var/empty/bison-3.7.6/bin"
#define SBINDIR "/var/empty/bison-3.7.6/sbin"
#define LIBEXECDIR "/var/empty/bison-3.7.6/libexec"
#define DATAROOTDIR "/var/empty/bison-3.7.6/share"
#define DATADIR "/var/empty/bison-3.7.6/share"
#define SYSCONFDIR "/var/empty/bison-3.7.6/etc"
#define SHAREDSTATEDIR "/var/empty/bison-3.7.6/com"
#define LOCALSTATEDIR "/var/empty/bison-3.7.6/var"
#define RUNSTATEDIR "/var/empty/bison-3.7.6/var/run"
#define INCLUDEDIR "/var/empty/bison-3.7.6/include"
#define OLDINCLUDEDIR "/usr/include"
#define DOCDIR "/var/empty/bison-3.7.6/share/doc/bison"
#define INFODIR "/var/empty/bison-3.7.6/share/info"
#define HTMLDIR "/var/empty/bison-3.7.6/share/doc/bison"
#define DVIDIR "/var/empty/bison-3.7.6/share/doc/bison"
#define PDFDIR "/var/empty/bison-3.7.6/share/doc/bison"
#define PSDIR "/var/empty/bison-3.7.6/share/doc/bison"
#define LIBDIR "/var/empty/bison-3.7.6/lib"
#define LISPDIR "/var/empty/bison-3.7.6/share/emacs/site-lisp"
#define LOCALEDIR "/var/empty/bison-3.7.6/share/locale"
#define MANDIR "/var/empty/bison-3.7.6/share/man"
#define PKGDATADIR "/var/empty/bison-3.7.6/share/bison"
#define PKGINCLUDEDIR "/var/empty/bison-3.7.6/include/bison"
#define PKGLIBDIR "/var/empty/bison-3.7.6/lib/bison"
#define PKGLIBEXECDIR "/var/empty/bison-3.7.6/libexec/bison"
