LIBRARY()



LICENSE(Python-2.0)

RESOURCE_FILES(
    __init__.py
    btm_matcher.py
    btm_utils.py
    fixer_base.py
    fixer_util.py
    fixes/__init__.py
    fixes/fix_apply.py
    fixes/fix_asserts.py
    fixes/fix_basestring.py
    fixes/fix_buffer.py
    fixes/fix_dict.py
    fixes/fix_except.py
    fixes/fix_exec.py
    fixes/fix_execfile.py
    fixes/fix_exitfunc.py
    fixes/fix_filter.py
    fixes/fix_funcattrs.py
    fixes/fix_future.py
    fixes/fix_getcwdu.py
    fixes/fix_has_key.py
    fixes/fix_idioms.py
    fixes/fix_import.py
    fixes/fix_imports.py
    fixes/fix_imports2.py
    fixes/fix_input.py
    fixes/fix_intern.py
    fixes/fix_isinstance.py
    fixes/fix_itertools.py
    fixes/fix_itertools_imports.py
    fixes/fix_long.py
    fixes/fix_map.py
    fixes/fix_metaclass.py
    fixes/fix_methodattrs.py
    fixes/fix_ne.py
    fixes/fix_next.py
    fixes/fix_nonzero.py
    fixes/fix_numliterals.py
    fixes/fix_operator.py
    fixes/fix_paren.py
    fixes/fix_print.py
    fixes/fix_raise.py
    fixes/fix_raw_input.py
    fixes/fix_reduce.py
    fixes/fix_reload.py
    fixes/fix_renames.py
    fixes/fix_repr.py
    fixes/fix_set_literal.py
    fixes/fix_standarderror.py
    fixes/fix_sys_exc.py
    fixes/fix_throw.py
    fixes/fix_tuple_params.py
    fixes/fix_types.py
    fixes/fix_unicode.py
    fixes/fix_urllib.py
    fixes/fix_ws_comma.py
    fixes/fix_xrange.py
    fixes/fix_xreadlines.py
    fixes/fix_zip.py
    main.py
    patcomp.py
    pgen2/__init__.py
    pgen2/conv.py
    pgen2/driver.py
    pgen2/grammar.py
    pgen2/literals.py
    pgen2/parse.py
    pgen2/pgen.py
    pgen2/token.py
    pgen2/tokenize.py
    pygram.py
    pytree.py
    refactor.py
)

END()
