# Generated by devtools/yamaker.

RECURSE(
    libffi.bhaible
    libffi.call
    libffi.closures
)

IF (OS_DARWIN AND ARCH_AARCH64)
    SET(MAC_M1 yes)
ENDIF()

IF (NOT MAC_M1 AND NOT OS_IOS)
    RECURSE(
    libffi.go
)
ENDIF()

IF (NOT OS_WINDOWS AND NOT ARCH_PPC64LE)
    RECURSE(
    libffi.complex
)
ENDIF()
