#include "config-linux.h"

#define ARCHIVE_CRYPTO_MD5_LIBSYSTEM 1
#define ARCHIVE_CRYPTO_SHA1_LIBSYSTEM 1
#define ARCHIVE_CRYPTO_SHA256_LIBSYSTEM 1
#define ARCHIVE_CRYPTO_SHA384_LIBSYSTEM 1
#define ARCHIVE_CRYPTO_SHA512_LIBSYSTEM 1

#define HAVE_ARC4RANDOM_BUF 1
#define HAVE_CHFLAGS 1
#define HAVE_COPYFILE_H 1
#define HAVE_D_MD_ORDER 1
#define HAVE_EFTYPE 1
#define HAVE_FCHFLAGS 1
#define HAVE_GETVFSBYNAME 1
#define HAVE_LCHFLAGS 1
#define HAVE_READPASSPHRASE 1
#define HAVE_READPASSPHRASE_H 1
#define HAVE_STRUCT_STAT_ST_BIRTHTIME 1
#define HAVE_STRUCT_STAT_ST_BIRTHTIMESPEC_TV_NSEC 1
#define HAVE_STRUCT_STAT_ST_FLAGS 1
#define HAVE_STRUCT_STAT_ST_MTIMESPEC_TV_NSEC 1
#define HAVE_STRUCT_VFSCONF 1

#undef HAVE_FUTIMENS
#undef HAVE_FUTIMESAT
#undef HAVE_LINUX_FIEMAP_H
#undef HAVE_LINUX_FS_H
#undef HAVE_LINUX_MAGIC_H
#undef HAVE_LINUX_TYPES_H
#undef HAVE_STRUCT_STAT_ST_MTIM_TV_NSEC
#undef HAVE_SYS_STATFS_H
#undef HAVE_SYS_SYSMACROS_H
#undef HAVE_SYS_VFS_H 
#undef HAVE_SYS_XATTR_H
#undef HAVE_UTIMENSAT
#undef MAJOR_IN_SYSMACROS

#undef HAVE_POSIX_SPAWNP
#define HAVE_POSIX_SPAWNP 1

#undef HAVE_STRUCT_STATFS
