/* File: _spropackmodule.c
 * This file is auto-generated with f2py (version:1.26.4).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Sat Nov 18 18:32:55 2023
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
#include <string.h>
#include <setjmp.h>
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *_spropack_error;
static PyObject *_spropack_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef signed char signed_char;
typedef char * string;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
typedef float(*cb_saprod_in___user__routines_typedef)(string,int *,int *,float *,float *,float *,int *,int);

/********************** See f2py2e/cfuncs.py: cppmacros **********************/

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


#define PRINTPYOBJERR(obj)\
    fprintf(stderr,"_spropack.error is related to ");\
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");

#define FAILNULL(p) do {                                            \
    if ((p) == NULL) {                                              \
        PyErr_SetString(PyExc_MemoryError, "NULL pointer found");   \
        goto capi_fail;                                             \
    }                                                               \
} while (0)


#define STRINGMALLOC(str,len)\
    if ((str = (string)malloc(len+1)) == NULL) {\
        PyErr_SetString(PyExc_MemoryError, "out of memory");\
        goto capi_fail;\
    } else {\
        (str)[len] = '\0';\
    }


#define GETSCALARFROMPYTUPLE(tuple,index,var,ctype,mess) {\
        if ((capi_tmp = PyTuple_GetItem((tuple),(index)))==NULL) goto capi_fail;\
        if (!(ctype ## _from_pyobj((var),capi_tmp,mess)))\
            goto capi_fail;\
    }


#define pyobj_from_string1size(v,len) (PyUnicode_FromStringAndSize((char *)v, len))

#define pyobj_from_int1(v) (PyLong_FromLong(v))


#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif


#ifndef F2PY_THREAD_LOCAL_DECL
#if defined(_MSC_VER)
#define F2PY_THREAD_LOCAL_DECL __declspec(thread)
#elif defined(NPY_OS_MINGW)
#define F2PY_THREAD_LOCAL_DECL __thread
#elif defined(__STDC_VERSION__) \
      && (__STDC_VERSION__ >= 201112L) \
      && !defined(__STDC_NO_THREADS__) \
      && (!defined(__GLIBC__) || __GLIBC__ > 2 || (__GLIBC__ == 2 && __GLIBC_MINOR__ > 12)) \
      && !defined(NPY_OS_OPENBSD) && !defined(NPY_OS_HAIKU)
/* __STDC_NO_THREADS__ was first defined in a maintenance release of glibc 2.12,
   see https://lists.gnu.org/archive/html/commit-hurd/2012-07/msg00180.html,
   so `!defined(__STDC_NO_THREADS__)` may give false positive for the existence
   of `threads.h` when using an older release of glibc 2.12
   See gh-19437 for details on OpenBSD */
#include <threads.h>
#define F2PY_THREAD_LOCAL_DECL thread_local
#elif defined(__GNUC__) \
      && (__GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ >= 4)))
#define F2PY_THREAD_LOCAL_DECL __thread
#endif
#endif


#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/* See fortranobject.h for definitions. The macros here are provided for BC. */
#define rank f2py_rank
#define shape f2py_shape
#define fshape f2py_shape
#define len f2py_len
#define flen f2py_flen
#define slen f2py_slen
#define size f2py_size


#define STRINGFREE(str) do {if (!(str == NULL)) free(str);} while (0)


/*
STRINGPADN replaces null values with padding values from the right.

`to` must have size of at least N bytes.

If the `to[N-1]` has null value, then replace it and all the
preceding, nulls with the given padding.

STRINGPADN(to, N, PADDING, NULLVALUE) is an inverse operation.
*/
#define STRINGPADN(to, N, NULLVALUE, PADDING)                   \
    do {                                                        \
        int _m = (N);                                           \
        char *_to = (to);                                       \
        for (_m -= 1; _m >= 0 && _to[_m] == NULLVALUE; _m--) {  \
             _to[_m] = PADDING;                                 \
        }                                                       \
    } while (0)


#define SWAP(a,b,t) {\
    t *c;\
    c = a;\
    a = b;\
    b = c;}


#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(_spropack_error,errstring);\
        /*goto capi_fail;*/\
    } else 

/*
STRINGCOPYN copies N bytes.

`to` and `from` buffers must have sizes of at least N bytes.
*/
#define STRINGCOPYN(to,from,N)                                  \
    do {                                                        \
        int _m = (N);                                           \
        char *_to = (to);                                       \
        char *_from = (from);                                   \
        FAILNULL(_to); FAILNULL(_from);                         \
        (void)strncpy(_to, _from, _m);             \
    } while (0)


/************************ See f2py2e/cfuncs.py: cfuncs ************************/

static int
double_from_pyobj(double* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
        *v = PyFloat_AsDouble(obj);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    tmp = PyNumber_Float(obj);
    if (tmp) {
        *v = PyFloat_AsDouble(tmp);
        Py_DECREF(tmp);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = _spropack_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


static int
float_from_pyobj(float* v, PyObject *obj, const char *errmess)
{
    double d=0.0;
    if (double_from_pyobj(&d,obj,errmess)) {
        *v = (float)d;
        return 1;
    }
    return 0;
}


/*
  Create a new string buffer `str` of at most length `len` from a
  Python string-like object `obj`.

  The string buffer has given size (len) or the size of inistr when len==-1.

  The string buffer is padded with blanks: in Fortran, trailing blanks
  are insignificant contrary to C nulls.
 */
static int
string_from_pyobj(string *str, int *len, const string inistr, PyObject *obj,
                  const char *errmess)
{
    PyObject *tmp = NULL;
    string buf = NULL;
    npy_intp n = -1;
#ifdef DEBUGCFUNCS
fprintf(stderr,"string_from_pyobj(str='%s',len=%d,inistr='%s',obj=%p)\n",
               (char*)str, *len, (char *)inistr, obj);
#endif
    if (obj == Py_None) {
        n = strlen(inistr);
        buf = inistr;
    }
    else if (PyArray_Check(obj)) {
        PyArrayObject *arr = (PyArrayObject *)obj;
        if (!ISCONTIGUOUS(arr)) {
            PyErr_SetString(PyExc_ValueError,
                            "array object is non-contiguous.");
            goto capi_fail;
        }
        n = PyArray_NBYTES(arr);
        buf = PyArray_DATA(arr);
        n = strnlen(buf, n);
    }
    else {
        if (PyBytes_Check(obj)) {
            tmp = obj;
            Py_INCREF(tmp);
        }
        else if (PyUnicode_Check(obj)) {
            tmp = PyUnicode_AsASCIIString(obj);
        }
        else {
            PyObject *tmp2;
            tmp2 = PyObject_Str(obj);
            if (tmp2) {
                tmp = PyUnicode_AsASCIIString(tmp2);
                Py_DECREF(tmp2);
            }
            else {
                tmp = NULL;
            }
        }
        if (tmp == NULL) goto capi_fail;
        n = PyBytes_GET_SIZE(tmp);
        buf = PyBytes_AS_STRING(tmp);
    }
    if (*len == -1) {
        /* TODO: change the type of `len` so that we can remove this */
        if (n > NPY_MAX_INT) {
            PyErr_SetString(PyExc_OverflowError,
                            "object too large for a 32-bit int");
            goto capi_fail;
        }
        *len = n;
    }
    else if (*len < n) {
        /* discard the last (len-n) bytes of input buf */
        n = *len;
    }
    if (n < 0 || *len < 0 || buf == NULL) {
        goto capi_fail;
    }
    STRINGMALLOC(*str, *len);  // *str is allocated with size (*len + 1)
    if (n < *len) {
        /*
          Pad fixed-width string with nulls. The caller will replace
          nulls with blanks when the corresponding argument is not
          intent(c).
        */
        memset(*str + n, '\0', *len - n);
    }
    STRINGCOPYN(*str, buf, n);
    Py_XDECREF(tmp);
    return 1;
capi_fail:
    Py_XDECREF(tmp);
    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = _spropack_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }

    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = _spropack_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


static int
create_cb_arglist(PyObject* fun, PyTupleObject* xa , const int maxnofargs,
                  const int nofoptargs, int *nofargs, PyTupleObject **args,
                  const char *errmess)
{
    PyObject *tmp = NULL;
    PyObject *tmp_fun = NULL;
    Py_ssize_t tot, opt, ext, siz, i, di = 0;
    CFUNCSMESS("create_cb_arglist\n");
    tot=opt=ext=siz=0;
    /* Get the total number of arguments */
    if (PyFunction_Check(fun)) {
        tmp_fun = fun;
        Py_INCREF(tmp_fun);
    }
    else {
        di = 1;
        if (PyObject_HasAttrString(fun,"im_func")) {
            tmp_fun = PyObject_GetAttrString(fun,"im_func");
        }
        else if (PyObject_HasAttrString(fun,"__call__")) {
            tmp = PyObject_GetAttrString(fun,"__call__");
            if (PyObject_HasAttrString(tmp,"im_func"))
                tmp_fun = PyObject_GetAttrString(tmp,"im_func");
            else {
                tmp_fun = fun; /* built-in function */
                Py_INCREF(tmp_fun);
                tot = maxnofargs;
                if (PyCFunction_Check(fun)) {
                    /* In case the function has a co_argcount (like on PyPy) */
                    di = 0;
                }
                if (xa != NULL)
                    tot += PyTuple_Size((PyObject *)xa);
            }
            Py_XDECREF(tmp);
        }
        else if (PyFortran_Check(fun) || PyFortran_Check1(fun)) {
            tot = maxnofargs;
            if (xa != NULL)
                tot += PyTuple_Size((PyObject *)xa);
            tmp_fun = fun;
            Py_INCREF(tmp_fun);
        }
        else if (F2PyCapsule_Check(fun)) {
            tot = maxnofargs;
            if (xa != NULL)
                ext = PyTuple_Size((PyObject *)xa);
            if(ext>0) {
                fprintf(stderr,"extra arguments tuple cannot be used with PyCapsule call-back\n");
                goto capi_fail;
            }
            tmp_fun = fun;
            Py_INCREF(tmp_fun);
        }
    }

    if (tmp_fun == NULL) {
        fprintf(stderr,
                "Call-back argument must be function|instance|instance.__call__|f2py-function "
                "but got %s.\n",
                ((fun == NULL) ? "NULL" : Py_TYPE(fun)->tp_name));
        goto capi_fail;
    }

    if (PyObject_HasAttrString(tmp_fun,"__code__")) {
        if (PyObject_HasAttrString(tmp = PyObject_GetAttrString(tmp_fun,"__code__"),"co_argcount")) {
            PyObject *tmp_argcount = PyObject_GetAttrString(tmp,"co_argcount");
            Py_DECREF(tmp);
            if (tmp_argcount == NULL) {
                goto capi_fail;
            }
            tot = PyLong_AsSsize_t(tmp_argcount) - di;
            Py_DECREF(tmp_argcount);
        }
    }
    /* Get the number of optional arguments */
    if (PyObject_HasAttrString(tmp_fun,"__defaults__")) {
        if (PyTuple_Check(tmp = PyObject_GetAttrString(tmp_fun,"__defaults__")))
            opt = PyTuple_Size(tmp);
        Py_XDECREF(tmp);
    }
    /* Get the number of extra arguments */
    if (xa != NULL)
        ext = PyTuple_Size((PyObject *)xa);
    /* Calculate the size of call-backs argument list */
    siz = MIN(maxnofargs+ext,tot);
    *nofargs = MAX(0,siz-ext);

#ifdef DEBUGCFUNCS
    fprintf(stderr,
            "debug-capi:create_cb_arglist:maxnofargs(-nofoptargs),"
            "tot,opt,ext,siz,nofargs = %d(-%d), %zd, %zd, %zd, %zd, %d\n",
            maxnofargs, nofoptargs, tot, opt, ext, siz, *nofargs);
#endif

    if (siz < tot-opt) {
        fprintf(stderr,
                "create_cb_arglist: Failed to build argument list "
                "(siz) with enough arguments (tot-opt) required by "
                "user-supplied function (siz,tot,opt=%zd, %zd, %zd).\n",
                siz, tot, opt);
        goto capi_fail;
    }

    /* Initialize argument list */
    *args = (PyTupleObject *)PyTuple_New(siz);
    for (i=0;i<*nofargs;i++) {
        Py_INCREF(Py_None);
        PyTuple_SET_ITEM((PyObject *)(*args),i,Py_None);
    }
    if (xa != NULL)
        for (i=(*nofargs);i<siz;i++) {
            tmp = PyTuple_GetItem((PyObject *)xa,i-(*nofargs));
            Py_INCREF(tmp);
            PyTuple_SET_ITEM(*args,i,tmp);
        }
    CFUNCSMESS("create_cb_arglist-end\n");
    Py_DECREF(tmp_fun);
    return 1;

capi_fail:
    if (PyErr_Occurred() == NULL)
        PyErr_SetString(_spropack_error, errmess);
    Py_XDECREF(tmp_fun);
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(slansvd,SLANSVD)(string,string,int*,int*,int*,int*,cb_saprod_in___user__routines_typedef,float*,int*,float*,float*,float*,int*,float*,float*,int*,int*,int*,float*,int*,int*,float*,int*,size_t,size_t);
extern void F_FUNC_US(slansvd_irl,SLANSVD_IRL)(string,string,string,int*,int*,int*,int*,int*,int*,cb_saprod_in___user__routines_typedef,float*,int*,float*,float*,float*,int*,float*,float*,int*,int*,int*,float*,int*,int*,float*,int*,size_t,size_t,size_t);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/

/*********************** cb_saprod_in___user__routines ***********************/
typedef struct {
    PyObject *capi;
    PyTupleObject *args_capi;
    int nofargs;
    jmp_buf jmpbuf;
} cb_saprod_in___user__routines_t;

#if defined(F2PY_THREAD_LOCAL_DECL) && !defined(F2PY_USE_PYTHON_TLS)

static F2PY_THREAD_LOCAL_DECL cb_saprod_in___user__routines_t *_active_cb_saprod_in___user__routines = NULL;

static cb_saprod_in___user__routines_t *swap_active_cb_saprod_in___user__routines(cb_saprod_in___user__routines_t *ptr) {
    cb_saprod_in___user__routines_t *prev = _active_cb_saprod_in___user__routines;
    _active_cb_saprod_in___user__routines = ptr;
    return prev;
}

static cb_saprod_in___user__routines_t *get_active_cb_saprod_in___user__routines(void) {
    return _active_cb_saprod_in___user__routines;
}

#else

static cb_saprod_in___user__routines_t *swap_active_cb_saprod_in___user__routines(cb_saprod_in___user__routines_t *ptr) {
    char *key = "__f2py_cb_cb_saprod_in___user__routines";
    return (cb_saprod_in___user__routines_t *)F2PySwapThreadLocalCallbackPtr(key, ptr);
}

static cb_saprod_in___user__routines_t *get_active_cb_saprod_in___user__routines(void) {
    char *key = "__f2py_cb_cb_saprod_in___user__routines";
    return (cb_saprod_in___user__routines_t *)F2PyGetThreadLocalCallbackPtr(key);
}

#endif

/*typedef float(*cb_saprod_in___user__routines_typedef)(string,int *,int *,float *,float *,float *,int *,int);*/
static float cb_saprod_in___user__routines (string transa,int *m_cb_capi,int *n_cb_capi,float *x,float *y,float *dparm,int *iparm,int transa_cb_len) {
    cb_saprod_in___user__routines_t cb_local = { NULL, NULL, 0 };
    cb_saprod_in___user__routines_t *cb = NULL;
    PyTupleObject *capi_arglist = NULL;
    PyObject *capi_return = NULL;
    PyObject *capi_tmp = NULL;
    PyObject *capi_arglist_list = NULL;
    int capi_j,capi_i = 0;
    int capi_longjmp_ok = 1;
/*decl*/
    float return_value = 0;
    int m=(*m_cb_capi);
    int n=(*n_cb_capi);
    npy_intp iparm_Dims[1] = {-1};
    npy_intp dparm_Dims[1] = {-1};
    npy_intp x_Dims[1] = {-1};
    npy_intp y_Dims[1] = {-1};
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
    cb = get_active_cb_saprod_in___user__routines();
    if (cb == NULL) {
        capi_longjmp_ok = 0;
        cb = &cb_local;
    }
    capi_arglist = cb->args_capi;
    CFUNCSMESS("cb:Call-back function cb_saprod_in___user__routines (maxnofargs=7(-0))\n");
    CFUNCSMESSPY("cb:cb_saprod_in___user__routines_capi=",cb->capi);
    if (cb->capi==NULL) {
        capi_longjmp_ok = 0;
        cb->capi = PyObject_GetAttrString(_spropack_module,"saprod");
        CFUNCSMESSPY("cb:cb_saprod_in___user__routines_capi=",cb->capi);
    }
    if (cb->capi==NULL) {
        PyErr_SetString(_spropack_error,"cb: Callback saprod not defined (as an argument or module _spropack attribute).\n");
        goto capi_fail;
    }
    if (F2PyCapsule_Check(cb->capi)) {
    cb_saprod_in___user__routines_typedef cb_saprod_in___user__routines_cptr;
    cb_saprod_in___user__routines_cptr = F2PyCapsule_AsVoidPtr(cb->capi);
    return_value=(*cb_saprod_in___user__routines_cptr)(transa,m_cb_capi,n_cb_capi,x,y,dparm,iparm,transa_cb_len);
        return return_value;
    }
    if (capi_arglist==NULL) {
        capi_longjmp_ok = 0;
        capi_tmp = PyObject_GetAttrString(_spropack_module,"saprod_extra_args");
        if (capi_tmp) {
            capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
            Py_DECREF(capi_tmp);
            if (capi_arglist==NULL) {
                PyErr_SetString(_spropack_error,"Failed to convert _spropack.saprod_extra_args to tuple.\n");
                goto capi_fail;
            }
        } else {
            PyErr_Clear();
            capi_arglist = (PyTupleObject *)Py_BuildValue("()");
        }
    }
    if (capi_arglist == NULL) {
        PyErr_SetString(_spropack_error,"Callback saprod argument list is not set.\n");
        goto capi_fail;
    }
/*setdims*/
    iparm_Dims[0]=0;
    dparm_Dims[0]=0;
    x_Dims[0]=(transa[0] == 'n'?n:m);
    y_Dims[0]=(transa[0] == 'n'?m:n);
#ifdef PYPY_VERSION
#define CAPI_ARGLIST_SETITEM(idx, value) PyList_SetItem((PyObject *)capi_arglist_list, idx, value)
    capi_arglist_list = PySequence_List(capi_arglist);
    if (capi_arglist_list == NULL) goto capi_fail;
#else
#define CAPI_ARGLIST_SETITEM(idx, value) PyTuple_SetItem((PyObject *)capi_arglist, idx, value)
#endif
/*pyobjfrom*/
    if (cb->nofargs>capi_i)
        if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_string1size(transa,transa_cb_len)))
            goto capi_fail;
    if (cb->nofargs>capi_i)
        if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(m)))
            goto capi_fail;
    if (cb->nofargs>capi_i)
        if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(n)))
            goto capi_fail;
    if (cb->nofargs>capi_i) {
        /* tmp_arr will be inserted to capi_arglist_list that will be
           destroyed when leaving callback function wrapper together
           with tmp_arr. */
        PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,
          1,x_Dims,NPY_FLOAT,NULL,(char*)x,1,
          NPY_ARRAY_FARRAY,NULL);


        if (tmp_arr==NULL)
            goto capi_fail;
        if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
            goto capi_fail;
}
    if (cb->nofargs>capi_i) {
        /* tmp_arr will be inserted to capi_arglist_list that will be
           destroyed when leaving callback function wrapper together
           with tmp_arr. */
        PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,
          1,y_Dims,NPY_FLOAT,NULL,(char*)y,1,
          NPY_ARRAY_FARRAY,NULL);


        if (tmp_arr==NULL)
            goto capi_fail;
        if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
            goto capi_fail;
}
    if (cb->nofargs>capi_i) {
        /* tmp_arr will be inserted to capi_arglist_list that will be
           destroyed when leaving callback function wrapper together
           with tmp_arr. */
        PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,
          1,dparm_Dims,NPY_FLOAT,NULL,(char*)dparm,1,
          NPY_ARRAY_FARRAY,NULL);


        if (tmp_arr==NULL)
            goto capi_fail;
        if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
            goto capi_fail;
}
    if (cb->nofargs>capi_i) {
        /* tmp_arr will be inserted to capi_arglist_list that will be
           destroyed when leaving callback function wrapper together
           with tmp_arr. */
        PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,
          1,iparm_Dims,NPY_INT,NULL,(char*)iparm,1,
          NPY_ARRAY_FARRAY,NULL);


        if (tmp_arr==NULL)
            goto capi_fail;
        if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
            goto capi_fail;
}
#undef CAPI_ARGLIST_SETITEM
#ifdef PYPY_VERSION
    CFUNCSMESSPY("cb:capi_arglist=",capi_arglist_list);
#else
    CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
#endif
    CFUNCSMESS("cb:Call-back calling Python function saprod.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
#ifdef PYPY_VERSION
    capi_return = PyObject_CallObject(cb->capi,(PyObject *)capi_arglist_list);
    Py_DECREF(capi_arglist_list);
    capi_arglist_list = NULL;
#else
    capi_return = PyObject_CallObject(cb->capi,(PyObject *)capi_arglist);
#endif
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
    CFUNCSMESSPY("cb:capi_return=",capi_return);
    if (capi_return == NULL) {
        fprintf(stderr,"capi_return is NULL\n");
        goto capi_fail;
    }
    if (capi_return == Py_None) {
        Py_DECREF(capi_return);
        capi_return = Py_BuildValue("()");
    }
    else if (!PyTuple_Check(capi_return)) {
        capi_return = Py_BuildValue("(N)",capi_return);
    }
    capi_j = PyTuple_Size(capi_return);
    capi_i = 0;
/*frompyobj*/
    if (capi_j>capi_i) {
        GETSCALARFROMPYTUPLE(capi_return,capi_i++,&return_value,float,
          "float_from_pyobj failed in converting return_value of"
          " call-back function cb_saprod_in___user__routines to C float\n");
    } else {
        fprintf(stderr,"Warning: call-back function cb_saprod_in___user__routines did not provide"
                       " return value (index=%d, type=float)\n",capi_i);
    }
    CFUNCSMESS("cb:cb_saprod_in___user__routines:successful\n");
    Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
    goto capi_return_pt;
capi_fail:
    fprintf(stderr,"Call-back cb_saprod_in___user__routines failed.\n");
    Py_XDECREF(capi_return);
    Py_XDECREF(capi_arglist_list);
    if (capi_longjmp_ok) {
        longjmp(cb->jmpbuf,-1);
    }
capi_return_pt:
    ;
    return return_value;
}
/******************** end of cb_saprod_in___user__routines ********************/


/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************** slansvd **********************************/
static char doc_f2py_rout__spropack_slansvd[] = "\
u,sigma,bnd,v,info = slansvd(jobu,jobv,m,n,k,aprod,u,v,tolin,work,iwork,doption,ioption,dparm,iparm,[kmax,ldu,ldv,lwork,liwork,aprod_extra_args])\n\nWrapper for ``slansvd``.\
\n\nParameters\n----------\n"
"jobu : input string(len=1)\n"
"jobv : input string(len=1)\n"
"m : input int\n"
"n : input int\n"
"k : input int\n"
"aprod : call-back function => saprod\n"
"u : input rank-2 array('f') with bounds (ldu,1 + kmax)\n"
"v : input rank-2 array('f') with bounds (ldv,kmax)\n"
"tolin : input float\n"
"work : input rank-1 array('f') with bounds (lwork)\n"
"iwork : input rank-1 array('i') with bounds (liwork)\n"
"doption : input rank-1 array('f') with bounds (3)\n"
"ioption : input rank-1 array('i') with bounds (2)\n"
"dparm : input rank-1 array('f') with bounds (*)\n"
"iparm : input rank-1 array('i') with bounds (*)\n"
"\nOther Parameters\n----------------\n"
"kmax : input int, optional\n    Default: -1 + shape(u, 1)\n"
"aprod_extra_args : input tuple, optional\n    Default: ()\n"
"ldu : input int, optional\n    Default: shape(u,0)\n"
"ldv : input int, optional\n    Default: shape(v,0)\n"
"lwork : input int, optional\n    Default: len(work)\n"
"liwork : input int, optional\n    Default: len(iwork)\n"
"\nReturns\n-------\n"
"u : rank-2 array('f') with bounds (ldu,1 + kmax)\n"
"sigma : rank-1 array('f') with bounds (k)\n"
"bnd : rank-1 array('f') with bounds (k)\n"
"v : rank-2 array('f') with bounds (ldv,kmax)\n"
"info : int\n"
"\nNotes\n-----\nCall-back functions::\n\n"
"    def saprod(transa,m,n,x,y,dparm,iparm): return saprod\n\
    Required arguments:\n"
"        transa : input string(len=1)\n"
"        m : input int\n"
"        n : input int\n"
"        x : input rank-1 array('f') with bounds ((transa[0] == 'n'?n:m))\n"
"        y : input rank-1 array('f') with bounds ((transa[0] == 'n'?m:n))\n"
"        dparm : input rank-1 array('f') with bounds (*)\n"
"        iparm : input rank-1 array('i') with bounds (*)\n"
"    Return objects:\n"
"        saprod : float";
/* extern void F_FUNC(slansvd,SLANSVD)(string,string,int*,int*,int*,int*,cb_saprod_in___user__routines_typedef,float*,int*,float*,float*,float*,int*,float*,float*,int*,int*,int*,float*,int*,int*,float*,int*,size_t,size_t); */
static PyObject *f2py_rout__spropack_slansvd(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string,string,int*,int*,int*,int*,cb_saprod_in___user__routines_typedef,float*,int*,float*,float*,float*,int*,float*,float*,int*,int*,int*,float*,int*,int*,float*,int*,size_t,size_t)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    string jobu = NULL;
    int slen(jobu);
    PyObject *jobu_capi = Py_None;
    string jobv = NULL;
    int slen(jobv);
    PyObject *jobv_capi = Py_None;
    int m = 0;
    PyObject *m_capi = Py_None;
    int n = 0;
    PyObject *n_capi = Py_None;
    int k = 0;
    PyObject *k_capi = Py_None;
    int kmax = 0;
    PyObject *kmax_capi = Py_None;
    cb_saprod_in___user__routines_t aprod_cb = { Py_None, NULL, 0 };
    cb_saprod_in___user__routines_t *aprod_cb_ptr = &aprod_cb;
    PyTupleObject *aprod_xa_capi = NULL;
    cb_saprod_in___user__routines_typedef aprod_cptr;
    float *u = NULL;
    npy_intp u_Dims[2] = {-1, -1};
    const int u_Rank = 2;
    PyArrayObject *capi_u_as_array = NULL;
    int capi_u_intent = 0;
    PyObject *u_capi = Py_None;
    int ldu = 0;
    PyObject *ldu_capi = Py_None;
    float *sigma = NULL;
    npy_intp sigma_Dims[1] = {-1};
    const int sigma_Rank = 1;
    PyArrayObject *capi_sigma_as_array = NULL;
    int capi_sigma_intent = 0;
    float *bnd = NULL;
    npy_intp bnd_Dims[1] = {-1};
    const int bnd_Rank = 1;
    PyArrayObject *capi_bnd_as_array = NULL;
    int capi_bnd_intent = 0;
    float *v = NULL;
    npy_intp v_Dims[2] = {-1, -1};
    const int v_Rank = 2;
    PyArrayObject *capi_v_as_array = NULL;
    int capi_v_intent = 0;
    PyObject *v_capi = Py_None;
    int ldv = 0;
    PyObject *ldv_capi = Py_None;
    float tolin = 0;
    PyObject *tolin_capi = Py_None;
    float *work = NULL;
    npy_intp work_Dims[1] = {-1};
    const int work_Rank = 1;
    PyArrayObject *capi_work_as_array = NULL;
    int capi_work_intent = 0;
    PyObject *work_capi = Py_None;
    int lwork = 0;
    PyObject *lwork_capi = Py_None;
    int *iwork = NULL;
    npy_intp iwork_Dims[1] = {-1};
    const int iwork_Rank = 1;
    PyArrayObject *capi_iwork_as_array = NULL;
    int capi_iwork_intent = 0;
    PyObject *iwork_capi = Py_None;
    int liwork = 0;
    PyObject *liwork_capi = Py_None;
    float *doption = NULL;
    npy_intp doption_Dims[1] = {-1};
    const int doption_Rank = 1;
    PyArrayObject *capi_doption_as_array = NULL;
    int capi_doption_intent = 0;
    PyObject *doption_capi = Py_None;
    int *ioption = NULL;
    npy_intp ioption_Dims[1] = {-1};
    const int ioption_Rank = 1;
    PyArrayObject *capi_ioption_as_array = NULL;
    int capi_ioption_intent = 0;
    PyObject *ioption_capi = Py_None;
    int info = 0;
    float *dparm = NULL;
    npy_intp dparm_Dims[1] = {-1};
    const int dparm_Rank = 1;
    PyArrayObject *capi_dparm_as_array = NULL;
    int capi_dparm_intent = 0;
    PyObject *dparm_capi = Py_None;
    int *iparm = NULL;
    npy_intp iparm_Dims[1] = {-1};
    const int iparm_Rank = 1;
    PyArrayObject *capi_iparm_as_array = NULL;
    int capi_iparm_intent = 0;
    PyObject *iparm_capi = Py_None;
    static char *capi_kwlist[] = {"jobu","jobv","m","n","k","aprod","u","v","tolin","work","iwork","doption","ioption","dparm","iparm","kmax","ldu","ldv","lwork","liwork","aprod_extra_args",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOOOOOOOOO|OOOOOO!:_spropack.slansvd",\
        capi_kwlist,&jobu_capi,&jobv_capi,&m_capi,&n_capi,&k_capi,&aprod_cb.capi,&u_capi,&v_capi,&tolin_capi,&work_capi,&iwork_capi,&doption_capi,&ioption_capi,&dparm_capi,&iparm_capi,&kmax_capi,&ldu_capi,&ldv_capi,&lwork_capi,&liwork_capi,&PyTuple_Type,&aprod_xa_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable jobu */
    slen(jobu) = 1;
    f2py_success = string_from_pyobj(&jobu,&slen(jobu),"",jobu_capi,"string_from_pyobj failed in converting 1st argument`jobu' of _spropack.slansvd to C string");
    if (f2py_success) {
        STRINGPADN(jobu, slen(jobu), '\0', ' ');
    /* Processing variable jobv */
    slen(jobv) = 1;
    f2py_success = string_from_pyobj(&jobv,&slen(jobv),"",jobv_capi,"string_from_pyobj failed in converting 2nd argument`jobv' of _spropack.slansvd to C string");
    if (f2py_success) {
        STRINGPADN(jobv, slen(jobv), '\0', ' ');
    /* Processing variable m */
        f2py_success = int_from_pyobj(&m,m_capi,"_spropack.slansvd() 3rd argument (m) can't be converted to int");
    if (f2py_success) {
    /* Processing variable n */
        f2py_success = int_from_pyobj(&n,n_capi,"_spropack.slansvd() 4th argument (n) can't be converted to int");
    if (f2py_success) {
    /* Processing variable k */
        f2py_success = int_from_pyobj(&k,k_capi,"_spropack.slansvd() 5th argument (k) can't be converted to int");
    if (f2py_success) {
    /* Processing variable aprod */
if(F2PyCapsule_Check(aprod_cb.capi)) {
  aprod_cptr = F2PyCapsule_AsVoidPtr(aprod_cb.capi);
} else {
  aprod_cptr = cb_saprod_in___user__routines;
}

    if (create_cb_arglist(aprod_cb.capi,aprod_xa_capi,7,0,&aprod_cb.nofargs,&aprod_cb.args_capi,"failed in processing argument list for call-back aprod.")) {

        CFUNCSMESS("Saving callback variables for `aprod`.\n");
        aprod_cb_ptr = swap_active_cb_saprod_in___user__routines(aprod_cb_ptr);
    /* Processing variable u */
    ;
    capi_u_intent |= F2PY_INTENT_IN|F2PY_INTENT_OUT;
    const char * capi_errmess = "_spropack._spropack.slansvd: failed to create array from the 7th argument `u`";
    capi_u_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,u_Dims,u_Rank,  capi_u_intent,u_capi,capi_errmess);
    if (capi_u_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = _spropack_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        u = (float *)(PyArray_DATA(capi_u_as_array));

    /* Processing variable tolin */
        f2py_success = float_from_pyobj(&tolin,tolin_capi,"_spropack.slansvd() 9th argument (tolin) can't be converted to float");
    if (f2py_success) {
    /* Processing variable work */
    ;
    capi_work_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "_spropack._spropack.slansvd: failed to create array from the 10th argument `work`";
    capi_work_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,work_Dims,work_Rank,  capi_work_intent,work_capi,capi_errmess);
    if (capi_work_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = _spropack_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        work = (float *)(PyArray_DATA(capi_work_as_array));

    /* Processing variable iwork */
    ;
    capi_iwork_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "_spropack._spropack.slansvd: failed to create array from the 11st argument `iwork`";
    capi_iwork_as_array = ndarray_from_pyobj(  NPY_INT,1,iwork_Dims,iwork_Rank,  capi_iwork_intent,iwork_capi,capi_errmess);
    if (capi_iwork_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = _spropack_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        iwork = (int *)(PyArray_DATA(capi_iwork_as_array));

    /* Processing variable doption */
    doption_Dims[0]=3;
    capi_doption_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "_spropack._spropack.slansvd: failed to create array from the 12nd argument `doption`";
    capi_doption_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,doption_Dims,doption_Rank,  capi_doption_intent,doption_capi,capi_errmess);
    if (capi_doption_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = _spropack_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        doption = (float *)(PyArray_DATA(capi_doption_as_array));

    /* Processing variable ioption */
    ioption_Dims[0]=2;
    capi_ioption_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "_spropack._spropack.slansvd: failed to create array from the 13rd argument `ioption`";
    capi_ioption_as_array = ndarray_from_pyobj(  NPY_INT,1,ioption_Dims,ioption_Rank,  capi_ioption_intent,ioption_capi,capi_errmess);
    if (capi_ioption_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = _spropack_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        ioption = (int *)(PyArray_DATA(capi_ioption_as_array));

    /* Processing variable info */
    /* Processing variable dparm */
    ;
    capi_dparm_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "_spropack._spropack.slansvd: failed to create array from the 14th argument `dparm`";
    capi_dparm_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,dparm_Dims,dparm_Rank,  capi_dparm_intent,dparm_capi,capi_errmess);
    if (capi_dparm_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = _spropack_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        dparm = (float *)(PyArray_DATA(capi_dparm_as_array));

    /* Processing variable iparm */
    ;
    capi_iparm_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "_spropack._spropack.slansvd: failed to create array from the 15th argument `iparm`";
    capi_iparm_as_array = ndarray_from_pyobj(  NPY_INT,1,iparm_Dims,iparm_Rank,  capi_iparm_intent,iparm_capi,capi_errmess);
    if (capi_iparm_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = _spropack_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        iparm = (int *)(PyArray_DATA(capi_iparm_as_array));

    /* Processing variable kmax */
    if (kmax_capi == Py_None) kmax = -1 + shape(u, 1); else
        f2py_success = int_from_pyobj(&kmax,kmax_capi,"_spropack.slansvd() 1st keyword (kmax) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(u, 1) == 1 + kmax,"shape(u, 1) == 1 + kmax","1st keyword kmax","slansvd:kmax=%d",kmax) {
    /* Processing variable ldu */
    if (ldu_capi == Py_None) ldu = shape(u,0); else
        f2py_success = int_from_pyobj(&ldu,ldu_capi,"_spropack.slansvd() 2nd keyword (ldu) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(u,0)==ldu,"shape(u,0)==ldu","2nd keyword ldu","slansvd:ldu=%d",ldu) {
    /* Processing variable sigma */
    sigma_Dims[0]=k;
    capi_sigma_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char * capi_errmess = "_spropack._spropack.slansvd: failed to create array from the hidden `sigma`";
    capi_sigma_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,sigma_Dims,sigma_Rank,  capi_sigma_intent,Py_None,capi_errmess);
    if (capi_sigma_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = _spropack_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        sigma = (float *)(PyArray_DATA(capi_sigma_as_array));

    /* Processing variable bnd */
    bnd_Dims[0]=k;
    capi_bnd_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char * capi_errmess = "_spropack._spropack.slansvd: failed to create array from the hidden `bnd`";
    capi_bnd_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,bnd_Dims,bnd_Rank,  capi_bnd_intent,Py_None,capi_errmess);
    if (capi_bnd_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = _spropack_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        bnd = (float *)(PyArray_DATA(capi_bnd_as_array));

    /* Processing variable v */
    v_Dims[1]=kmax;
    capi_v_intent |= F2PY_INTENT_IN|F2PY_INTENT_OUT;
    const char * capi_errmess = "_spropack._spropack.slansvd: failed to create array from the 8th argument `v`";
    capi_v_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,v_Dims,v_Rank,  capi_v_intent,v_capi,capi_errmess);
    if (capi_v_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = _spropack_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        v = (float *)(PyArray_DATA(capi_v_as_array));

    /* Processing variable ldv */
    if (ldv_capi == Py_None) ldv = shape(v,0); else
        f2py_success = int_from_pyobj(&ldv,ldv_capi,"_spropack.slansvd() 3rd keyword (ldv) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(v,0)==ldv,"shape(v,0)==ldv","3rd keyword ldv","slansvd:ldv=%d",ldv) {
    /* Processing variable lwork */
    if (lwork_capi == Py_None) lwork = len(work); else
        f2py_success = int_from_pyobj(&lwork,lwork_capi,"_spropack.slansvd() 4th keyword (lwork) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(len(work)>=lwork,"len(work)>=lwork","4th keyword lwork","slansvd:lwork=%d",lwork) {
    /* Processing variable liwork */
    if (liwork_capi == Py_None) liwork = len(iwork); else
        f2py_success = int_from_pyobj(&liwork,liwork_capi,"_spropack.slansvd() 5th keyword (liwork) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(len(iwork)>=liwork,"len(iwork)>=liwork","5th keyword liwork","slansvd:liwork=%d",liwork) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        if ((setjmp(aprod_cb.jmpbuf))) {
            f2py_success = 0;
        } else {
                (*f2py_func)(jobu,jobv,&m,&n,&k,&kmax,aprod_cptr,u,&ldu,sigma,bnd,v,&ldv,&tolin,work,&lwork,iwork,&liwork,doption,ioption,&info,dparm,iparm,slen(jobu),slen(jobv));
        }
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("NNNNi",capi_u_as_array,capi_sigma_as_array,capi_bnd_as_array,capi_v_as_array,info);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*CHECKSCALAR(len(iwork)>=liwork)*/
    } /*if (f2py_success) of liwork*/
    /* End of cleaning variable liwork */
    } /*CHECKSCALAR(len(work)>=lwork)*/
    } /*if (f2py_success) of lwork*/
    /* End of cleaning variable lwork */
    } /*CHECKSCALAR(shape(v,0)==ldv)*/
    } /*if (f2py_success) of ldv*/
    /* End of cleaning variable ldv */
    }  /* if (capi_v_as_array == NULL) ... else of v */
    /* End of cleaning variable v */
    }  /* if (capi_bnd_as_array == NULL) ... else of bnd */
    /* End of cleaning variable bnd */
    }  /* if (capi_sigma_as_array == NULL) ... else of sigma */
    /* End of cleaning variable sigma */
    } /*CHECKSCALAR(shape(u,0)==ldu)*/
    } /*if (f2py_success) of ldu*/
    /* End of cleaning variable ldu */
    } /*CHECKSCALAR(shape(u, 1) == 1 + kmax)*/
    } /*if (f2py_success) of kmax*/
    /* End of cleaning variable kmax */
    if((PyObject *)capi_iparm_as_array!=iparm_capi) {
        Py_XDECREF(capi_iparm_as_array); }
    }  /* if (capi_iparm_as_array == NULL) ... else of iparm */
    /* End of cleaning variable iparm */
    if((PyObject *)capi_dparm_as_array!=dparm_capi) {
        Py_XDECREF(capi_dparm_as_array); }
    }  /* if (capi_dparm_as_array == NULL) ... else of dparm */
    /* End of cleaning variable dparm */
    /* End of cleaning variable info */
    if((PyObject *)capi_ioption_as_array!=ioption_capi) {
        Py_XDECREF(capi_ioption_as_array); }
    }  /* if (capi_ioption_as_array == NULL) ... else of ioption */
    /* End of cleaning variable ioption */
    if((PyObject *)capi_doption_as_array!=doption_capi) {
        Py_XDECREF(capi_doption_as_array); }
    }  /* if (capi_doption_as_array == NULL) ... else of doption */
    /* End of cleaning variable doption */
    if((PyObject *)capi_iwork_as_array!=iwork_capi) {
        Py_XDECREF(capi_iwork_as_array); }
    }  /* if (capi_iwork_as_array == NULL) ... else of iwork */
    /* End of cleaning variable iwork */
    if((PyObject *)capi_work_as_array!=work_capi) {
        Py_XDECREF(capi_work_as_array); }
    }  /* if (capi_work_as_array == NULL) ... else of work */
    /* End of cleaning variable work */
    } /*if (f2py_success) of tolin*/
    /* End of cleaning variable tolin */
    }  /* if (capi_u_as_array == NULL) ... else of u */
    /* End of cleaning variable u */
        CFUNCSMESS("Restoring callback variables for `aprod`.\n");
        aprod_cb_ptr = swap_active_cb_saprod_in___user__routines(aprod_cb_ptr);
        Py_DECREF(aprod_cb.args_capi);
    }
    /* End of cleaning variable aprod */
    } /*if (f2py_success) of k*/
    /* End of cleaning variable k */
    } /*if (f2py_success) of n*/
    /* End of cleaning variable n */
    } /*if (f2py_success) of m*/
    /* End of cleaning variable m */
        STRINGFREE(jobv);
    }  /*if (f2py_success) of jobv*/
    /* End of cleaning variable jobv */
        STRINGFREE(jobu);
    }  /*if (f2py_success) of jobu*/
    /* End of cleaning variable jobu */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of slansvd *******************************/

/******************************** slansvd_irl ********************************/
static char doc_f2py_rout__spropack_slansvd_irl[] = "\
u,sigma,bnd,v,info = slansvd_irl(which,jobu,jobv,m,n,p,neig,maxiter,aprod,u,v,tolin,work,iwork,doption,ioption,dparm,iparm,[dim,ldu,ldv,lwork,liwork,aprod_extra_args])\n\nWrapper for ``slansvd_irl``.\
\n\nParameters\n----------\n"
"which : input string(len=1)\n"
"jobu : input string(len=1)\n"
"jobv : input string(len=1)\n"
"m : input int\n"
"n : input int\n"
"p : input int\n"
"neig : input int\n"
"maxiter : input int\n"
"aprod : call-back function => saprod\n"
"u : input rank-2 array('f') with bounds (ldu,1 + dim)\n"
"v : input rank-2 array('f') with bounds (ldv,dim)\n"
"tolin : input float\n"
"work : input rank-1 array('f') with bounds (lwork)\n"
"iwork : input rank-1 array('i') with bounds (liwork)\n"
"doption : input rank-1 array('f') with bounds (4)\n"
"ioption : input rank-1 array('i') with bounds (2)\n"
"dparm : input rank-1 array('f') with bounds (*)\n"
"iparm : input rank-1 array('i') with bounds (*)\n"
"\nOther Parameters\n----------------\n"
"dim : input int, optional\n    Default: -1 + shape(u, 1)\n"
"aprod_extra_args : input tuple, optional\n    Default: ()\n"
"ldu : input int, optional\n    Default: shape(u,0)\n"
"ldv : input int, optional\n    Default: shape(v,0)\n"
"lwork : input int, optional\n    Default: len(work)\n"
"liwork : input int, optional\n    Default: len(iwork)\n"
"\nReturns\n-------\n"
"u : rank-2 array('f') with bounds (ldu,1 + dim)\n"
"sigma : rank-1 array('f') with bounds (neig)\n"
"bnd : rank-1 array('f') with bounds (neig)\n"
"v : rank-2 array('f') with bounds (ldv,dim)\n"
"info : int\n"
"\nNotes\n-----\nCall-back functions::\n\n"
"    def saprod(transa,m,n,x,y,dparm,iparm): return saprod\n\
    Required arguments:\n"
"        transa : input string(len=1)\n"
"        m : input int\n"
"        n : input int\n"
"        x : input rank-1 array('f') with bounds ((transa[0] == 'n'?n:m))\n"
"        y : input rank-1 array('f') with bounds ((transa[0] == 'n'?m:n))\n"
"        dparm : input rank-1 array('f') with bounds (*)\n"
"        iparm : input rank-1 array('i') with bounds (*)\n"
"    Return objects:\n"
"        saprod : float";
/* extern void F_FUNC_US(slansvd_irl,SLANSVD_IRL)(string,string,string,int*,int*,int*,int*,int*,int*,cb_saprod_in___user__routines_typedef,float*,int*,float*,float*,float*,int*,float*,float*,int*,int*,int*,float*,int*,int*,float*,int*,size_t,size_t,size_t); */
static PyObject *f2py_rout__spropack_slansvd_irl(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string,string,string,int*,int*,int*,int*,int*,int*,cb_saprod_in___user__routines_typedef,float*,int*,float*,float*,float*,int*,float*,float*,int*,int*,int*,float*,int*,int*,float*,int*,size_t,size_t,size_t)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    string which = NULL;
    int slen(which);
    PyObject *which_capi = Py_None;
    string jobu = NULL;
    int slen(jobu);
    PyObject *jobu_capi = Py_None;
    string jobv = NULL;
    int slen(jobv);
    PyObject *jobv_capi = Py_None;
    int m = 0;
    PyObject *m_capi = Py_None;
    int n = 0;
    PyObject *n_capi = Py_None;
    int dim = 0;
    PyObject *dim_capi = Py_None;
    int p = 0;
    PyObject *p_capi = Py_None;
    int neig = 0;
    PyObject *neig_capi = Py_None;
    int maxiter = 0;
    PyObject *maxiter_capi = Py_None;
    cb_saprod_in___user__routines_t aprod_cb = { Py_None, NULL, 0 };
    cb_saprod_in___user__routines_t *aprod_cb_ptr = &aprod_cb;
    PyTupleObject *aprod_xa_capi = NULL;
    cb_saprod_in___user__routines_typedef aprod_cptr;
    float *u = NULL;
    npy_intp u_Dims[2] = {-1, -1};
    const int u_Rank = 2;
    PyArrayObject *capi_u_as_array = NULL;
    int capi_u_intent = 0;
    PyObject *u_capi = Py_None;
    int ldu = 0;
    PyObject *ldu_capi = Py_None;
    float *sigma = NULL;
    npy_intp sigma_Dims[1] = {-1};
    const int sigma_Rank = 1;
    PyArrayObject *capi_sigma_as_array = NULL;
    int capi_sigma_intent = 0;
    float *bnd = NULL;
    npy_intp bnd_Dims[1] = {-1};
    const int bnd_Rank = 1;
    PyArrayObject *capi_bnd_as_array = NULL;
    int capi_bnd_intent = 0;
    float *v = NULL;
    npy_intp v_Dims[2] = {-1, -1};
    const int v_Rank = 2;
    PyArrayObject *capi_v_as_array = NULL;
    int capi_v_intent = 0;
    PyObject *v_capi = Py_None;
    int ldv = 0;
    PyObject *ldv_capi = Py_None;
    float tolin = 0;
    PyObject *tolin_capi = Py_None;
    float *work = NULL;
    npy_intp work_Dims[1] = {-1};
    const int work_Rank = 1;
    PyArrayObject *capi_work_as_array = NULL;
    int capi_work_intent = 0;
    PyObject *work_capi = Py_None;
    int lwork = 0;
    PyObject *lwork_capi = Py_None;
    int *iwork = NULL;
    npy_intp iwork_Dims[1] = {-1};
    const int iwork_Rank = 1;
    PyArrayObject *capi_iwork_as_array = NULL;
    int capi_iwork_intent = 0;
    PyObject *iwork_capi = Py_None;
    int liwork = 0;
    PyObject *liwork_capi = Py_None;
    float *doption = NULL;
    npy_intp doption_Dims[1] = {-1};
    const int doption_Rank = 1;
    PyArrayObject *capi_doption_as_array = NULL;
    int capi_doption_intent = 0;
    PyObject *doption_capi = Py_None;
    int *ioption = NULL;
    npy_intp ioption_Dims[1] = {-1};
    const int ioption_Rank = 1;
    PyArrayObject *capi_ioption_as_array = NULL;
    int capi_ioption_intent = 0;
    PyObject *ioption_capi = Py_None;
    int info = 0;
    float *dparm = NULL;
    npy_intp dparm_Dims[1] = {-1};
    const int dparm_Rank = 1;
    PyArrayObject *capi_dparm_as_array = NULL;
    int capi_dparm_intent = 0;
    PyObject *dparm_capi = Py_None;
    int *iparm = NULL;
    npy_intp iparm_Dims[1] = {-1};
    const int iparm_Rank = 1;
    PyArrayObject *capi_iparm_as_array = NULL;
    int capi_iparm_intent = 0;
    PyObject *iparm_capi = Py_None;
    static char *capi_kwlist[] = {"which","jobu","jobv","m","n","p","neig","maxiter","aprod","u","v","tolin","work","iwork","doption","ioption","dparm","iparm","dim","ldu","ldv","lwork","liwork","aprod_extra_args",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOOOOOOOOOOOO|OOOOOO!:_spropack.slansvd_irl",\
        capi_kwlist,&which_capi,&jobu_capi,&jobv_capi,&m_capi,&n_capi,&p_capi,&neig_capi,&maxiter_capi,&aprod_cb.capi,&u_capi,&v_capi,&tolin_capi,&work_capi,&iwork_capi,&doption_capi,&ioption_capi,&dparm_capi,&iparm_capi,&dim_capi,&ldu_capi,&ldv_capi,&lwork_capi,&liwork_capi,&PyTuple_Type,&aprod_xa_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable which */
    slen(which) = 1;
    f2py_success = string_from_pyobj(&which,&slen(which),"",which_capi,"string_from_pyobj failed in converting 1st argument`which' of _spropack.slansvd_irl to C string");
    if (f2py_success) {
        STRINGPADN(which, slen(which), '\0', ' ');
    /* Processing variable jobu */
    slen(jobu) = 1;
    f2py_success = string_from_pyobj(&jobu,&slen(jobu),"",jobu_capi,"string_from_pyobj failed in converting 2nd argument`jobu' of _spropack.slansvd_irl to C string");
    if (f2py_success) {
        STRINGPADN(jobu, slen(jobu), '\0', ' ');
    /* Processing variable jobv */
    slen(jobv) = 1;
    f2py_success = string_from_pyobj(&jobv,&slen(jobv),"",jobv_capi,"string_from_pyobj failed in converting 3rd argument`jobv' of _spropack.slansvd_irl to C string");
    if (f2py_success) {
        STRINGPADN(jobv, slen(jobv), '\0', ' ');
    /* Processing variable m */
        f2py_success = int_from_pyobj(&m,m_capi,"_spropack.slansvd_irl() 4th argument (m) can't be converted to int");
    if (f2py_success) {
    /* Processing variable n */
        f2py_success = int_from_pyobj(&n,n_capi,"_spropack.slansvd_irl() 5th argument (n) can't be converted to int");
    if (f2py_success) {
    /* Processing variable p */
        f2py_success = int_from_pyobj(&p,p_capi,"_spropack.slansvd_irl() 6th argument (p) can't be converted to int");
    if (f2py_success) {
    /* Processing variable neig */
        f2py_success = int_from_pyobj(&neig,neig_capi,"_spropack.slansvd_irl() 7th argument (neig) can't be converted to int");
    if (f2py_success) {
    /* Processing variable maxiter */
        f2py_success = int_from_pyobj(&maxiter,maxiter_capi,"_spropack.slansvd_irl() 8th argument (maxiter) can't be converted to int");
    if (f2py_success) {
    /* Processing variable aprod */
if(F2PyCapsule_Check(aprod_cb.capi)) {
  aprod_cptr = F2PyCapsule_AsVoidPtr(aprod_cb.capi);
} else {
  aprod_cptr = cb_saprod_in___user__routines;
}

    if (create_cb_arglist(aprod_cb.capi,aprod_xa_capi,7,0,&aprod_cb.nofargs,&aprod_cb.args_capi,"failed in processing argument list for call-back aprod.")) {

        CFUNCSMESS("Saving callback variables for `aprod`.\n");
        aprod_cb_ptr = swap_active_cb_saprod_in___user__routines(aprod_cb_ptr);
    /* Processing variable u */
    ;
    capi_u_intent |= F2PY_INTENT_IN|F2PY_INTENT_OUT;
    const char * capi_errmess = "_spropack._spropack.slansvd_irl: failed to create array from the 10th argument `u`";
    capi_u_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,u_Dims,u_Rank,  capi_u_intent,u_capi,capi_errmess);
    if (capi_u_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = _spropack_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        u = (float *)(PyArray_DATA(capi_u_as_array));

    /* Processing variable tolin */
        f2py_success = float_from_pyobj(&tolin,tolin_capi,"_spropack.slansvd_irl() 12nd argument (tolin) can't be converted to float");
    if (f2py_success) {
    /* Processing variable work */
    ;
    capi_work_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "_spropack._spropack.slansvd_irl: failed to create array from the 13rd argument `work`";
    capi_work_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,work_Dims,work_Rank,  capi_work_intent,work_capi,capi_errmess);
    if (capi_work_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = _spropack_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        work = (float *)(PyArray_DATA(capi_work_as_array));

    /* Processing variable iwork */
    ;
    capi_iwork_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "_spropack._spropack.slansvd_irl: failed to create array from the 14th argument `iwork`";
    capi_iwork_as_array = ndarray_from_pyobj(  NPY_INT,1,iwork_Dims,iwork_Rank,  capi_iwork_intent,iwork_capi,capi_errmess);
    if (capi_iwork_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = _spropack_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        iwork = (int *)(PyArray_DATA(capi_iwork_as_array));

    /* Processing variable doption */
    doption_Dims[0]=4;
    capi_doption_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "_spropack._spropack.slansvd_irl: failed to create array from the 15th argument `doption`";
    capi_doption_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,doption_Dims,doption_Rank,  capi_doption_intent,doption_capi,capi_errmess);
    if (capi_doption_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = _spropack_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        doption = (float *)(PyArray_DATA(capi_doption_as_array));

    /* Processing variable ioption */
    ioption_Dims[0]=2;
    capi_ioption_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "_spropack._spropack.slansvd_irl: failed to create array from the 16th argument `ioption`";
    capi_ioption_as_array = ndarray_from_pyobj(  NPY_INT,1,ioption_Dims,ioption_Rank,  capi_ioption_intent,ioption_capi,capi_errmess);
    if (capi_ioption_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = _spropack_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        ioption = (int *)(PyArray_DATA(capi_ioption_as_array));

    /* Processing variable info */
    /* Processing variable dparm */
    ;
    capi_dparm_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "_spropack._spropack.slansvd_irl: failed to create array from the 17th argument `dparm`";
    capi_dparm_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,dparm_Dims,dparm_Rank,  capi_dparm_intent,dparm_capi,capi_errmess);
    if (capi_dparm_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = _spropack_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        dparm = (float *)(PyArray_DATA(capi_dparm_as_array));

    /* Processing variable iparm */
    ;
    capi_iparm_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "_spropack._spropack.slansvd_irl: failed to create array from the 18th argument `iparm`";
    capi_iparm_as_array = ndarray_from_pyobj(  NPY_INT,1,iparm_Dims,iparm_Rank,  capi_iparm_intent,iparm_capi,capi_errmess);
    if (capi_iparm_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = _spropack_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        iparm = (int *)(PyArray_DATA(capi_iparm_as_array));

    /* Processing variable dim */
    if (dim_capi == Py_None) dim = -1 + shape(u, 1); else
        f2py_success = int_from_pyobj(&dim,dim_capi,"_spropack.slansvd_irl() 1st keyword (dim) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(u, 1) == 1 + dim,"shape(u, 1) == 1 + dim","1st keyword dim","slansvd_irl:dim=%d",dim) {
    /* Processing variable ldu */
    if (ldu_capi == Py_None) ldu = shape(u,0); else
        f2py_success = int_from_pyobj(&ldu,ldu_capi,"_spropack.slansvd_irl() 2nd keyword (ldu) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(u,0)==ldu,"shape(u,0)==ldu","2nd keyword ldu","slansvd_irl:ldu=%d",ldu) {
    /* Processing variable sigma */
    sigma_Dims[0]=neig;
    capi_sigma_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char * capi_errmess = "_spropack._spropack.slansvd_irl: failed to create array from the hidden `sigma`";
    capi_sigma_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,sigma_Dims,sigma_Rank,  capi_sigma_intent,Py_None,capi_errmess);
    if (capi_sigma_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = _spropack_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        sigma = (float *)(PyArray_DATA(capi_sigma_as_array));

    /* Processing variable bnd */
    bnd_Dims[0]=neig;
    capi_bnd_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char * capi_errmess = "_spropack._spropack.slansvd_irl: failed to create array from the hidden `bnd`";
    capi_bnd_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,bnd_Dims,bnd_Rank,  capi_bnd_intent,Py_None,capi_errmess);
    if (capi_bnd_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = _spropack_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        bnd = (float *)(PyArray_DATA(capi_bnd_as_array));

    /* Processing variable v */
    v_Dims[1]=dim;
    capi_v_intent |= F2PY_INTENT_IN|F2PY_INTENT_OUT;
    const char * capi_errmess = "_spropack._spropack.slansvd_irl: failed to create array from the 11st argument `v`";
    capi_v_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,v_Dims,v_Rank,  capi_v_intent,v_capi,capi_errmess);
    if (capi_v_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = _spropack_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        v = (float *)(PyArray_DATA(capi_v_as_array));

    /* Processing variable ldv */
    if (ldv_capi == Py_None) ldv = shape(v,0); else
        f2py_success = int_from_pyobj(&ldv,ldv_capi,"_spropack.slansvd_irl() 3rd keyword (ldv) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(v,0)==ldv,"shape(v,0)==ldv","3rd keyword ldv","slansvd_irl:ldv=%d",ldv) {
    /* Processing variable lwork */
    if (lwork_capi == Py_None) lwork = len(work); else
        f2py_success = int_from_pyobj(&lwork,lwork_capi,"_spropack.slansvd_irl() 4th keyword (lwork) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(len(work)>=lwork,"len(work)>=lwork","4th keyword lwork","slansvd_irl:lwork=%d",lwork) {
    /* Processing variable liwork */
    if (liwork_capi == Py_None) liwork = len(iwork); else
        f2py_success = int_from_pyobj(&liwork,liwork_capi,"_spropack.slansvd_irl() 5th keyword (liwork) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(len(iwork)>=liwork,"len(iwork)>=liwork","5th keyword liwork","slansvd_irl:liwork=%d",liwork) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        if ((setjmp(aprod_cb.jmpbuf))) {
            f2py_success = 0;
        } else {
                (*f2py_func)(which,jobu,jobv,&m,&n,&dim,&p,&neig,&maxiter,aprod_cptr,u,&ldu,sigma,bnd,v,&ldv,&tolin,work,&lwork,iwork,&liwork,doption,ioption,&info,dparm,iparm,slen(which),slen(jobu),slen(jobv));
        }
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("NNNNi",capi_u_as_array,capi_sigma_as_array,capi_bnd_as_array,capi_v_as_array,info);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*CHECKSCALAR(len(iwork)>=liwork)*/
    } /*if (f2py_success) of liwork*/
    /* End of cleaning variable liwork */
    } /*CHECKSCALAR(len(work)>=lwork)*/
    } /*if (f2py_success) of lwork*/
    /* End of cleaning variable lwork */
    } /*CHECKSCALAR(shape(v,0)==ldv)*/
    } /*if (f2py_success) of ldv*/
    /* End of cleaning variable ldv */
    }  /* if (capi_v_as_array == NULL) ... else of v */
    /* End of cleaning variable v */
    }  /* if (capi_bnd_as_array == NULL) ... else of bnd */
    /* End of cleaning variable bnd */
    }  /* if (capi_sigma_as_array == NULL) ... else of sigma */
    /* End of cleaning variable sigma */
    } /*CHECKSCALAR(shape(u,0)==ldu)*/
    } /*if (f2py_success) of ldu*/
    /* End of cleaning variable ldu */
    } /*CHECKSCALAR(shape(u, 1) == 1 + dim)*/
    } /*if (f2py_success) of dim*/
    /* End of cleaning variable dim */
    if((PyObject *)capi_iparm_as_array!=iparm_capi) {
        Py_XDECREF(capi_iparm_as_array); }
    }  /* if (capi_iparm_as_array == NULL) ... else of iparm */
    /* End of cleaning variable iparm */
    if((PyObject *)capi_dparm_as_array!=dparm_capi) {
        Py_XDECREF(capi_dparm_as_array); }
    }  /* if (capi_dparm_as_array == NULL) ... else of dparm */
    /* End of cleaning variable dparm */
    /* End of cleaning variable info */
    if((PyObject *)capi_ioption_as_array!=ioption_capi) {
        Py_XDECREF(capi_ioption_as_array); }
    }  /* if (capi_ioption_as_array == NULL) ... else of ioption */
    /* End of cleaning variable ioption */
    if((PyObject *)capi_doption_as_array!=doption_capi) {
        Py_XDECREF(capi_doption_as_array); }
    }  /* if (capi_doption_as_array == NULL) ... else of doption */
    /* End of cleaning variable doption */
    if((PyObject *)capi_iwork_as_array!=iwork_capi) {
        Py_XDECREF(capi_iwork_as_array); }
    }  /* if (capi_iwork_as_array == NULL) ... else of iwork */
    /* End of cleaning variable iwork */
    if((PyObject *)capi_work_as_array!=work_capi) {
        Py_XDECREF(capi_work_as_array); }
    }  /* if (capi_work_as_array == NULL) ... else of work */
    /* End of cleaning variable work */
    } /*if (f2py_success) of tolin*/
    /* End of cleaning variable tolin */
    }  /* if (capi_u_as_array == NULL) ... else of u */
    /* End of cleaning variable u */
        CFUNCSMESS("Restoring callback variables for `aprod`.\n");
        aprod_cb_ptr = swap_active_cb_saprod_in___user__routines(aprod_cb_ptr);
        Py_DECREF(aprod_cb.args_capi);
    }
    /* End of cleaning variable aprod */
    } /*if (f2py_success) of maxiter*/
    /* End of cleaning variable maxiter */
    } /*if (f2py_success) of neig*/
    /* End of cleaning variable neig */
    } /*if (f2py_success) of p*/
    /* End of cleaning variable p */
    } /*if (f2py_success) of n*/
    /* End of cleaning variable n */
    } /*if (f2py_success) of m*/
    /* End of cleaning variable m */
        STRINGFREE(jobv);
    }  /*if (f2py_success) of jobv*/
    /* End of cleaning variable jobv */
        STRINGFREE(jobu);
    }  /*if (f2py_success) of jobu*/
    /* End of cleaning variable jobu */
        STRINGFREE(which);
    }  /*if (f2py_success) of which*/
    /* End of cleaning variable which */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************************** end of slansvd_irl *****************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

static FortranDataDef f2py_timing_def[] = {
  {"nopx",0,{{-1}},NPY_INT, 1},
  {"nreorth",0,{{-1}},NPY_INT, 1},
  {"ndot",0,{{-1}},NPY_INT, 1},
  {"nreorthu",0,{{-1}},NPY_INT, 1},
  {"nreorthv",0,{{-1}},NPY_INT, 1},
  {"nitref",0,{{-1}},NPY_INT, 1},
  {"nrestart",0,{{-1}},NPY_INT, 1},
  {"nbsvd",0,{{-1}},NPY_INT, 1},
  {"tmvopx",0,{{-1}},NPY_FLOAT, 1},
  {"tgetu0",0,{{-1}},NPY_FLOAT, 1},
  {"tupdmu",0,{{-1}},NPY_FLOAT, 1},
  {"tupdnu",0,{{-1}},NPY_FLOAT, 1},
  {"tintv",0,{{-1}},NPY_FLOAT, 1},
  {"tlanbpro",0,{{-1}},NPY_FLOAT, 1},
  {"treorth",0,{{-1}},NPY_FLOAT, 1},
  {"treorthu",0,{{-1}},NPY_FLOAT, 1},
  {"treorthv",0,{{-1}},NPY_FLOAT, 1},
  {"telru",0,{{-1}},NPY_FLOAT, 1},
  {"telrv",0,{{-1}},NPY_FLOAT, 1},
  {"tbsvd",0,{{-1}},NPY_FLOAT, 1},
  {"tnorm2",0,{{-1}},NPY_FLOAT, 1},
  {"tlansvd",0,{{-1}},NPY_FLOAT, 1},
  {"nlandim",0,{{-1}},NPY_INT, 1},
  {"tritzvec",0,{{-1}},NPY_FLOAT, 1},
  {"trestart",0,{{-1}},NPY_FLOAT, 1},
  {"tdot",0,{{-1}},NPY_FLOAT, 1},
  {"nsing",0,{{-1}},NPY_INT, 1},
  {NULL}
};
static void f2py_setup_timing(char *nopx,char *nreorth,char *ndot,char *nreorthu,char *nreorthv,char *nitref,char *nrestart,char *nbsvd,char *tmvopx,char *tgetu0,char *tupdmu,char *tupdnu,char *tintv,char *tlanbpro,char *treorth,char *treorthu,char *treorthv,char *telru,char *telrv,char *tbsvd,char *tnorm2,char *tlansvd,char *nlandim,char *tritzvec,char *trestart,char *tdot,char *nsing) {
  int i_f2py=0;
  f2py_timing_def[i_f2py++].data = nopx;
  f2py_timing_def[i_f2py++].data = nreorth;
  f2py_timing_def[i_f2py++].data = ndot;
  f2py_timing_def[i_f2py++].data = nreorthu;
  f2py_timing_def[i_f2py++].data = nreorthv;
  f2py_timing_def[i_f2py++].data = nitref;
  f2py_timing_def[i_f2py++].data = nrestart;
  f2py_timing_def[i_f2py++].data = nbsvd;
  f2py_timing_def[i_f2py++].data = tmvopx;
  f2py_timing_def[i_f2py++].data = tgetu0;
  f2py_timing_def[i_f2py++].data = tupdmu;
  f2py_timing_def[i_f2py++].data = tupdnu;
  f2py_timing_def[i_f2py++].data = tintv;
  f2py_timing_def[i_f2py++].data = tlanbpro;
  f2py_timing_def[i_f2py++].data = treorth;
  f2py_timing_def[i_f2py++].data = treorthu;
  f2py_timing_def[i_f2py++].data = treorthv;
  f2py_timing_def[i_f2py++].data = telru;
  f2py_timing_def[i_f2py++].data = telrv;
  f2py_timing_def[i_f2py++].data = tbsvd;
  f2py_timing_def[i_f2py++].data = tnorm2;
  f2py_timing_def[i_f2py++].data = tlansvd;
  f2py_timing_def[i_f2py++].data = nlandim;
  f2py_timing_def[i_f2py++].data = tritzvec;
  f2py_timing_def[i_f2py++].data = trestart;
  f2py_timing_def[i_f2py++].data = tdot;
  f2py_timing_def[i_f2py++].data = nsing;
}
extern void F_FUNC(f2pyinittiming,F2PYINITTIMING)(void(*)(char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*));
static void f2py_init_timing(void) {
  F_FUNC(f2pyinittiming,F2PYINITTIMING)(f2py_setup_timing);
}

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
    {"slansvd",-1,{{-1}},0,0,(char *)  F_FUNC(slansvd,SLANSVD),  (f2py_init_func)f2py_rout__spropack_slansvd,doc_f2py_rout__spropack_slansvd},
    {"slansvd_irl",-1,{{-1}},0,0,(char *)  F_FUNC_US(slansvd_irl,SLANSVD_IRL),  (f2py_init_func)f2py_rout__spropack_slansvd_irl,doc_f2py_rout__spropack_slansvd_irl},

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "_spropack",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit__spropack(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = _spropack_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module _spropack (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("1.26.4");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module '_spropack' is auto-generated with f2py (version:1.26.4).\nFunctions:\n"
"    u,sigma,bnd,v,info = slansvd(jobu,jobv,m,n,k,aprod,u,v,tolin,work,iwork,doption,ioption,dparm,iparm,kmax=-1 + shape(u, 1),ldu=shape(u,0),ldv=shape(v,0),lwork=len(work),liwork=len(iwork),aprod_extra_args=())\n"
"    u,sigma,bnd,v,info = slansvd_irl(which,jobu,jobv,m,n,p,neig,maxiter,aprod,u,v,tolin,work,iwork,doption,ioption,dparm,iparm,dim=-1 + shape(u, 1),ldu=shape(u,0),ldv=shape(v,0),lwork=len(work),liwork=len(iwork),aprod_extra_args=())\n"
"COMMON blocks:\n""  /timing/ nopx,nreorth,ndot,nreorthu,nreorthv,nitref,nrestart,nbsvd,tmvopx,tgetu0,tupdmu,tupdnu,tintv,tlanbpro,treorth,treorthu,treorthv,telru,telrv,tbsvd,tnorm2,tlansvd,nlandim,tritzvec,trestart,tdot,nsing\n"".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("1.26.4");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    _spropack_error = PyErr_NewException ("_spropack.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "__spropack_error", _spropack_error);
    Py_DECREF(_spropack_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }


/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

  tmp = PyFortranObject_New(f2py_timing_def,f2py_init_timing);
  if (tmp == NULL) return NULL;
  if (F2PyDict_SetItemString(d, "timing", tmp) == -1) return NULL;
  Py_DECREF(tmp);
/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"_spropack");
#endif
    return m;
}
#ifdef __cplusplus
}
#endif
