/* File: _cobylamodule.c
 * This file is auto-generated with f2py (version:1.26.4).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Sat Nov 18 18:32:55 2023
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
#include <setjmp.h>
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *_cobyla_error;
static PyObject *_cobyla_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
typedef void(*cb_callback_in__cobyla__user__routines_typedef)(int *,int *,double *);
typedef void(*cb_calcfc_in__cobyla__user__routines_typedef)(int *,int *,double *,double *,double *);

/********************** See f2py2e/cfuncs.py: cppmacros **********************/

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


#define PRINTPYOBJERR(obj)\
    fprintf(stderr,"_cobyla.error is related to ");\
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");


#define GETSCALARFROMPYTUPLE(tuple,index,var,ctype,mess) {\
        if ((capi_tmp = PyTuple_GetItem((tuple),(index)))==NULL) goto capi_fail;\
        if (!(ctype ## _from_pyobj((var),capi_tmp,mess)))\
            goto capi_fail;\
    }


#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif


#ifndef F2PY_THREAD_LOCAL_DECL
#if defined(_MSC_VER)
#define F2PY_THREAD_LOCAL_DECL __declspec(thread)
#elif defined(NPY_OS_MINGW)
#define F2PY_THREAD_LOCAL_DECL __thread
#elif defined(__STDC_VERSION__) \
      && (__STDC_VERSION__ >= 201112L) \
      && !defined(__STDC_NO_THREADS__) \
      && (!defined(__GLIBC__) || __GLIBC__ > 2 || (__GLIBC__ == 2 && __GLIBC_MINOR__ > 12)) \
      && !defined(NPY_OS_OPENBSD) && !defined(NPY_OS_HAIKU)
/* __STDC_NO_THREADS__ was first defined in a maintenance release of glibc 2.12,
   see https://lists.gnu.org/archive/html/commit-hurd/2012-07/msg00180.html,
   so `!defined(__STDC_NO_THREADS__)` may give false positive for the existence
   of `threads.h` when using an older release of glibc 2.12
   See gh-19437 for details on OpenBSD */
#include <threads.h>
#define F2PY_THREAD_LOCAL_DECL thread_local
#elif defined(__GNUC__) \
      && (__GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ >= 4)))
#define F2PY_THREAD_LOCAL_DECL __thread
#endif
#endif


#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/* See fortranobject.h for definitions. The macros here are provided for BC. */
#define rank f2py_rank
#define shape f2py_shape
#define fshape f2py_shape
#define len f2py_len
#define flen f2py_flen
#define slen f2py_slen
#define size f2py_size


#define SWAP(a,b,t) {\
    t *c;\
    c = a;\
    a = b;\
    b = c;}


#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(_cobyla_error,errstring);\
        /*goto capi_fail;*/\
    } else 

/************************ See f2py2e/cfuncs.py: cfuncs ************************/

static int
double_from_pyobj(double* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
        *v = PyFloat_AsDouble(obj);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    tmp = PyNumber_Float(obj);
    if (tmp) {
        *v = PyFloat_AsDouble(tmp);
        Py_DECREF(tmp);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = _cobyla_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


static int
create_cb_arglist(PyObject* fun, PyTupleObject* xa , const int maxnofargs,
                  const int nofoptargs, int *nofargs, PyTupleObject **args,
                  const char *errmess)
{
    PyObject *tmp = NULL;
    PyObject *tmp_fun = NULL;
    Py_ssize_t tot, opt, ext, siz, i, di = 0;
    CFUNCSMESS("create_cb_arglist\n");
    tot=opt=ext=siz=0;
    /* Get the total number of arguments */
    if (PyFunction_Check(fun)) {
        tmp_fun = fun;
        Py_INCREF(tmp_fun);
    }
    else {
        di = 1;
        if (PyObject_HasAttrString(fun,"im_func")) {
            tmp_fun = PyObject_GetAttrString(fun,"im_func");
        }
        else if (PyObject_HasAttrString(fun,"__call__")) {
            tmp = PyObject_GetAttrString(fun,"__call__");
            if (PyObject_HasAttrString(tmp,"im_func"))
                tmp_fun = PyObject_GetAttrString(tmp,"im_func");
            else {
                tmp_fun = fun; /* built-in function */
                Py_INCREF(tmp_fun);
                tot = maxnofargs;
                if (PyCFunction_Check(fun)) {
                    /* In case the function has a co_argcount (like on PyPy) */
                    di = 0;
                }
                if (xa != NULL)
                    tot += PyTuple_Size((PyObject *)xa);
            }
            Py_XDECREF(tmp);
        }
        else if (PyFortran_Check(fun) || PyFortran_Check1(fun)) {
            tot = maxnofargs;
            if (xa != NULL)
                tot += PyTuple_Size((PyObject *)xa);
            tmp_fun = fun;
            Py_INCREF(tmp_fun);
        }
        else if (F2PyCapsule_Check(fun)) {
            tot = maxnofargs;
            if (xa != NULL)
                ext = PyTuple_Size((PyObject *)xa);
            if(ext>0) {
                fprintf(stderr,"extra arguments tuple cannot be used with PyCapsule call-back\n");
                goto capi_fail;
            }
            tmp_fun = fun;
            Py_INCREF(tmp_fun);
        }
    }

    if (tmp_fun == NULL) {
        fprintf(stderr,
                "Call-back argument must be function|instance|instance.__call__|f2py-function "
                "but got %s.\n",
                ((fun == NULL) ? "NULL" : Py_TYPE(fun)->tp_name));
        goto capi_fail;
    }

    if (PyObject_HasAttrString(tmp_fun,"__code__")) {
        if (PyObject_HasAttrString(tmp = PyObject_GetAttrString(tmp_fun,"__code__"),"co_argcount")) {
            PyObject *tmp_argcount = PyObject_GetAttrString(tmp,"co_argcount");
            Py_DECREF(tmp);
            if (tmp_argcount == NULL) {
                goto capi_fail;
            }
            tot = PyLong_AsSsize_t(tmp_argcount) - di;
            Py_DECREF(tmp_argcount);
        }
    }
    /* Get the number of optional arguments */
    if (PyObject_HasAttrString(tmp_fun,"__defaults__")) {
        if (PyTuple_Check(tmp = PyObject_GetAttrString(tmp_fun,"__defaults__")))
            opt = PyTuple_Size(tmp);
        Py_XDECREF(tmp);
    }
    /* Get the number of extra arguments */
    if (xa != NULL)
        ext = PyTuple_Size((PyObject *)xa);
    /* Calculate the size of call-backs argument list */
    siz = MIN(maxnofargs+ext,tot);
    *nofargs = MAX(0,siz-ext);

#ifdef DEBUGCFUNCS
    fprintf(stderr,
            "debug-capi:create_cb_arglist:maxnofargs(-nofoptargs),"
            "tot,opt,ext,siz,nofargs = %d(-%d), %zd, %zd, %zd, %zd, %d\n",
            maxnofargs, nofoptargs, tot, opt, ext, siz, *nofargs);
#endif

    if (siz < tot-opt) {
        fprintf(stderr,
                "create_cb_arglist: Failed to build argument list "
                "(siz) with enough arguments (tot-opt) required by "
                "user-supplied function (siz,tot,opt=%zd, %zd, %zd).\n",
                siz, tot, opt);
        goto capi_fail;
    }

    /* Initialize argument list */
    *args = (PyTupleObject *)PyTuple_New(siz);
    for (i=0;i<*nofargs;i++) {
        Py_INCREF(Py_None);
        PyTuple_SET_ITEM((PyObject *)(*args),i,Py_None);
    }
    if (xa != NULL)
        for (i=(*nofargs);i<siz;i++) {
            tmp = PyTuple_GetItem((PyObject *)xa,i-(*nofargs));
            Py_INCREF(tmp);
            PyTuple_SET_ITEM(*args,i,tmp);
        }
    CFUNCSMESS("create_cb_arglist-end\n");
    Py_DECREF(tmp_fun);
    return 1;

capi_fail:
    if (PyErr_Occurred() == NULL)
        PyErr_SetString(_cobyla_error, errmess);
    Py_XDECREF(tmp_fun);
    return 0;
}


static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }

    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = _cobyla_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(cobyla ,COBYLA )(cb_calcfc_in__cobyla__user__routines_typedef,int*,int*,double*,double*,double*,int*,int*,double*,int*,double*,cb_callback_in__cobyla__user__routines_typedef);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/

/******************** cb_calcfc_in__cobyla__user__routines ********************/
typedef struct {
    PyObject *capi;
    PyTupleObject *args_capi;
    int nofargs;
    jmp_buf jmpbuf;
} cb_calcfc_in__cobyla__user__routines_t;

#if defined(F2PY_THREAD_LOCAL_DECL) && !defined(F2PY_USE_PYTHON_TLS)

static F2PY_THREAD_LOCAL_DECL cb_calcfc_in__cobyla__user__routines_t *_active_cb_calcfc_in__cobyla__user__routines = NULL;

static cb_calcfc_in__cobyla__user__routines_t *swap_active_cb_calcfc_in__cobyla__user__routines(cb_calcfc_in__cobyla__user__routines_t *ptr) {
    cb_calcfc_in__cobyla__user__routines_t *prev = _active_cb_calcfc_in__cobyla__user__routines;
    _active_cb_calcfc_in__cobyla__user__routines = ptr;
    return prev;
}

static cb_calcfc_in__cobyla__user__routines_t *get_active_cb_calcfc_in__cobyla__user__routines(void) {
    return _active_cb_calcfc_in__cobyla__user__routines;
}

#else

static cb_calcfc_in__cobyla__user__routines_t *swap_active_cb_calcfc_in__cobyla__user__routines(cb_calcfc_in__cobyla__user__routines_t *ptr) {
    char *key = "__f2py_cb_cb_calcfc_in__cobyla__user__routines";
    return (cb_calcfc_in__cobyla__user__routines_t *)F2PySwapThreadLocalCallbackPtr(key, ptr);
}

static cb_calcfc_in__cobyla__user__routines_t *get_active_cb_calcfc_in__cobyla__user__routines(void) {
    char *key = "__f2py_cb_cb_calcfc_in__cobyla__user__routines";
    return (cb_calcfc_in__cobyla__user__routines_t *)F2PyGetThreadLocalCallbackPtr(key);
}

#endif

/*typedef void(*cb_calcfc_in__cobyla__user__routines_typedef)(int *,int *,double *,double *,double *);*/
static void cb_calcfc_in__cobyla__user__routines (int *n_cb_capi,int *m_cb_capi,double *x,double *f_cb_capi,double *con) {
    cb_calcfc_in__cobyla__user__routines_t cb_local = { NULL, NULL, 0 };
    cb_calcfc_in__cobyla__user__routines_t *cb = NULL;
    PyTupleObject *capi_arglist = NULL;
    PyObject *capi_return = NULL;
    PyObject *capi_tmp = NULL;
    PyObject *capi_arglist_list = NULL;
    int capi_j,capi_i = 0;
    int capi_longjmp_ok = 1;
/*decl*/
    int n=(*n_cb_capi);
    int m=(*m_cb_capi);
    double f=(*f_cb_capi);
    npy_intp x_Dims[1] = {-1};
    npy_intp con_Dims[1] = {-1};
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
    cb = get_active_cb_calcfc_in__cobyla__user__routines();
    if (cb == NULL) {
        capi_longjmp_ok = 0;
        cb = &cb_local;
    }
    capi_arglist = cb->args_capi;
    CFUNCSMESS("cb:Call-back function cb_calcfc_in__cobyla__user__routines (maxnofargs=2(-0))\n");
    CFUNCSMESSPY("cb:cb_calcfc_in__cobyla__user__routines_capi=",cb->capi);
    if (cb->capi==NULL) {
        capi_longjmp_ok = 0;
        cb->capi = PyObject_GetAttrString(_cobyla_module,"calcfc");
        CFUNCSMESSPY("cb:cb_calcfc_in__cobyla__user__routines_capi=",cb->capi);
    }
    if (cb->capi==NULL) {
        PyErr_SetString(_cobyla_error,"cb: Callback calcfc not defined (as an argument or module _cobyla attribute).\n");
        goto capi_fail;
    }
    if (F2PyCapsule_Check(cb->capi)) {
    cb_calcfc_in__cobyla__user__routines_typedef cb_calcfc_in__cobyla__user__routines_cptr;
    cb_calcfc_in__cobyla__user__routines_cptr = F2PyCapsule_AsVoidPtr(cb->capi);
    (*cb_calcfc_in__cobyla__user__routines_cptr)(n_cb_capi,m_cb_capi,x,f_cb_capi,con);
    return;
    }
    if (capi_arglist==NULL) {
        capi_longjmp_ok = 0;
        capi_tmp = PyObject_GetAttrString(_cobyla_module,"calcfc_extra_args");
        if (capi_tmp) {
            capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
            Py_DECREF(capi_tmp);
            if (capi_arglist==NULL) {
                PyErr_SetString(_cobyla_error,"Failed to convert _cobyla.calcfc_extra_args to tuple.\n");
                goto capi_fail;
            }
        } else {
            PyErr_Clear();
            capi_arglist = (PyTupleObject *)Py_BuildValue("()");
        }
    }
    if (capi_arglist == NULL) {
        PyErr_SetString(_cobyla_error,"Callback calcfc argument list is not set.\n");
        goto capi_fail;
    }
/*setdims*/
    x_Dims[0]=n;
    con_Dims[0]=m;
#ifdef PYPY_VERSION
#define CAPI_ARGLIST_SETITEM(idx, value) PyList_SetItem((PyObject *)capi_arglist_list, idx, value)
    capi_arglist_list = PySequence_List(capi_arglist);
    if (capi_arglist_list == NULL) goto capi_fail;
#else
#define CAPI_ARGLIST_SETITEM(idx, value) PyTuple_SetItem((PyObject *)capi_arglist, idx, value)
#endif
/*pyobjfrom*/
    if (cb->nofargs>capi_i) {
        /* tmp_arr will be inserted to capi_arglist_list that will be
           destroyed when leaving callback function wrapper together
           with tmp_arr. */
        PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,
          1,x_Dims,NPY_DOUBLE,NULL,(char*)x,1,
          NPY_ARRAY_FARRAY,NULL);


        if (tmp_arr==NULL)
            goto capi_fail;
        if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
            goto capi_fail;
}
    if (cb->nofargs>capi_i) {
        /* tmp_arr will be inserted to capi_arglist_list that will be
           destroyed when leaving callback function wrapper together
           with tmp_arr. */
        PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,
          1,con_Dims,NPY_DOUBLE,NULL,(char*)con,1,
          NPY_ARRAY_FARRAY,NULL);


        if (tmp_arr==NULL)
            goto capi_fail;
        if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
            goto capi_fail;
}
#undef CAPI_ARGLIST_SETITEM
#ifdef PYPY_VERSION
    CFUNCSMESSPY("cb:capi_arglist=",capi_arglist_list);
#else
    CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
#endif
    CFUNCSMESS("cb:Call-back calling Python function calcfc.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
#ifdef PYPY_VERSION
    capi_return = PyObject_CallObject(cb->capi,(PyObject *)capi_arglist_list);
    Py_DECREF(capi_arglist_list);
    capi_arglist_list = NULL;
#else
    capi_return = PyObject_CallObject(cb->capi,(PyObject *)capi_arglist);
#endif
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
    CFUNCSMESSPY("cb:capi_return=",capi_return);
    if (capi_return == NULL) {
        fprintf(stderr,"capi_return is NULL\n");
        goto capi_fail;
    }
    if (capi_return == Py_None) {
        Py_DECREF(capi_return);
        capi_return = Py_BuildValue("()");
    }
    else if (!PyTuple_Check(capi_return)) {
        capi_return = Py_BuildValue("(N)",capi_return);
    }
    capi_j = PyTuple_Size(capi_return);
    capi_i = 0;
/*frompyobj*/
    if (capi_j>capi_i)
        GETSCALARFROMPYTUPLE(capi_return,capi_i++,f_cb_capi,double,"double_from_pyobj failed in converting argument f of call-back function cb_calcfc_in__cobyla__user__routines to C double\n");
    CFUNCSMESS("cb:cb_calcfc_in__cobyla__user__routines:successful\n");
    Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
    goto capi_return_pt;
capi_fail:
    fprintf(stderr,"Call-back cb_calcfc_in__cobyla__user__routines failed.\n");
    Py_XDECREF(capi_return);
    Py_XDECREF(capi_arglist_list);
    if (capi_longjmp_ok) {
        longjmp(cb->jmpbuf,-1);
    }
capi_return_pt:
    ;
return;
}
/**************** end of cb_calcfc_in__cobyla__user__routines ****************/


/******************* cb_callback_in__cobyla__user__routines *******************/
typedef struct {
    PyObject *capi;
    PyTupleObject *args_capi;
    int nofargs;
    jmp_buf jmpbuf;
} cb_callback_in__cobyla__user__routines_t;

#if defined(F2PY_THREAD_LOCAL_DECL) && !defined(F2PY_USE_PYTHON_TLS)

static F2PY_THREAD_LOCAL_DECL cb_callback_in__cobyla__user__routines_t *_active_cb_callback_in__cobyla__user__routines = NULL;

static cb_callback_in__cobyla__user__routines_t *swap_active_cb_callback_in__cobyla__user__routines(cb_callback_in__cobyla__user__routines_t *ptr) {
    cb_callback_in__cobyla__user__routines_t *prev = _active_cb_callback_in__cobyla__user__routines;
    _active_cb_callback_in__cobyla__user__routines = ptr;
    return prev;
}

static cb_callback_in__cobyla__user__routines_t *get_active_cb_callback_in__cobyla__user__routines(void) {
    return _active_cb_callback_in__cobyla__user__routines;
}

#else

static cb_callback_in__cobyla__user__routines_t *swap_active_cb_callback_in__cobyla__user__routines(cb_callback_in__cobyla__user__routines_t *ptr) {
    char *key = "__f2py_cb_cb_callback_in__cobyla__user__routines";
    return (cb_callback_in__cobyla__user__routines_t *)F2PySwapThreadLocalCallbackPtr(key, ptr);
}

static cb_callback_in__cobyla__user__routines_t *get_active_cb_callback_in__cobyla__user__routines(void) {
    char *key = "__f2py_cb_cb_callback_in__cobyla__user__routines";
    return (cb_callback_in__cobyla__user__routines_t *)F2PyGetThreadLocalCallbackPtr(key);
}

#endif

/*typedef void(*cb_callback_in__cobyla__user__routines_typedef)(int *,int *,double *);*/
static void cb_callback_in__cobyla__user__routines (int *n_cb_capi,int *m_cb_capi,double *x) {
    cb_callback_in__cobyla__user__routines_t cb_local = { NULL, NULL, 0 };
    cb_callback_in__cobyla__user__routines_t *cb = NULL;
    PyTupleObject *capi_arglist = NULL;
    PyObject *capi_return = NULL;
    PyObject *capi_tmp = NULL;
    PyObject *capi_arglist_list = NULL;
    int capi_j,capi_i = 0;
    int capi_longjmp_ok = 1;
/*decl*/
    int n=(*n_cb_capi);
    int m=(*m_cb_capi);
    npy_intp x_Dims[1] = {-1};
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
    cb = get_active_cb_callback_in__cobyla__user__routines();
    if (cb == NULL) {
        capi_longjmp_ok = 0;
        cb = &cb_local;
    }
    capi_arglist = cb->args_capi;
    CFUNCSMESS("cb:Call-back function cb_callback_in__cobyla__user__routines (maxnofargs=1(-0))\n");
    CFUNCSMESSPY("cb:cb_callback_in__cobyla__user__routines_capi=",cb->capi);
    if (cb->capi==NULL) {
        capi_longjmp_ok = 0;
        cb->capi = PyObject_GetAttrString(_cobyla_module,"callback");
        CFUNCSMESSPY("cb:cb_callback_in__cobyla__user__routines_capi=",cb->capi);
    }
    if (cb->capi==NULL) {
        PyErr_SetString(_cobyla_error,"cb: Callback callback not defined (as an argument or module _cobyla attribute).\n");
        goto capi_fail;
    }
    if (F2PyCapsule_Check(cb->capi)) {
    cb_callback_in__cobyla__user__routines_typedef cb_callback_in__cobyla__user__routines_cptr;
    cb_callback_in__cobyla__user__routines_cptr = F2PyCapsule_AsVoidPtr(cb->capi);
    (*cb_callback_in__cobyla__user__routines_cptr)(n_cb_capi,m_cb_capi,x);
    return;
    }
    if (capi_arglist==NULL) {
        capi_longjmp_ok = 0;
        capi_tmp = PyObject_GetAttrString(_cobyla_module,"callback_extra_args");
        if (capi_tmp) {
            capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
            Py_DECREF(capi_tmp);
            if (capi_arglist==NULL) {
                PyErr_SetString(_cobyla_error,"Failed to convert _cobyla.callback_extra_args to tuple.\n");
                goto capi_fail;
            }
        } else {
            PyErr_Clear();
            capi_arglist = (PyTupleObject *)Py_BuildValue("()");
        }
    }
    if (capi_arglist == NULL) {
        PyErr_SetString(_cobyla_error,"Callback callback argument list is not set.\n");
        goto capi_fail;
    }
/*setdims*/
    x_Dims[0]=n;
#ifdef PYPY_VERSION
#define CAPI_ARGLIST_SETITEM(idx, value) PyList_SetItem((PyObject *)capi_arglist_list, idx, value)
    capi_arglist_list = PySequence_List(capi_arglist);
    if (capi_arglist_list == NULL) goto capi_fail;
#else
#define CAPI_ARGLIST_SETITEM(idx, value) PyTuple_SetItem((PyObject *)capi_arglist, idx, value)
#endif
/*pyobjfrom*/
    if (cb->nofargs>capi_i) {
        /* tmp_arr will be inserted to capi_arglist_list that will be
           destroyed when leaving callback function wrapper together
           with tmp_arr. */
        PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,
          1,x_Dims,NPY_DOUBLE,NULL,(char*)x,1,
          NPY_ARRAY_FARRAY,NULL);


        if (tmp_arr==NULL)
            goto capi_fail;
        if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
            goto capi_fail;
}
#undef CAPI_ARGLIST_SETITEM
#ifdef PYPY_VERSION
    CFUNCSMESSPY("cb:capi_arglist=",capi_arglist_list);
#else
    CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
#endif
    CFUNCSMESS("cb:Call-back calling Python function callback.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
#ifdef PYPY_VERSION
    capi_return = PyObject_CallObject(cb->capi,(PyObject *)capi_arglist_list);
    Py_DECREF(capi_arglist_list);
    capi_arglist_list = NULL;
#else
    capi_return = PyObject_CallObject(cb->capi,(PyObject *)capi_arglist);
#endif
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
    CFUNCSMESSPY("cb:capi_return=",capi_return);
    if (capi_return == NULL) {
        fprintf(stderr,"capi_return is NULL\n");
        goto capi_fail;
    }
    if (capi_return == Py_None) {
        Py_DECREF(capi_return);
        capi_return = Py_BuildValue("()");
    }
    else if (!PyTuple_Check(capi_return)) {
        capi_return = Py_BuildValue("(N)",capi_return);
    }
    capi_j = PyTuple_Size(capi_return);
    capi_i = 0;
/*frompyobj*/
    CFUNCSMESS("cb:cb_callback_in__cobyla__user__routines:successful\n");
    Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
    goto capi_return_pt;
capi_fail:
    fprintf(stderr,"Call-back cb_callback_in__cobyla__user__routines failed.\n");
    Py_XDECREF(capi_return);
    Py_XDECREF(capi_arglist_list);
    if (capi_longjmp_ok) {
        longjmp(cb->jmpbuf,-1);
    }
capi_return_pt:
    ;
return;
}
/*************** end of cb_callback_in__cobyla__user__routines ***************/


/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************** minimize **********************************/
static char doc_f2py_rout__cobyla_minimize[] = "\
x,dinfo = minimize(calcfc,m,x,rhobeg,rhoend,dinfo,callback,[iprint,maxfun,calcfc_extra_args,callback_extra_args])\n\nWrapper for ``minimize``.\
\n\nParameters\n----------\n"
"calcfc : call-back function\n"
"m : input int\n"
"x : input rank-1 array('d') with bounds (n)\n"
"rhobeg : input float\n"
"rhoend : input float\n"
"dinfo : input rank-1 array('d') with bounds (4)\n"
"callback : call-back function\n"
"\nOther Parameters\n----------------\n"
"calcfc_extra_args : input tuple, optional\n    Default: ()\n"
"iprint : input int, optional\n    Default: 1\n"
"maxfun : input int, optional\n    Default: 100\n"
"callback_extra_args : input tuple, optional\n    Default: ()\n"
"\nReturns\n-------\n"
"x : rank-1 array('d') with bounds (n)\n"
"dinfo : rank-1 array('d') with bounds (4)\n"
"\nNotes\n-----\nCall-back functions::\n\n"
"    def calcfc(x,con): return f\n\
    Required arguments:\n"
"        x : input rank-1 array('d') with bounds (n)\n"
"        con : input rank-1 array('d') with bounds (m)\n"
"    Return objects:\n"
"        f : float\n"
"    def callback(x): return \n\
    Required arguments:\n"
"        x : input rank-1 array('d') with bounds (n)";
/* extern void F_FUNC(cobyla ,COBYLA )(cb_calcfc_in__cobyla__user__routines_typedef,int*,int*,double*,double*,double*,int*,int*,double*,int*,double*,cb_callback_in__cobyla__user__routines_typedef); */
static PyObject *f2py_rout__cobyla_minimize(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(cb_calcfc_in__cobyla__user__routines_typedef,int*,int*,double*,double*,double*,int*,int*,double*,int*,double*,cb_callback_in__cobyla__user__routines_typedef)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    cb_calcfc_in__cobyla__user__routines_t calcfc_cb = { Py_None, NULL, 0 };
    cb_calcfc_in__cobyla__user__routines_t *calcfc_cb_ptr = &calcfc_cb;
    PyTupleObject *calcfc_xa_capi = NULL;
    cb_calcfc_in__cobyla__user__routines_typedef calcfc_cptr;
    int n = 0;
    int m = 0;
    PyObject *m_capi = Py_None;
    double *x = NULL;
    npy_intp x_Dims[1] = {-1};
    const int x_Rank = 1;
    PyArrayObject *capi_x_as_array = NULL;
    int capi_x_intent = 0;
    PyObject *x_capi = Py_None;
    double rhobeg = 0;
    PyObject *rhobeg_capi = Py_None;
    double rhoend = 0;
    PyObject *rhoend_capi = Py_None;
    int iprint = 0;
    PyObject *iprint_capi = Py_None;
    int maxfun = 0;
    PyObject *maxfun_capi = Py_None;
    double *w = NULL;
    npy_intp w_Dims[1] = {-1};
    const int w_Rank = 1;
    PyArrayObject *capi_w_as_array = NULL;
    int capi_w_intent = 0;
    int *iact = NULL;
    npy_intp iact_Dims[1] = {-1};
    const int iact_Rank = 1;
    PyArrayObject *capi_iact_as_array = NULL;
    int capi_iact_intent = 0;
    double *dinfo = NULL;
    npy_intp dinfo_Dims[1] = {-1};
    const int dinfo_Rank = 1;
    PyArrayObject *capi_dinfo_as_array = NULL;
    int capi_dinfo_intent = 0;
    PyObject *dinfo_capi = Py_None;
    cb_callback_in__cobyla__user__routines_t callback_cb = { Py_None, NULL, 0 };
    cb_callback_in__cobyla__user__routines_t *callback_cb_ptr = &callback_cb;
    PyTupleObject *callback_xa_capi = NULL;
    cb_callback_in__cobyla__user__routines_typedef callback_cptr;
    static char *capi_kwlist[] = {"calcfc","m","x","rhobeg","rhoend","dinfo","callback","iprint","maxfun","calcfc_extra_args","callback_extra_args",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOO|OOO!O!:_cobyla.minimize",\
        capi_kwlist,&calcfc_cb.capi,&m_capi,&x_capi,&rhobeg_capi,&rhoend_capi,&dinfo_capi,&callback_cb.capi,&iprint_capi,&maxfun_capi,&PyTuple_Type,&calcfc_xa_capi,&PyTuple_Type,&callback_xa_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable calcfc */
if(F2PyCapsule_Check(calcfc_cb.capi)) {
  calcfc_cptr = F2PyCapsule_AsVoidPtr(calcfc_cb.capi);
} else {
  calcfc_cptr = cb_calcfc_in__cobyla__user__routines;
}

    if (create_cb_arglist(calcfc_cb.capi,calcfc_xa_capi,2,0,&calcfc_cb.nofargs,&calcfc_cb.args_capi,"failed in processing argument list for call-back calcfc.")) {

        CFUNCSMESS("Saving callback variables for `calcfc`.\n");
        calcfc_cb_ptr = swap_active_cb_calcfc_in__cobyla__user__routines(calcfc_cb_ptr);
    /* Processing variable m */
        f2py_success = int_from_pyobj(&m,m_capi,"_cobyla.minimize() 2nd argument (m) can't be converted to int");
    if (f2py_success) {
    /* Processing variable x */
    ;
    capi_x_intent |= F2PY_INTENT_IN|F2PY_INTENT_OUT;
    const char * capi_errmess = "_cobyla._cobyla.minimize: failed to create array from the 3rd argument `x`";
    capi_x_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,x_Dims,x_Rank,  capi_x_intent,x_capi,capi_errmess);
    if (capi_x_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = _cobyla_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        x = (double *)(PyArray_DATA(capi_x_as_array));

    /* Processing variable rhobeg */
        f2py_success = double_from_pyobj(&rhobeg,rhobeg_capi,"_cobyla.minimize() 4th argument (rhobeg) can't be converted to double");
    if (f2py_success) {
    /* Processing variable rhoend */
        f2py_success = double_from_pyobj(&rhoend,rhoend_capi,"_cobyla.minimize() 5th argument (rhoend) can't be converted to double");
    if (f2py_success) {
    /* Processing variable iprint */
    if (iprint_capi == Py_None) iprint = 1; else
        f2py_success = int_from_pyobj(&iprint,iprint_capi,"_cobyla.minimize() 1st keyword (iprint) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(0<=iprint && iprint<=3,"0<=iprint && iprint<=3","1st keyword iprint","minimize:iprint=%d",iprint) {
    /* Processing variable maxfun */
    if (maxfun_capi == Py_None) maxfun = 100; else
        f2py_success = int_from_pyobj(&maxfun,maxfun_capi,"_cobyla.minimize() 2nd keyword (maxfun) can't be converted to int");
    if (f2py_success) {
    /* Processing variable dinfo */
    dinfo_Dims[0]=4;
    capi_dinfo_intent |= F2PY_INTENT_IN|F2PY_INTENT_OUT;
    const char * capi_errmess = "_cobyla._cobyla.minimize: failed to create array from the 6th argument `dinfo`";
    capi_dinfo_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,dinfo_Dims,dinfo_Rank,  capi_dinfo_intent,dinfo_capi,capi_errmess);
    if (capi_dinfo_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = _cobyla_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        dinfo = (double *)(PyArray_DATA(capi_dinfo_as_array));

    /* Processing variable callback */
if(F2PyCapsule_Check(callback_cb.capi)) {
  callback_cptr = F2PyCapsule_AsVoidPtr(callback_cb.capi);
} else {
  callback_cptr = cb_callback_in__cobyla__user__routines;
}

    if (create_cb_arglist(callback_cb.capi,callback_xa_capi,1,0,&callback_cb.nofargs,&callback_cb.args_capi,"failed in processing argument list for call-back callback.")) {

        CFUNCSMESS("Saving callback variables for `callback`.\n");
        callback_cb_ptr = swap_active_cb_callback_in__cobyla__user__routines(callback_cb_ptr);
    /* Processing variable n */
    n = len(x);
    /* Processing variable w */
    w_Dims[0]=6 + 4 * m + 11 * n + 2 * m * n + 3 * n * n;
    capi_w_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_CACHE;
    const char * capi_errmess = "_cobyla._cobyla.minimize: failed to create array from the hidden `w`";
    capi_w_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,w_Dims,w_Rank,  capi_w_intent,Py_None,capi_errmess);
    if (capi_w_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = _cobyla_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        w = (double *)(PyArray_DATA(capi_w_as_array));

    /* Processing variable iact */
    iact_Dims[0]=1 + m;
    capi_iact_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_CACHE;
    const char * capi_errmess = "_cobyla._cobyla.minimize: failed to create array from the hidden `iact`";
    capi_iact_as_array = ndarray_from_pyobj(  NPY_INT,1,iact_Dims,iact_Rank,  capi_iact_intent,Py_None,capi_errmess);
    if (capi_iact_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = _cobyla_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        iact = (int *)(PyArray_DATA(capi_iact_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        if ((setjmp(calcfc_cb.jmpbuf)) || (setjmp(callback_cb.jmpbuf))) {
            f2py_success = 0;
        } else {
                (*f2py_func)(calcfc_cptr,&n,&m,x,&rhobeg,&rhoend,&iprint,&maxfun,w,iact,dinfo,callback_cptr);
        }
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("NN",capi_x_as_array,capi_dinfo_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
        Py_XDECREF(capi_iact_as_array);
    }  /* if (capi_iact_as_array == NULL) ... else of iact */
    /* End of cleaning variable iact */
        Py_XDECREF(capi_w_as_array);
    }  /* if (capi_w_as_array == NULL) ... else of w */
    /* End of cleaning variable w */
    /* End of cleaning variable n */
        CFUNCSMESS("Restoring callback variables for `callback`.\n");
        callback_cb_ptr = swap_active_cb_callback_in__cobyla__user__routines(callback_cb_ptr);
        Py_DECREF(callback_cb.args_capi);
    }
    /* End of cleaning variable callback */
    }  /* if (capi_dinfo_as_array == NULL) ... else of dinfo */
    /* End of cleaning variable dinfo */
    } /*if (f2py_success) of maxfun*/
    /* End of cleaning variable maxfun */
    } /*CHECKSCALAR(0<=iprint && iprint<=3)*/
    } /*if (f2py_success) of iprint*/
    /* End of cleaning variable iprint */
    } /*if (f2py_success) of rhoend*/
    /* End of cleaning variable rhoend */
    } /*if (f2py_success) of rhobeg*/
    /* End of cleaning variable rhobeg */
    }  /* if (capi_x_as_array == NULL) ... else of x */
    /* End of cleaning variable x */
    } /*if (f2py_success) of m*/
    /* End of cleaning variable m */
        CFUNCSMESS("Restoring callback variables for `calcfc`.\n");
        calcfc_cb_ptr = swap_active_cb_calcfc_in__cobyla__user__routines(calcfc_cb_ptr);
        Py_DECREF(calcfc_cb.args_capi);
    }
    /* End of cleaning variable calcfc */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************************** end of minimize ******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
    {"minimize",-1,{{-1}},0,0,(char *)  F_FUNC(cobyla ,COBYLA ),  (f2py_init_func)f2py_rout__cobyla_minimize,doc_f2py_rout__cobyla_minimize},

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "_cobyla",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit__cobyla(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = _cobyla_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module _cobyla (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("1.26.4");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module '_cobyla' is auto-generated with f2py (version:1.26.4).\nFunctions:\n"
"    x,dinfo = minimize(calcfc,m,x,rhobeg,rhoend,dinfo,callback,iprint=1,maxfun=100,calcfc_extra_args=(),callback_extra_args=())\n"
".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("1.26.4");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    _cobyla_error = PyErr_NewException ("_cobyla.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "__cobyla_error", _cobyla_error);
    Py_DECREF(_cobyla_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }

/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"_cobyla");
#endif
    return m;
}
#ifdef __cplusplus
}
#endif
