# Generated by devtools/yamaker (pypi).

PY23_LIBRARY()



VERSION(0.8.1)

LICENSE(ZPL-2.1)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    simplegeneric.py
)

RESOURCE_FILES(
    PREFIX contrib/python/simplegeneric/
    .dist-info/METADATA
    .dist-info/top_level.txt
)

END()
