# Generated by devtools/contrib/pypi-import.

PY23_LIBRARY()



VERSION(0.1.2)

LICENSE(BSD-2-Clause)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    appnope/__init__.py
    appnope/_dummy.py
    appnope/_nope.py
)

RESOURCE_FILES(
    PREFIX contrib/python/appnope/
    .dist-info/METADATA
    .dist-info/top_level.txt
)

END()
