# Generated by devtools/yamaker (pypi).

PY3_LIBRARY()



VERSION(3.1.0)

LICENSE(BSD-3-Clause)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    threadpoolctl.py
)

RESOURCE_FILES(
    PREFIX contrib/python/threadpoolctl/
    .dist-info/METADATA
)

END()
