#include "platform-linux.hpp"

#undef ZMQ_HAVE_EVENTFD
#undef ZMQ_HAVE_SO_PEERCRED
#undef ZMQ_HAVE_SOCK_CLOEXEC
#undef ZMQ_HAVE_TCP_KEEPIDLE
#undef ZMQ_IOTHREAD_POLLER_USE_EPOLL
#undef ZMQ_HAVE_PTHREAD_SETNAME_2
#undef ZMQ_HAVE_TIPC
#undef ZMQ_HAVE_BUSY_POLL

#define ZMQ_IOTHREAD_POLLER_USE_KQUEUE
#define ZMQ_HAVE_PTHREAD_SETNAME_1
