# Generated by devtools/yamaker (pypi).

PY2_LIBRARY()



VERSION(1.1.10)

LICENSE(BSD-3-Clause)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    enum/__init__.py
)

RESOURCE_FILES(
    PREFIX contrib/deprecated/python/enum34/
    .dist-info/METADATA
    .dist-info/top_level.txt
)

END()

RECURSE(
    tests
)
