# Generated by devtools/yamaker from nixpkgs 5852a21819542e6809f68ba5a798600e69874e76.

LIBRARY()



VERSION(0.8.0)

LICENSE(BSD-2-Clause)

NO_COMPILER_WARNINGS()

NO_RUNTIME()

SRCS(
    xxhash.c
)

END()
