# Generated by devtools/yamaker (pypi).

PY2_LIBRARY()



VERSION(1.6.4)

LICENSE(MIT)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    backports/functools_lru_cache.py
)

RESOURCE_FILES(
    PREFIX contrib/deprecated/python/backports.functools-lru-cache/
    .dist-info/METADATA
    .dist-info/top_level.txt
)

END()
