# Generated by devtools/yamaker.

LIBRARY()



VERSION(1.0.6.0.1)

LICENSE(BSD-4-Clause)

ADDINCL(
    contrib/libs/libbz2
)

NO_COMPILER_WARNINGS()

NO_UTIL()

IF (SANITIZER_TYPE STREQUAL undefined)
    NO_SANITIZE()
ENDIF()

SRCS(
    blocksort.c
    bzlib.c
    compress.c
    crctable.c
    decompress.c
    huffman.c
    randtable.c
)

END()
