LIBRARY()



PEERDIR(
    contrib/python/scipy/scipy/fftpack/src
)

SRCS(
    # dfft_subr_*.f in fftpack
    idd_frm_subr_0.f
    idd_frm_subr_1.f
    idd_frm_subr_2.f
    idd_frm_subr_3.f
    idd_frm_subr_4.f
    idd_frm_subr_5.f
    idd_frm_subr_6.f
    idd_frm_subr_7.f
    idd_frm_subr_8.f
    idd_house_subr_0.f
    idd_house_subr_1.f
    idd_house_subr_2.f
    idd_id2svd_subr_0.f
    idd_id2svd_subr_1.f
    idd_id2svd_subr_2.f
    idd_id2svd_subr_3.f
    idd_id2svd_subr_4.f
    idd_id2svd_subr_5.f
    idd_id_subr_0.f
    idd_id_subr_1.f
    idd_id_subr_2.f
    idd_id_subr_3.f
    idd_id_subr_4.f
    idd_id_subr_5.f
    idd_id_subr_6.f
    idd_id_subr_7.f
    iddp_aid_subr_0.f
    iddp_aid_subr_1.f
    iddp_aid_subr_2.f
    iddp_aid_subr_3.f
    iddp_aid_subr_4.f
    iddp_aid_subr_5.f
    iddp_asvd_subr_0.f
    iddp_asvd_subr_1.f
    iddp_rid_subr_0.f
    iddp_rid_subr_1.f
    iddp_rid_subr_2.f
    iddp_rid_subr_3.f
    iddp_rid_subr_4.f
    iddp_rsvd_subr_0.f
    iddp_rsvd_subr_1.f
    idd_qrpiv_subr_0.f
    idd_qrpiv_subr_1.f
    idd_qrpiv_subr_2.f
    idd_qrpiv_subr_3.f
    idd_qrpiv_subr_4.f
    idd_qrpiv_subr_5.f
    iddr_aid_subr_0.f
    iddr_aid_subr_1.f
    iddr_aid_subr_2.f
    iddr_aid_subr_3.f
    iddr_asvd_subr_0.f
    iddr_asvd_subr_1.f
    iddr_rid_subr_0.f
    iddr_rid_subr_1.f
    iddr_rsvd_subr_0.f
    iddr_rsvd_subr_1.f
    idd_sfft_subr_0.f
    idd_sfft_subr_1.f
    idd_sfft_subr_2.f
    idd_sfft_subr_3.f
    idd_sfft_subr_4.f
    idd_sfft_subr_5.f
    idd_sfft_subr_6.f
    idd_snorm_subr_0.f
    idd_snorm_subr_1.f
    idd_snorm_subr_2.f
    idd_snorm_subr_3.f
    idd_svd_subr_0.f
    idd_svd_subr_1.f
    idd_svd_subr_2.f
    idd_svd_subr_3.f
    idd_svd_subr_4.f
    id_rand_subr_0.f
    id_rand_subr_1.f
    id_rand_subr_2.f
    id_rtrans_subr_0.f
    id_rtrans_subr_10.f
    id_rtrans_subr_11.f
    id_rtrans_subr_12.f
    id_rtrans_subr_13.f
    id_rtrans_subr_14.f
    id_rtrans_subr_15.f
    id_rtrans_subr_16.f
    id_rtrans_subr_17.f
    id_rtrans_subr_1.f
    id_rtrans_subr_2.f
    id_rtrans_subr_3.f
    id_rtrans_subr_4.f
    id_rtrans_subr_5.f
    id_rtrans_subr_6.f
    id_rtrans_subr_7.f
    id_rtrans_subr_8.f
    id_rtrans_subr_9.f
    idz_frm_subr_0.f
    idz_frm_subr_1.f
    idz_frm_subr_2.f
    idz_frm_subr_3.f
    idz_frm_subr_4.f
    idz_frm_subr_5.f
    idz_frm_subr_6.f
    idz_house_subr_0.f
    idz_house_subr_1.f
    idz_house_subr_2.f
    idz_id2svd_subr_0.f
    idz_id2svd_subr_1.f
    idz_id2svd_subr_2.f
    idz_id2svd_subr_3.f
    idz_id2svd_subr_4.f
    idz_id2svd_subr_5.f
    idz_id_subr_0.f
    idz_id_subr_1.f
    idz_id_subr_2.f
    idz_id_subr_3.f
    idz_id_subr_4.f
    idz_id_subr_5.f
    idz_id_subr_6.f
    idz_id_subr_7.f
    idzp_aid_subr_0.f
    idzp_aid_subr_1.f
    idzp_aid_subr_2.f
    idzp_aid_subr_3.f
    idzp_aid_subr_4.f
    idzp_aid_subr_5.f
    idzp_asvd_subr_0.f
    idzp_asvd_subr_1.f
    idzp_asvd_subr_2.f
    idzp_rid_subr_0.f
    idzp_rid_subr_1.f
    idzp_rid_subr_2.f
    idzp_rid_subr_3.f
    idzp_rid_subr_4.f
    idzp_rsvd_subr_0.f
    idzp_rsvd_subr_1.f
    idzp_rsvd_subr_2.f
    idz_qrpiv_subr_0.f
    idz_qrpiv_subr_1.f
    idz_qrpiv_subr_2.f
    idz_qrpiv_subr_3.f
    idz_qrpiv_subr_4.f
    idz_qrpiv_subr_5.f
    idzr_aid_subr_0.f
    idzr_aid_subr_1.f
    idzr_aid_subr_2.f
    idzr_aid_subr_3.f
    idzr_asvd_subr_0.f
    idzr_asvd_subr_1.f
    idzr_rid_subr_0.f
    idzr_rid_subr_1.f
    idzr_rsvd_subr_0.f
    idzr_rsvd_subr_1.f
    idz_sfft_subr_0.f
    idz_sfft_subr_1.f
    idz_sfft_subr_2.f
    idz_snorm_subr_0.f
    idz_snorm_subr_1.f
    idz_snorm_subr_2.f
    idz_snorm_subr_3.f
    idz_svd_subr_0.f
    idz_svd_subr_1.f
    idz_svd_subr_2.f
    idz_svd_subr_3.f
    idz_svd_subr_4.f
    idz_svd_subr_5.f
    prini_subr_0.f
    prini_subr_1.f
    prini_subr_2.f
    prini_subr_3.f
    prini_subr_4.f
    prini_subr_5.f
    prini_subr_6.f
)

END()
