# Generated by devtools/yamaker.

LIBRARY()



VERSION(1.9.2)

LICENSE(BSD-2-Clause)

PEERDIR(
    contrib/libs/xxhash
)

ADDINCL(
    contrib/libs/xxhash
)

NO_RUNTIME()

SRCS(
    lz4.c
    lz4frame.c
    lz4hc.c
)

END()
