C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapsdot (sdotf2pywrap, n, x, offx, incx, y, 
     &offy, incy)
      external wsdot
      integer n
      integer offx
      integer incx
      integer offy
      integer incy
      real x(*)
      real y(*)
      real sdotf2pywrap, wsdot
      sdotf2pywrap = wsdot(n, x, offx, incx, y, offy, incy)
      end


      subroutine f2pywrapddot (ddotf2pywrap, n, x, offx, incx, y, 
     &offy, incy)
      external ddot
      integer n
      integer offx
      integer incx
      integer offy
      integer incy
      double precision x(*)
      double precision y(*)
      double precision ddotf2pywrap, ddot
      ddotf2pywrap = ddot(n, x, offx, incx, y, offy, incy)
      end


      subroutine f2pywrapcdotu (cdotuf2pywrap, n, x, offx, incx, y
     &, offy, incy)
      external wcdotu
      integer n
      integer offx
      integer incx
      integer offy
      integer incy
      complex x(*)
      complex y(*)
      complex cdotuf2pywrap, wcdotu
      cdotuf2pywrap = wcdotu(n, x, offx, incx, y, offy, incy)
      end


      subroutine f2pywrapzdotu (zdotuf2pywrap, n, x, offx, incx, y
     &, offy, incy)
      external wzdotu
      integer n
      integer offx
      integer incx
      integer offy
      integer incy
      double complex x(*)
      double complex y(*)
      double complex zdotuf2pywrap, wzdotu
      zdotuf2pywrap = wzdotu(n, x, offx, incx, y, offy, incy)
      end


      subroutine f2pywrapcdotc (cdotcf2pywrap, n, x, offx, incx, y
     &, offy, incy)
      external wcdotc
      integer n
      integer offx
      integer incx
      integer offy
      integer incy
      complex x(*)
      complex y(*)
      complex cdotcf2pywrap, wcdotc
      cdotcf2pywrap = wcdotc(n, x, offx, incx, y, offy, incy)
      end


      subroutine f2pywrapzdotc (zdotcf2pywrap, n, x, offx, incx, y
     &, offy, incy)
      external wzdotc
      integer n
      integer offx
      integer incx
      integer offy
      integer incy
      double complex x(*)
      double complex y(*)
      double complex zdotcf2pywrap, wzdotc
      zdotcf2pywrap = wzdotc(n, x, offx, incx, y, offy, incy)
      end


      subroutine f2pywrapsnrm2 (snrm2f2pywrap, n, x, offx, incx)
      external wsnrm2
      integer n
      integer offx
      integer incx
      real x(*)
      real snrm2f2pywrap, wsnrm2
      snrm2f2pywrap = wsnrm2(n, x, offx, incx)
      end


      subroutine f2pywrapscnrm2 (scnrm2f2pywrap, n, x, offx, incx)
      external wscnrm2
      integer n
      integer offx
      integer incx
      complex x(*)
      real scnrm2f2pywrap, wscnrm2
      scnrm2f2pywrap = wscnrm2(n, x, offx, incx)
      end


      subroutine f2pywrapdnrm2 (dnrm2f2pywrap, n, x, offx, incx)
      external dnrm2
      integer n
      integer offx
      integer incx
      double precision x(*)
      double precision dnrm2f2pywrap, dnrm2
      dnrm2f2pywrap = dnrm2(n, x, offx, incx)
      end


      subroutine f2pywrapdznrm2 (dznrm2f2pywrap, n, x, offx, incx)
      external dznrm2
      integer n
      integer offx
      integer incx
      double complex x(*)
      double precision dznrm2f2pywrap, dznrm2
      dznrm2f2pywrap = dznrm2(n, x, offx, incx)
      end


      subroutine f2pywrapsasum (sasumf2pywrap, n, x, offx, incx)
      external wsasum
      integer n
      integer offx
      integer incx
      real x(*)
      real sasumf2pywrap, wsasum
      sasumf2pywrap = wsasum(n, x, offx, incx)
      end


      subroutine f2pywrapscasum (scasumf2pywrap, n, x, offx, incx)
      external wscasum
      integer n
      integer offx
      integer incx
      complex x(*)
      real scasumf2pywrap, wscasum
      scasumf2pywrap = wscasum(n, x, offx, incx)
      end


      subroutine f2pywrapdasum (dasumf2pywrap, n, x, offx, incx)
      external dasum
      integer n
      integer offx
      integer incx
      double precision x(*)
      double precision dasumf2pywrap, dasum
      dasumf2pywrap = dasum(n, x, offx, incx)
      end


      subroutine f2pywrapdzasum (dzasumf2pywrap, n, x, offx, incx)
      external dzasum
      integer n
      integer offx
      integer incx
      double complex x(*)
      double precision dzasumf2pywrap, dzasum
      dzasumf2pywrap = dzasum(n, x, offx, incx)
      end

