#if defined(__GNUC__)
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#if defined(__clang__)
#pragma GCC diagnostic ignored "-Wunknown-warning-option"
#endif
#pragma GCC diagnostic ignored "-Wsubobject-linkage"
#endif

#include "util/generic/adaptor.cpp"
#include "util/generic/algorithm.cpp"
#include "util/generic/array_ref.cpp"
#include "util/generic/array_size.cpp"
#include "util/generic/bitmap.cpp"
#include "util/generic/bitops.cpp"
#include "util/generic/bt_exception.cpp"
#include "util/generic/buffer.cpp"
#include "util/generic/cast.cpp"
#include "util/generic/deque.cpp"
#include "util/generic/explicit_type.cpp"
#include "util/generic/fastqueue.cpp"
#include "util/generic/flags.cpp"
#include "util/generic/function.cpp"
#include "util/generic/function_ref.cpp"
#include "util/generic/fwd.cpp"
#include "util/generic/guid.cpp"
#include "util/generic/hash.cpp"
#include "util/generic/hash_multi_map.cpp"
#include "util/generic/hash_table.cpp"
#include "util/generic/hash_primes.cpp"
#include "util/generic/hash_set.cpp"
#include "util/generic/hide_ptr.cpp"
#include "util/generic/intrlist.cpp"
#include "util/generic/is_in.cpp"
#include "util/generic/iterator.cpp"
#include "util/generic/iterator_range.cpp"
#include "util/generic/lazy_value.cpp"
#include "util/generic/list.cpp"
#include "util/generic/map.cpp"
#include "util/generic/mapfindptr.cpp"
#include "util/generic/maybe.cpp"
#include "util/generic/mem_copy.cpp"
#include "util/generic/noncopyable.cpp"
#include "util/generic/object_counter.cpp"
#include "util/generic/overloaded.cpp"
#include "util/generic/ptr.cpp"
#include "util/generic/queue.cpp"
#include "util/generic/refcount.cpp"
#include "util/generic/scope.cpp"
#include "util/generic/serialized_enum.cpp"
#include "util/generic/set.cpp"
#include "util/generic/singleton.cpp"
#include "util/generic/size_literals.cpp"
#include "util/generic/stack.cpp"
#include "util/generic/store_policy.cpp"
#include "util/generic/strbuf.cpp"
#include "util/generic/strfcpy.cpp"
#include "util/generic/string.cpp"
#include "util/generic/typelist.cpp"
#include "util/generic/typetraits.cpp"
#include "util/generic/utility.cpp"
#include "util/generic/va_args.cpp"
#include "util/generic/variant.cpp"
#include "util/generic/vector.cpp"
#include "util/generic/xrange.cpp"
#include "util/generic/yexception.cpp"
#include "util/generic/ylimits.cpp"
#include "util/generic/ymath.cpp"
