#if defined(__GNUC__)
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#if defined(__clang__)
#pragma GCC diagnostic ignored "-Wunknown-warning-option"
#endif
#pragma GCC diagnostic ignored "-Wsubobject-linkage"
#endif

#include "util/stream/aligned.cpp"
#include "util/stream/buffer.cpp"
#include "util/stream/buffered.cpp"
#include "util/stream/debug.cpp"
#include "util/stream/direct_io.cpp"
#include "util/stream/file.cpp"
#include "util/stream/format.cpp"
#include "util/stream/fwd.cpp"
#include "util/stream/hex.cpp"
#include "util/stream/holder.cpp"
#include "util/stream/input.cpp"
#include "util/stream/labeled.cpp"
#include "util/stream/length.cpp"
#include "util/stream/mem.cpp"
#include "util/stream/multi.cpp"
#include "util/stream/null.cpp"
#include "util/stream/output.cpp"
#include "util/stream/pipe.cpp"
#include "util/stream/printf.cpp"
#include "util/stream/str.cpp"
#include "util/stream/tee.cpp"
#include "util/stream/tempbuf.cpp"
#include "util/stream/tokenizer.cpp"
#include "util/stream/trace.cpp"
#include "util/stream/walk.cpp"
#include "util/stream/zerocopy.cpp"
#include "util/stream/zerocopy_output.cpp"
#include "util/stream/zlib.cpp"
