#if defined(__GNUC__)
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#if defined(__clang__)
#pragma GCC diagnostic ignored "-Wunknown-warning-option"
#endif
#pragma GCC diagnostic ignored "-Wsubobject-linkage"
#endif

#include "util/system/align.cpp"
#include "util/system/byteorder.cpp"
#include "util/system/cpu_id.cpp"
#include "util/system/fhandle.cpp"
#include "util/system/guard.cpp"
#include "util/system/interrupt_signals.cpp"
#include "util/system/madvise.cpp"
#include "util/system/maxlen.cpp"
#include "util/system/mincore.cpp"
#include "util/system/mktemp.cpp"
#include "util/system/mlock.cpp"
#include "util/system/mutex.cpp"
#include "util/system/nice.cpp"
#include "util/system/pipe.cpp"
#include "util/system/platform.cpp"
#include "util/system/progname.cpp"
#include "util/system/protect.cpp"
#include "util/system/rusage.cpp"
#include "util/system/rwlock.cpp"
#include "util/system/sanitizers.cpp"
#include "util/system/shellcommand.cpp"
#include "util/system/shmat.cpp"
#include "util/system/sigset.cpp"
#include "util/system/spinlock.cpp"
#include "util/system/spin_wait.cpp"
#include "util/system/src_location.cpp"
#include "util/system/sys_alloc.cpp"
#include "util/system/sysstat.cpp"
#include "util/system/tempfile.cpp"
#include "util/system/tls.cpp"
#include "util/system/type_name.cpp"
#include "util/system/unaligned_mem.cpp"
#include "util/system/user.cpp"
#include "util/system/utime.cpp"
#include "util/system/yassert.cpp"
#include "util/system/yield.cpp"
