include(default)
[settings]
arch=x86_64
build_type=Release
compiler=clang
compiler.libcxx=libc++
compiler.version=14
compiler.cppstd=20
os=Android
os.api_level=21
[tool_requires]
android-ndk/r25
[options]
