LIBRARY()

LICENSE(
    PD
)



NO_COMPILER_WARNINGS()

NO_RUNTIME()

ENABLE(YANDEX_TEST_MULTIPLEX)

IF (OS_WINDOWS)
    CFLAGS(-DSQLITE_OS_WIN)
ELSE()
    CFLAGS(-DSQLITE_OS_UNIX)
ENDIF()

CFLAGS(-DSQLITE_ENABLE_COLUMN_METADATA)
CFLAGS(-DSQLITE_ENABLE_UPDATE_DELETE_LIMIT)
CFLAGS(-DSQLITE_THREADSAFE)
CFLAGS(-DSQLITE_SYSTEM_MALLOC)
CFLAGS(-DHAVE_USLEEP)
CFLAGS(-DSQLITE_ENABLE_FTS3)
CFLAGS(-DSQLITE_ENABLE_FTS3_PARENTHESIS)
CFLAGS(-DSQLITE_ENABLE_FTS4_UNICODE61)


SRCS(
    sqlite3.c
)

IF (YANDEX_TEST_MULTIPLEX)
    CFLAGS(-DYANDEX_TEST_MULTIPLEX)
    SRCS(
        test_multiplex.c
    )
ENDIF()

END()
