# Generated by devtools/yamaker from nixpkgs 21.11.

PROGRAM()



VERSION(3.9.12)

ORIGINAL_SOURCE(https://github.com/python/cpython/archive/v3.9.12.tar.gz)

LICENSE(Python-2.0)

USE_PYTHON3()

PEERDIR(
    contrib/tools/python3/src/Modules/_sqlite
)

CFLAGS(
    -DPy_BUILD_CORE
)

SRCS(
    src/Programs/python.c
)

END()

RECURSE(
    pycc
    src/Lib
)
