# Generated by devtools/yamaker (pypi).

PY2_LIBRARY()



VERSION(20.9)

LICENSE(BSD-3-Clause)

PEERDIR(
    contrib/python/pyparsing
)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    packaging/__about__.py
    packaging/__init__.py
    packaging/_compat.py
    packaging/_structures.py
    packaging/_typing.py
    packaging/markers.py
    packaging/requirements.py
    packaging/specifiers.py
    packaging/tags.py
    packaging/utils.py
    packaging/version.py
)

RESOURCE_FILES(
    PREFIX contrib/python/packaging/py2/
    .dist-info/METADATA
    .dist-info/top_level.txt
    packaging/py.typed
)

END()
