
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-16T12:17:51-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "bbbf5eff75883511a1126b11205bef34f1cf0ff9",
 "version": "5.16.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
