
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-17T09:49:11-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "84456f33e7dcd094544fbe835fbd1965825d4f95",
 "version": "5.21.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
