
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-11T15:18:03-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "01c6450cc81abce8e6cd702cea7c1a24d631398b",
 "version": "5.16.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
