

IF (HOST_OS_DARWIN AND HOST_ARCH_X86_64 OR
    HOST_OS_LINUX AND HOST_ARCH_X86_64 OR
    HOST_OS_WINDOWS AND HOST_ARCH_X86_64)
    ENABLE(VALID_HOST_PLATFORM_FOR_PREBUILT_CPP_STYLEGUIDE)
ENDIF()

IF (NOT USE_PREBUILT_TOOLS OR NOT VALID_HOST_PLATFORM_FOR_PREBUILT_CPP_STYLEGUIDE)
    PROGRAM()

    NO_COMPILER_WARNINGS()

    PEERDIR(
        contrib/libs/protoc
    )

    SRCS(
        cpp_styleguide.cpp
    )

    END()
ELSE()
    PREBUILT_PROGRAM()

    PEERDIR(build/external_resources/arcadia_cpp_styleguide)

    PRIMARY_OUTPUT(${ARCADIA_CPP_STYLEGUIDE_RESOURCE_GLOBAL}/cpp_styleguide${MODULE_SUFFIX})

    END()
ENDIF()
