# Generated by devtools/yamaker (pypi).

PY23_LIBRARY()



VERSION(0.7.5)

LICENSE(MIT)

IF (PYTHON2)
    PEERDIR(
        contrib/python/pathlib2
    )
ENDIF()

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    pickleshare.py
)

RESOURCE_FILES(
    PREFIX contrib/python/pickleshare/
    .dist-info/METADATA
    .dist-info/top_level.txt
)

END()
