

RECURSE(
    algo
    algo/ut
    algo_helpers
    algo_helpers/ut
    app_helpers
    ctr_description
    data_types
    data_util
    data_util/ut
    distributed
    documents_importance
    embeddings
    embedding_features
    embedding_features/ut
    feature_estimator
    feature_estimator/ut
    functools
    functools/ut
    hyperparameter_tuning
    index_range
    init
    labels
    lapack
    options
    options/ut
    pairs
    quantization
    quantization/ut
    quantization_schema
    quantization_schema/ut
    quantized_pool
    quantized_pool_analysis
    quantized_pool/ut
    target
    text_features
    text_features/ut
    text_processing
    text_processing/ut
    validate_fb
)
