# Generated by devtools/yamaker from nixpkgs 22.05.

PY3_LIBRARY()

LICENSE(
    Apache-2.0 AND
    LicenseRef-scancode-unknown-license-reference AND
    Public-Domain
)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)



VERSION(0.29.33)

ORIGINAL_SOURCE(mirror://pypi/C/Cython/Cython-0.29.33.tar.gz)

NO_LINT()

END()
