
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-01T11:05:19-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "aa14db7476ebf12cd6839304e4d1596e99d052a5",
 "version": "4.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
