#include "jemalloc_internal_defs-linux.h"

#undef JEMALLOC_OVERRIDE___LIBC_CALLOC 
#undef JEMALLOC_OVERRIDE___LIBC_FREE 
#undef JEMALLOC_OVERRIDE___LIBC_MALLOC 
#undef JEMALLOC_OVERRIDE___LIBC_MEMALIGN 
#undef JEMALLOC_OVERRIDE___LIBC_REALLOC 
#undef JEMALLOC_OVERRIDE___LIBC_VALLOC 
#undef JEMALLOC_OVERRIDE___POSIX_MEMALIGN 

