PY2_LIBRARY()

LICENSE(BSD-3-Clause)



VERSION(0.18.1)

PEERDIR(
    contrib/libs/cblas
    contrib/python/numpy
    contrib/python/scipy
)

ADDINCL(
    contrib/libs/cblas
    FOR cython contrib/python/scikit-learn/py2
    contrib/python/scikit-learn/py2/sklearn/linear_model
    contrib/python/scikit-learn/py2/sklearn/svm
    contrib/python/scikit-learn/py2/sklearn/svm/src/libsvm
    contrib/python/scikit-learn/py2/sklearn/utils
)

NO_CHECK_IMPORTS(
    sklearn.utils.*
)

NO_COMPILER_WARNINGS()

NO_LINT()

SRCS(
    sklearn/svm/src/liblinear/linear.cpp
    sklearn/svm/src/liblinear/tron.cpp
    sklearn/svm/src/libsvm/libsvm_template.cpp
    sklearn/utils/src/gamma.c
    sklearn/utils/src/MurmurHash3.cpp

    # This is included from libsvm_template.cpp.
    #sklearn/svm/src/libsvm/svm.cpp

    # These files are embedded into pyx, like headers.
    #sklearn/svm/src/liblinear/liblinear_helper.c
    #sklearn/svm/src/libsvm/libsvm_helper.c
    #sklearn/svm/src/libsvm/libsvm_sparse_helper.c
)

PY_SRCS(
    TOP_LEVEL

    CYTHON_CPP
    sklearn/cluster/_dbscan_inner.pyx
    sklearn/cluster/_hierarchical.pyx
    sklearn/utils/fast_dict.pyx

    CYTHON_C
    sklearn/__check_build/__init__.py
    sklearn/__check_build/_check_build.pyx
    sklearn/__check_build/setup.py
    sklearn/__init__.py
    sklearn/_build_utils/__init__.py
    sklearn/_isotonic.pyx
    sklearn/base.py
    sklearn/calibration.py
    sklearn/cluster/__init__.py
    sklearn/cluster/_feature_agglomeration.py
    sklearn/cluster/_k_means.pyx
    sklearn/cluster/_k_means_elkan.pyx
    sklearn/cluster/affinity_propagation_.py
    sklearn/cluster/bicluster.py
    sklearn/cluster/birch.py
    sklearn/cluster/dbscan_.py
    sklearn/cluster/hierarchical.py
    sklearn/cluster/k_means_.py
    sklearn/cluster/mean_shift_.py
    sklearn/cluster/setup.py
    sklearn/cluster/spectral.py
    sklearn/covariance/__init__.py
    sklearn/covariance/empirical_covariance_.py
    sklearn/covariance/graph_lasso_.py
    sklearn/covariance/outlier_detection.py
    sklearn/covariance/robust_covariance.py
    sklearn/covariance/shrunk_covariance_.py
    sklearn/cross_decomposition/__init__.py
    sklearn/cross_decomposition/cca_.py
    sklearn/cross_decomposition/pls_.py
    sklearn/cross_validation.py
    sklearn/datasets/__init__.py
    sklearn/datasets/_svmlight_format.pyx
    sklearn/datasets/base.py
    sklearn/datasets/california_housing.py
    sklearn/datasets/covtype.py
    sklearn/datasets/kddcup99.py
    sklearn/datasets/lfw.py
    sklearn/datasets/mlcomp.py
    sklearn/datasets/mldata.py
    sklearn/datasets/olivetti_faces.py
    sklearn/datasets/rcv1.py
    sklearn/datasets/samples_generator.py
    sklearn/datasets/setup.py
    sklearn/datasets/species_distributions.py
    sklearn/datasets/svmlight_format.py
    sklearn/datasets/twenty_newsgroups.py
    sklearn/decomposition/__init__.py
    sklearn/decomposition/_online_lda.pyx
    sklearn/decomposition/base.py
    sklearn/decomposition/cdnmf_fast.pyx
    sklearn/decomposition/dict_learning.py
    sklearn/decomposition/factor_analysis.py
    sklearn/decomposition/fastica_.py
    sklearn/decomposition/incremental_pca.py
    sklearn/decomposition/kernel_pca.py
    sklearn/decomposition/nmf.py
    sklearn/decomposition/online_lda.py
    sklearn/decomposition/pca.py
    sklearn/decomposition/setup.py
    sklearn/decomposition/sparse_pca.py
    sklearn/decomposition/truncated_svd.py
    sklearn/discriminant_analysis.py
    sklearn/dummy.py
    sklearn/ensemble/__init__.py
    sklearn/ensemble/_gradient_boosting.pyx
    sklearn/ensemble/bagging.py
    sklearn/ensemble/base.py
    sklearn/ensemble/forest.py
    sklearn/ensemble/gradient_boosting.py
    sklearn/ensemble/iforest.py
    sklearn/ensemble/partial_dependence.py
    sklearn/ensemble/setup.py
    sklearn/ensemble/voting_classifier.py
    sklearn/ensemble/weight_boosting.py
    sklearn/exceptions.py
    sklearn/externals/__init__.py
    sklearn/externals/funcsigs.py
    sklearn/externals/joblib/__init__.py
    sklearn/externals/joblib/_compat.py
    sklearn/externals/joblib/_memory_helpers.py
    sklearn/externals/joblib/_multiprocessing_helpers.py
    sklearn/externals/joblib/_parallel_backends.py
    sklearn/externals/joblib/disk.py
    sklearn/externals/joblib/format_stack.py
    sklearn/externals/joblib/func_inspect.py
    sklearn/externals/joblib/hashing.py
    sklearn/externals/joblib/logger.py
    sklearn/externals/joblib/memory.py
    sklearn/externals/joblib/my_exceptions.py
    sklearn/externals/joblib/numpy_pickle.py
    sklearn/externals/joblib/numpy_pickle_compat.py
    sklearn/externals/joblib/numpy_pickle_utils.py
    sklearn/externals/joblib/parallel.py
    sklearn/externals/joblib/pool.py
    sklearn/externals/joblib/testing.py
    sklearn/externals/setup.py
    sklearn/externals/six.py
    sklearn/externals/test_externals_setup.py
    sklearn/feature_extraction/__init__.py
    sklearn/feature_extraction/_hashing.pyx
    sklearn/feature_extraction/dict_vectorizer.py
    sklearn/feature_extraction/hashing.py
    sklearn/feature_extraction/image.py
    sklearn/feature_extraction/setup.py
    sklearn/feature_extraction/stop_words.py
    sklearn/feature_extraction/text.py
    sklearn/feature_selection/__init__.py
    sklearn/feature_selection/base.py
    sklearn/feature_selection/from_model.py
    sklearn/feature_selection/mutual_info_.py
    sklearn/feature_selection/rfe.py
    sklearn/feature_selection/univariate_selection.py
    sklearn/feature_selection/variance_threshold.py
    sklearn/gaussian_process/__init__.py
    sklearn/gaussian_process/correlation_models.py
    sklearn/gaussian_process/gaussian_process.py
    sklearn/gaussian_process/gpc.py
    sklearn/gaussian_process/gpr.py
    sklearn/gaussian_process/kernels.py
    sklearn/gaussian_process/regression_models.py
    sklearn/grid_search.py
    sklearn/isotonic.py
    sklearn/kernel_approximation.py
    sklearn/kernel_ridge.py
    sklearn/lda.py
    sklearn/learning_curve.py
    sklearn/linear_model/__init__.py
    sklearn/linear_model/base.py
    sklearn/linear_model/bayes.py
    sklearn/linear_model/cd_fast.pyx
    sklearn/linear_model/coordinate_descent.py
    sklearn/linear_model/huber.py
    sklearn/linear_model/least_angle.py
    sklearn/linear_model/logistic.py
    sklearn/linear_model/omp.py
    sklearn/linear_model/passive_aggressive.py
    sklearn/linear_model/perceptron.py
    sklearn/linear_model/randomized_l1.py
    sklearn/linear_model/ransac.py
    sklearn/linear_model/ridge.py
    sklearn/linear_model/sag.py
    sklearn/linear_model/sag_fast.pyx
    sklearn/linear_model/setup.py
    sklearn/linear_model/sgd_fast.pyx
    sklearn/linear_model/stochastic_gradient.py
    sklearn/linear_model/theil_sen.py
    sklearn/manifold/__init__.py
    sklearn/manifold/_barnes_hut_tsne.pyx
    sklearn/manifold/_utils.pyx
    sklearn/manifold/isomap.py
    sklearn/manifold/locally_linear.py
    sklearn/manifold/mds.py
    sklearn/manifold/setup.py
    sklearn/manifold/spectral_embedding_.py
    sklearn/manifold/t_sne.py
    sklearn/metrics/__init__.py
    sklearn/metrics/base.py
    sklearn/metrics/classification.py
    sklearn/metrics/cluster/__init__.py
    sklearn/metrics/cluster/bicluster.py
    sklearn/metrics/cluster/expected_mutual_info_fast.pyx
    sklearn/metrics/cluster/setup.py
    sklearn/metrics/cluster/supervised.py
    sklearn/metrics/cluster/unsupervised.py
    sklearn/metrics/pairwise.py
    sklearn/metrics/pairwise_fast.pyx
    sklearn/metrics/ranking.py
    sklearn/metrics/regression.py
    sklearn/metrics/scorer.py
    sklearn/metrics/setup.py
    sklearn/mixture/__init__.py
    sklearn/mixture/base.py
    sklearn/mixture/bayesian_mixture.py
    sklearn/mixture/dpgmm.py
    sklearn/mixture/gaussian_mixture.py
    sklearn/mixture/gmm.py
    sklearn/model_selection/__init__.py
    sklearn/model_selection/_search.py
    sklearn/model_selection/_split.py
    sklearn/model_selection/_validation.py
    sklearn/multiclass.py
    sklearn/multioutput.py
    sklearn/naive_bayes.py
    sklearn/neighbors/__init__.py
    sklearn/neighbors/approximate.py
    sklearn/neighbors/ball_tree.pyx
    sklearn/neighbors/base.py
    sklearn/neighbors/classification.py
    sklearn/neighbors/dist_metrics.pyx
    sklearn/neighbors/graph.py
    sklearn/neighbors/kd_tree.pyx
    sklearn/neighbors/kde.py
    sklearn/neighbors/nearest_centroid.py
    sklearn/neighbors/regression.py
    sklearn/neighbors/setup.py
    sklearn/neighbors/typedefs.pyx
    sklearn/neighbors/unsupervised.py
    sklearn/neural_network/__init__.py
    sklearn/neural_network/_base.py
    sklearn/neural_network/_stochastic_optimizers.py
    sklearn/neural_network/multilayer_perceptron.py
    sklearn/neural_network/rbm.py
    sklearn/pipeline.py
    sklearn/preprocessing/__init__.py
    sklearn/preprocessing/_function_transformer.py
    sklearn/preprocessing/data.py
    sklearn/preprocessing/imputation.py
    sklearn/preprocessing/label.py
    sklearn/qda.py
    sklearn/random_projection.py
    sklearn/semi_supervised/__init__.py
    sklearn/semi_supervised/label_propagation.py
    sklearn/setup.py
    sklearn/svm/__init__.py
    sklearn/svm/base.py
    sklearn/svm/bounds.py
    sklearn/svm/classes.py
    sklearn/svm/liblinear.pyx
    sklearn/svm/libsvm.pyx
    sklearn/svm/libsvm_sparse.pyx
    sklearn/svm/setup.py
    sklearn/tree/__init__.py
    sklearn/tree/_criterion.pyx
    sklearn/tree/_splitter.pyx
    sklearn/tree/_tree.pyx
    sklearn/tree/_utils.pyx
    sklearn/tree/export.py
    sklearn/tree/setup.py
    sklearn/tree/tree.py
    sklearn/utils/__init__.py
    sklearn/utils/_logistic_sigmoid.pyx
    sklearn/utils/_random.pyx
    sklearn/utils/_scipy_sparse_lsqr_backport.py
    sklearn/utils/arpack.py
    sklearn/utils/arrayfuncs.pyx
    sklearn/utils/bench.py
    sklearn/utils/class_weight.py
    sklearn/utils/deprecation.py
    sklearn/utils/estimator_checks.py
    sklearn/utils/extmath.py
    sklearn/utils/fixes.py
    sklearn/utils/graph.py
    sklearn/utils/graph_shortest_path.pyx
    sklearn/utils/lgamma.pyx
    sklearn/utils/linear_assignment_.py
    sklearn/utils/metaestimators.py
    sklearn/utils/mocking.py
    sklearn/utils/multiclass.py
    sklearn/utils/murmurhash.pyx
    sklearn/utils/optimize.py
    sklearn/utils/random.py
    sklearn/utils/seq_dataset.pyx
    sklearn/utils/setup.py
    sklearn/utils/sparsefuncs.py
    sklearn/utils/sparsefuncs_fast.pyx
    sklearn/utils/sparsetools/__init__.py
    sklearn/utils/sparsetools/_graph_tools.pyx
    sklearn/utils/sparsetools/_graph_validation.py
    sklearn/utils/sparsetools/_traversal.pyx
    sklearn/utils/sparsetools/setup.py
    sklearn/utils/stats.py
    sklearn/utils/testing.py
    sklearn/utils/validation.py
    sklearn/utils/weight_vector.pyx
)

END()

RECURSE_FOR_TESTS(
    #tests
)
