# Generated by devtools/yamaker.

LIBRARY()

LICENSE(Apache-2.0)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)



ADDINCL(
    GLOBAL contrib/restricted/abseil-cpp
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    internal/cycleclock.cc
    internal/low_level_alloc.cc
    internal/raw_logging.cc
    internal/scoped_set_env.cc
    internal/spinlock.cc
    internal/spinlock_wait.cc
    internal/strerror.cc
    internal/sysinfo.cc
    internal/thread_identity.cc
    internal/throw_delegate.cc
    internal/unscaledcycleclock.cc
    log_severity.cc
)

END()
