LIBRARY()



SRCS(
    dst.c
    dct.c
    convolve.c
    zrfft.c
    zfftnd.c
    drfft.c
    zfft.c
    dfftpack/dcosti.f
    dfftpack/dsint1.f
    dfftpack/zffti.f
    dfftpack/dffti1.f
    dfftpack/zfftf1.f
    dfftpack/dsinqf.f
    dfftpack/dfftf1.f
    dfftpack/zfftb1.f
    dfftpack/zffti1.f
    dfftpack/dcosqf.f
    dfftpack/dfftf.f
    dfftpack/dsinqb.f
    dfftpack/dfftb1.f
    dfftpack/dsinqi.f
    dfftpack/dfftb.f
    dfftpack/zfftf.f
    dfftpack/dsint.f
    dfftpack/dcosqb.f
    dfftpack/dcost.f
    dfftpack/zfftb.f
    dfftpack/dffti.f
    dfftpack/dsinti.f
    dfftpack/dcosqi.f
    fftpack/cosqb.f
    fftpack/rfftb1.f
    fftpack/sinti.f
    fftpack/cfftb1.f
    fftpack/rfftf1.f
    fftpack/rffti1.f
    fftpack/sinqf.f
    fftpack/cosqi.f
    fftpack/cost.f
    fftpack/sint1.f
    fftpack/cfftb.f
    fftpack/rfftf.f
    fftpack/sinqi.f
    fftpack/cfftf.f
    fftpack/cffti1.f
    fftpack/costi.f
    fftpack/rfftb.f
    fftpack/cosqf.f
    fftpack/cfftf1.f
    fftpack/sint.f
    fftpack/cffti.f
    fftpack/sinqb.f
    fftpack/rffti.f
)

END()
