#!/bin/sh -e

rev=327000

svn export https://llvm.org/svn/llvm-project/libcxx/trunk@$rev libcxx-r$rev
cd libcxx-r$rev

rm -r benchmarks cmake docs fuzzing lib test utils www CMakeLists.txt TODO.TXT .arcconfig .gitignore include/CMakeLists.txt appveyor.yml appveyor-reqs-install.cmd
