# CMake generated Testfile for 
# Source directory: /Users/makar/Documents/Course work/Repository/catboost/contrib/libs
# Build directory: /Users/makar/Documents/Course work/Repository/catboost/build_artifacts/contrib/libs
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("cxxsupp")
subdirs("libunwind")
subdirs("zlib")
subdirs("double-conversion")
subdirs("libc_compat")
subdirs("protoc")
subdirs("protobuf")
subdirs("rapidjson")
subdirs("re2")
subdirs("mimalloc")
subdirs("tbb")
subdirs("flatbuffers")
subdirs("crcutil")
subdirs("nayuki_md5")
subdirs("base64")
subdirs("fmath")
subdirs("clapack")
subdirs("libf2c")
subdirs("cblas")
subdirs("tensorboard")
subdirs("brotli")
subdirs("libbz2")
subdirs("fastlz")
subdirs("zstd06")
subdirs("lz4")
subdirs("xxhash")
subdirs("lzmasdk")
subdirs("snappy")
subdirs("zstd")
subdirs("coreml")
subdirs("onnx")
subdirs("jdk")
subdirs("jemalloc")
subdirs("pugixml")
