# Generated by devtools/yamaker (pypi).

PY2_LIBRARY()



VERSION(4.0.2)

LICENSE(MIT)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    backports/configparser/__init__.py
    backports/configparser/helpers.py
    configparser.py
)

RESOURCE_FILES(
    PREFIX contrib/deprecated/python/configparser/
    .dist-info/METADATA
    .dist-info/top_level.txt
)

END()
