# Generated by devtools/yamaker from nixpkgs 22.05.

LIBRARY()

LICENSE(
    LicenseRef-scancode-other-permissive AND
    LicenseRef-scancode-unknown-license-reference AND
    Qhull
)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)



VERSION(8.0.2)

ORIGINAL_SOURCE(https://github.com/qhull/qhull/archive/v8.0.2.tar.gz)

ADDINCL(
    contrib/libs/qhull
)

NO_COMPILER_WARNINGS()

NO_RUNTIME()

SRCS(
    libqhull_r/geom2_r.c
    libqhull_r/geom_r.c
    libqhull_r/global_r.c
    libqhull_r/io_r.c
    libqhull_r/libqhull_r.c
    libqhull_r/mem_r.c
    libqhull_r/merge_r.c
    libqhull_r/poly2_r.c
    libqhull_r/poly_r.c
    libqhull_r/qset_r.c
    libqhull_r/random_r.c
    libqhull_r/rboxlib_r.c
    libqhull_r/stat_r.c
    libqhull_r/user_r.c
    libqhull_r/usermem_r.c
    libqhull_r/userprintf_r.c
    libqhull_r/userprintf_rbox_r.c
)

END()
