# Generated by devtools/yamaker.

PROGRAM()

WITHOUT_LICENSE_TEXTS()



LICENSE(GPL-2.0-only)

PEERDIR(
    contrib/restricted/libffi
)

NO_COMPILER_WARNINGS()

NO_RUNTIME()

SRCDIR(contrib/restricted/libffi/testsuite/libffi.closures)

SRCS(
    cls_align_pointer.c
)

END()
