C     -*- fortran -*-
C     This file is autogenerated with f2py (version:1.26.4)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pyinitdkblck(setupfunc)
      external setupfunc
      integer ivls
      common /dkblck/ ivls
      call setupfunc(ivls)
      end


