cmake_policy(SET CMP0091 NEW)
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")

add_link_options(
  /NOLOGO
  /ERRORREPORT:PROMPT
  /SUBSYSTEM:CONSOLE
  /TLBID:1
  /NXCOMPAT
  /IGNORE:4221
  /INCREMENTAL
)

if ((CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64") OR (CMAKE_SYSTEM_PROCESSOR STREQUAL "AMD64"))
  add_link_options(/MACHINE:X64)
endif()
