RESOURCES_LIBRARY()



IF (HOST_OS_LINUX)
    DECLARE_EXTERNAL_RESOURCE(LLD_ROOT sbr:695139891)
ELSEIF (HOST_OS_DARWIN)
    DECLARE_EXTERNAL_RESOURCE(LLD_ROOT sbr:695139821)
ENDIF()

LDFLAGS_FIXED("-fuse-ld=$LLD_ROOT_RESOURCE_GLOBAL/ld")

END()
