#pragma once

#include "config-linux.h"

#undef HAVE_STDIO_EXT_H
#undef HAVE_FEATURES_H
#undef HAVE_UCONTEXT_H

#undef HAVE_SECURE_GETENV 
#undef HAVE___FREADING

#undef HAVE_DECL_PROGRAM_INVOCATION_NAME
#undef HAVE_DECL_PROGRAM_INVOCATION_SHORT_NAME
#define HAVE_VAR___PROGNAME 1

// fread_unlocked should be controlled by USE_UNLOCKED_IO, yet it is not
#undef USE_UNLOCKED_IO
#undef HAVE_DECL_FEOF_UNLOCKED
#undef HAVE_DECL_FERROR_UNLOCKED
#undef HAVE_DECL_FFLUSH_UNLOCKED
#undef HAVE_DECL_FGETS_UNLOCKED
#undef HAVE_DECL_FPUTC_UNLOCKED
#undef HAVE_DECL_FPUTS_UNLOCKED
#undef HAVE_DECL_FREAD_UNLOCKED
#undef HAVE_DECL_FWRITE_UNLOCKED
#undef HAVE_DECL_GETCHAR_UNLOCKED
#undef HAVE_DECL_GETC_UNLOCKED
#undef HAVE_DECL_PUTCHAR_UNLOCKED
#undef HAVE_DECL_PUTC_UNLOCKED

#define _GL_ARG_NONNULL(...)
#define _GL_ATTRIBUTE_FORMAT_PRINTF(...)
