/*
 * WARNING: do not edit!
 * Generated by util/mkbuildinf.pl
 *
 * Copyright 2014-2017 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#define PLATFORM "platform: darwin64-x86_64-cc"
#define DATE "built on: Wed Oct 20 15:29:23 2021 UTC"

/*
 * Generate compiler_flags as an array of individual characters. This is a
 * workaround for the situation where CFLAGS gets too long for a C90 string
 * literal
 */
static const char compiler_flags[] = {
    'c','o','m','p','i','l','e','r',':',' ','c','c',' ','-','f','P',
    'I','C',' ','-','a','r','c','h',' ','x','8','6','_','6','4',' ',
    '-','O','3',' ','-','W','a','l','l',' ','-','i','s','y','s','r',
    'o','o','t',' ','/','A','p','p','l','i','c','a','t','i','o','n',
    's','/','X','c','o','d','e','.','a','p','p','/','C','o','n','t',
    'e','n','t','s','/','D','e','v','e','l','o','p','e','r','/','P',
    'l','a','t','f','o','r','m','s','/','i','P','h','o','n','e','S',
    'i','m','u','l','a','t','o','r','.','p','l','a','t','f','o','r',
    'm','/','D','e','v','e','l','o','p','e','r','/','S','D','K','s',
    '/','i','P','h','o','n','e','S','i','m','u','l','a','t','o','r',
    '.','s','d','k','/',' ','-','m','i','o','s','-','s','i','m','u',
    'l','a','t','o','r','-','v','e','r','s','i','o','n','-','m','i',
    'n','=','1','0','.','0',' ','-','D','L','_','E','N','D','I','A',
    'N',' ','-','D','O','P','E','N','S','S','L','_','P','I','C',' ',
    '-','D','O','P','E','N','S','S','L','_','C','P','U','I','D','_',
    'O','B','J',' ','-','D','O','P','E','N','S','S','L','_','I','A',
    '3','2','_','S','S','E','2',' ','-','D','O','P','E','N','S','S',
    'L','_','B','N','_','A','S','M','_','M','O','N','T',' ','-','D',
    'O','P','E','N','S','S','L','_','B','N','_','A','S','M','_','M',
    'O','N','T','5',' ','-','D','O','P','E','N','S','S','L','_','B',
    'N','_','A','S','M','_','G','F','2','m',' ','-','D','S','H','A',
    '1','_','A','S','M',' ','-','D','S','H','A','2','5','6','_','A',
    'S','M',' ','-','D','S','H','A','5','1','2','_','A','S','M',' ',
    '-','D','K','E','C','C','A','K','1','6','0','0','_','A','S','M',
    ' ','-','D','R','C','4','_','A','S','M',' ','-','D','M','D','5',
    '_','A','S','M',' ','-','D','A','E','S','N','I','_','A','S','M',
    ' ','-','D','V','P','A','E','S','_','A','S','M',' ','-','D','G',
    'H','A','S','H','_','A','S','M',' ','-','D','E','C','P','_','N',
    'I','S','T','Z','2','5','6','_','A','S','M',' ','-','D','X','2',
    '5','5','1','9','_','A','S','M',' ','-','D','P','O','L','Y','1',
    '3','0','5','_','A','S','M',' ','-','D','_','R','E','E','N','T',
    'R','A','N','T',' ','-','D','Z','L','I','B',' ','-','D','N','D',
    'E','B','U','G','\0'
};
