// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_GUID_NCATBOOSTFBS_ITER_H_
#define FLATBUFFERS_GENERATED_GUID_NCATBOOSTFBS_ITER_H_

#include "guid.fbs.h"
#include "contrib/libs/flatbuffers/include/flatbuffers/flatbuffers_iter.h"

#endif  // FLATBUFFERS_GENERATED_GUID_NCATBOOSTFBS_ITER_H_
