# CMake generated Testfile for 
# Source directory: /Users/makar/Documents/Course work/Repository/catboost/util/generic/ut
# Build directory: /Users/makar/Documents/Course work/Repository/catboost/build_artifacts/util/generic/ut
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(util-generic-ut_0 "/opt/homebrew/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/makar/Documents/Course work/Repository/catboost/build/scripts/split_unittest.py" "--split-factor" "10" "--shard" "0" "/Users/makar/Documents/Course work/Repository/catboost/build_artifacts/util/generic/ut/util-generic-ut" "--print-before-suite" "--print-before-test" "--fork-tests" "--print-times" "--show-fails")
set_tests_properties(util-generic-ut_0 PROPERTIES  ENVIRONMENT "" LABELS "LARGE" PROCESSORS "1" _BACKTRACE_TRIPLES "/Users/makar/Documents/Course work/Repository/catboost/cmake/common.cmake;304;add_test;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.darwin-arm64.txt;101;add_yunittest;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.darwin-arm64.txt;0;;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.txt;30;include;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.txt;0;")
add_test(util-generic-ut_1 "/opt/homebrew/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/makar/Documents/Course work/Repository/catboost/build/scripts/split_unittest.py" "--split-factor" "10" "--shard" "1" "/Users/makar/Documents/Course work/Repository/catboost/build_artifacts/util/generic/ut/util-generic-ut" "--print-before-suite" "--print-before-test" "--fork-tests" "--print-times" "--show-fails")
set_tests_properties(util-generic-ut_1 PROPERTIES  ENVIRONMENT "" LABELS "LARGE" PROCESSORS "1" _BACKTRACE_TRIPLES "/Users/makar/Documents/Course work/Repository/catboost/cmake/common.cmake;304;add_test;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.darwin-arm64.txt;101;add_yunittest;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.darwin-arm64.txt;0;;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.txt;30;include;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.txt;0;")
add_test(util-generic-ut_2 "/opt/homebrew/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/makar/Documents/Course work/Repository/catboost/build/scripts/split_unittest.py" "--split-factor" "10" "--shard" "2" "/Users/makar/Documents/Course work/Repository/catboost/build_artifacts/util/generic/ut/util-generic-ut" "--print-before-suite" "--print-before-test" "--fork-tests" "--print-times" "--show-fails")
set_tests_properties(util-generic-ut_2 PROPERTIES  ENVIRONMENT "" LABELS "LARGE" PROCESSORS "1" _BACKTRACE_TRIPLES "/Users/makar/Documents/Course work/Repository/catboost/cmake/common.cmake;304;add_test;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.darwin-arm64.txt;101;add_yunittest;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.darwin-arm64.txt;0;;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.txt;30;include;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.txt;0;")
add_test(util-generic-ut_3 "/opt/homebrew/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/makar/Documents/Course work/Repository/catboost/build/scripts/split_unittest.py" "--split-factor" "10" "--shard" "3" "/Users/makar/Documents/Course work/Repository/catboost/build_artifacts/util/generic/ut/util-generic-ut" "--print-before-suite" "--print-before-test" "--fork-tests" "--print-times" "--show-fails")
set_tests_properties(util-generic-ut_3 PROPERTIES  ENVIRONMENT "" LABELS "LARGE" PROCESSORS "1" _BACKTRACE_TRIPLES "/Users/makar/Documents/Course work/Repository/catboost/cmake/common.cmake;304;add_test;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.darwin-arm64.txt;101;add_yunittest;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.darwin-arm64.txt;0;;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.txt;30;include;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.txt;0;")
add_test(util-generic-ut_4 "/opt/homebrew/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/makar/Documents/Course work/Repository/catboost/build/scripts/split_unittest.py" "--split-factor" "10" "--shard" "4" "/Users/makar/Documents/Course work/Repository/catboost/build_artifacts/util/generic/ut/util-generic-ut" "--print-before-suite" "--print-before-test" "--fork-tests" "--print-times" "--show-fails")
set_tests_properties(util-generic-ut_4 PROPERTIES  ENVIRONMENT "" LABELS "LARGE" PROCESSORS "1" _BACKTRACE_TRIPLES "/Users/makar/Documents/Course work/Repository/catboost/cmake/common.cmake;304;add_test;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.darwin-arm64.txt;101;add_yunittest;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.darwin-arm64.txt;0;;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.txt;30;include;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.txt;0;")
add_test(util-generic-ut_5 "/opt/homebrew/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/makar/Documents/Course work/Repository/catboost/build/scripts/split_unittest.py" "--split-factor" "10" "--shard" "5" "/Users/makar/Documents/Course work/Repository/catboost/build_artifacts/util/generic/ut/util-generic-ut" "--print-before-suite" "--print-before-test" "--fork-tests" "--print-times" "--show-fails")
set_tests_properties(util-generic-ut_5 PROPERTIES  ENVIRONMENT "" LABELS "LARGE" PROCESSORS "1" _BACKTRACE_TRIPLES "/Users/makar/Documents/Course work/Repository/catboost/cmake/common.cmake;304;add_test;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.darwin-arm64.txt;101;add_yunittest;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.darwin-arm64.txt;0;;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.txt;30;include;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.txt;0;")
add_test(util-generic-ut_6 "/opt/homebrew/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/makar/Documents/Course work/Repository/catboost/build/scripts/split_unittest.py" "--split-factor" "10" "--shard" "6" "/Users/makar/Documents/Course work/Repository/catboost/build_artifacts/util/generic/ut/util-generic-ut" "--print-before-suite" "--print-before-test" "--fork-tests" "--print-times" "--show-fails")
set_tests_properties(util-generic-ut_6 PROPERTIES  ENVIRONMENT "" LABELS "LARGE" PROCESSORS "1" _BACKTRACE_TRIPLES "/Users/makar/Documents/Course work/Repository/catboost/cmake/common.cmake;304;add_test;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.darwin-arm64.txt;101;add_yunittest;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.darwin-arm64.txt;0;;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.txt;30;include;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.txt;0;")
add_test(util-generic-ut_7 "/opt/homebrew/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/makar/Documents/Course work/Repository/catboost/build/scripts/split_unittest.py" "--split-factor" "10" "--shard" "7" "/Users/makar/Documents/Course work/Repository/catboost/build_artifacts/util/generic/ut/util-generic-ut" "--print-before-suite" "--print-before-test" "--fork-tests" "--print-times" "--show-fails")
set_tests_properties(util-generic-ut_7 PROPERTIES  ENVIRONMENT "" LABELS "LARGE" PROCESSORS "1" _BACKTRACE_TRIPLES "/Users/makar/Documents/Course work/Repository/catboost/cmake/common.cmake;304;add_test;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.darwin-arm64.txt;101;add_yunittest;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.darwin-arm64.txt;0;;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.txt;30;include;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.txt;0;")
add_test(util-generic-ut_8 "/opt/homebrew/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/makar/Documents/Course work/Repository/catboost/build/scripts/split_unittest.py" "--split-factor" "10" "--shard" "8" "/Users/makar/Documents/Course work/Repository/catboost/build_artifacts/util/generic/ut/util-generic-ut" "--print-before-suite" "--print-before-test" "--fork-tests" "--print-times" "--show-fails")
set_tests_properties(util-generic-ut_8 PROPERTIES  ENVIRONMENT "" LABELS "LARGE" PROCESSORS "1" _BACKTRACE_TRIPLES "/Users/makar/Documents/Course work/Repository/catboost/cmake/common.cmake;304;add_test;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.darwin-arm64.txt;101;add_yunittest;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.darwin-arm64.txt;0;;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.txt;30;include;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.txt;0;")
add_test(util-generic-ut_9 "/opt/homebrew/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/makar/Documents/Course work/Repository/catboost/build/scripts/split_unittest.py" "--split-factor" "10" "--shard" "9" "/Users/makar/Documents/Course work/Repository/catboost/build_artifacts/util/generic/ut/util-generic-ut" "--print-before-suite" "--print-before-test" "--fork-tests" "--print-times" "--show-fails")
set_tests_properties(util-generic-ut_9 PROPERTIES  ENVIRONMENT "" LABELS "LARGE" PROCESSORS "1" _BACKTRACE_TRIPLES "/Users/makar/Documents/Course work/Repository/catboost/cmake/common.cmake;304;add_test;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.darwin-arm64.txt;101;add_yunittest;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.darwin-arm64.txt;0;;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.txt;30;include;/Users/makar/Documents/Course work/Repository/catboost/util/generic/ut/CMakeLists.txt;0;")
